### ISSUE TITLE
User that has already left private channel can still remove/rejoin channel

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1000]
**Describe the bug**
When user leaves private channel, she/he can no longer do anything towards that channel

**To Reproduce**
1. User A invites user B to a private channel
2. User B clicks to view members in that channel
3. User B removes himself from the channel, DON'T close the Member list dialog
4. User B removes user A from the channel
5. User B search himself and add himself to the channel

**Expected behavior**
Step 4: user B does not have permission to remove user A from the channel because he is no longer a member
Step 5: User B should not be able to add himself again to the channel (only members can do that)

**Actual result**
Step 4: User B can take action to remove member A from the channel from frontend (even though user A is not really removed)
Step 5: User B can rejoins private channel without being invited

![Peek 2021-03-10 10-12.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/9cc55d06-5f2f-4e04-bbc4-698b0206872e)

**Comment by RomaricMourgues** [comment]
Thanks there is a mix of Backend and Frontend errors here, we’ll fix this
