### ISSUE TITLE
Deactivated user is still shown to other users

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1001]
**Describe the bug**
user should not be able to send message/add DEACTIVATED user to channel

**To Reproduce**
1. As company owner/admin, deactivate an user account
2. Try to send direct message to the above user or add the above user to channels

**Expected behavior**
- Deactived user should not be shown up in search result

**Comment by tlle14** [comment]
Deactivated user is able to login to the suspending company. Please retest after it's fixed.
Story: https://ci.linagora.com/linagora/lgs/saas/portal/specifications/-/issues/30
