### ISSUE TITLE
Join channel search is buggy

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#1035]
See attached video, the list is not filled at the right time:

- [x] Typing `cc` displays something while it should not
- [x] Deleting text does not filter the list correctly
- [x] List is empty on first open the modal

What about displaying a list of channel the user is not already in on first state?

https://user-images.githubusercontent.com/264403/111648028-493dd300-8803-11eb-81a9-3f6a2cf81fe2.mov

**Comment by RomaricMourgues** [comment]
@chamerling do you have an estimate on this ? Do you think it can be included in the Q3.600 release during next week?

**Comment by chamerling** [comment]
@RomaricMourgues I will have a look (hope to not refactor all), assign it to me :)

**Comment by RomaricMourgues** [comment]
If we need to refactor it we will keep it for next month no worries

**Comment by chamerling** [comment]
💪🏼

**Comment by BenoitTallandier** [comment]
@chamerling I guess this issue is related to #1541 
Are you working on this issue ? 
If we don't need to refactor this part, I can work on these bug :)

**Comment by RomaricMourgues** [comment]
We probably need to refactor this part but you can refactor it yourself I think.

**Comment by chamerling** [comment]
@BenoitTallandier I am not working on it for now. I can later this week if I succeed to complete my current refactoring
