### ISSUE TITLE
Welcome page links are not well positioned

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#1037]
`Déconnecter` link must be in a new line

<img width="693" alt="Capture d’écran 2021-03-18 à 18 34 50" src="https://user-images.githubusercontent.com/264403/111670993-c0319680-8818-11eb-9527-452e611b65e5.png">

**Comment by stephanevieira75** [comment]
Already fixed, i'm closing this issue. 
![Capture d’écran de 2021-11-29 11-32-13.png](https://images.zenhubusercontent.com/5f4e3d2d91dca0478164f0b5/ec963008-2613-48cc-a2b4-c7547fc8a687)
