### ISSUE TITLE
Add guest/member/admin information during importation to console

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1045]
We need to:

- [x] add a "role" column and keep it up to date with console on php side (done by Romaric)

- [x] add a "role" column to company_user entity and update it using console results on each member add to "admin", "member" or "guest" (we don't set it to "owner")

- [x] when importing from Twake, this is how we know if someone is a guest: ` "_user_is_guest" => $workspaceMember->getExterne() || ($groupUser ? $groupUser->getExterne() : true), ` Correctly get “external” status (use workspace and group user information)

- [x] set user identity_provider as "console" in database for each users

- [x] Set the company identity_provider and identity_provider_id in companies

- [x] Company doubles ? -> Ask Christophe (-> to retest)

- [x] Implement name and avatars api update in import script

- [x] Implement name and avatars api update in hooks

**Comment by hantt12** [comment]
So I am assumming that this is a technical backlog and QA just skips it?

**Comment by RomaricMourgues** [comment]
Exact, Benoit will test if guest account from before the console were imported successfully.

**Comment by hieuhoang998** [comment]
@RomaricMourgues I access by guest account ( account migration) and now I can create a channel.....have full permission of member role.
So do you fix this case ?

**Comment by RomaricMourgues** [comment]
Can you give me the company name and account email ?

**Comment by hieuhoang998** [comment]
After that I promote the guest account to member role then edit to the guest role again then it's ok, so please check with the account guest (migration account to check this case)
