### ISSUE TITLE
Guest can mention everyone on the workspace

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1050]
**Describe the bug**
As a guest user, I can mention (and see) every user on the workspace, even the other guest that are not in the current channel.

**To Reproduce**
1. Open Twake with a guest account
2. Try to mention an other guest that is not in the channel

**Expected behavior**
A guest shouldn't be able to mention someone else outside people in the channel.

**Comment by chamerling** [comment]
Done in https://github.com/linagora/Twake/pull/1366
