### ISSUE TITLE
Unable to join ElasticSearch!

### ISSUE THREAD

**Issue by johnathanarroyo** [linagora/Twake#1051]
Hi I am trying to use this plugin.
This is great...
But when I try to install this it shows "Unable to join ElasticSearch!"
https://prnt.sc/10tk45a
Please help me to resolve the issue.
Thanks.

**Comment by RomaricMourgues** [comment]
Hi, you can disable elasticsearch in your Parameters.php configuration:
```
            "es" => [
              "host" => false
            ],
```

We are working on a new installation procedure for the end of the week, you can also wait for Friday :)

**Comment by johnathanarroyo** [comment]
After I fix the issue it shows the following db error.
![image](https://user-images.githubusercontent.com/26065238/112516078-22782300-8d54-11eb-8d17-c40b1241d2cd.png)

**Comment by RomaricMourgues** [comment]
This is normal, is Twake working after this ?

**Comment by johnathanarroyo** [comment]
no
it doesn't work.
![image](https://user-images.githubusercontent.com/26065238/112565729-d8fef680-8d9a-11eb-8302-594e6293ba11.png)
As you can see here, 2 docker containers are not started. I know twake_nginx_1 is depends on twake_node_1.
Please let me know 
Thanks.

**Comment by johnathanarroyo** [comment]
![image](https://user-images.githubusercontent.com/26065238/112570644-ac031180-8da3-11eb-9a9c-a31edbdeac15.png)
this is error cycling in console
