### ISSUE TITLE
The error page displays when close a thread while opening other channel in other workspace.

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1053]
**Describe the bug**
When closing the thread message while opening another channel in another workspace, it causes an error. 
Please see the evidence:
![Peek 2021-03-24 11-02](https://user-images.githubusercontent.com/69950655/112253689-c51b9d80-8c91-11eb-92ad-9eac28680e16.gif)

**To Reproduce**
1. On Workspace A, channel A, open a thread message. 
2. Navigate to Workspace B, open a channel B. 
3. Close the thread of channel A
4. Verify the issue

**Expected behavior**
The thread should be closed without any error.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 88.0

**Comment by RomaricMourgues** [comment]
Thanks! This issue is fixed in the next release planned this week :)
