### ISSUE TITLE
Missing loader and toaster on blocked accounts "verify email" button + blocked accounts can't logout + more

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1054]
- [x] Missing loader and toaster on blocked accounts "verify email" button

- [x] Blocked accounts cannot logout, we need to add a button to logout

- [x] Blocked account header and modal are not shown until we open a channel

- [x] When onboarding is shown, in some cases the users may have already verified its email, in this case we can hide the "verify email" button (see image bellow)

![Screenshot 2021-03-24 at 13.57.37.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/a02e31f2-7e4e-4bf8-862c-8bf3be64c6f2)

**Comment by tlle14** [comment]
**1. Pass:** Have a loader and toaster after resend the verify email
[Peek 2021-05-11 15-29.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2fc368e3-34a3-4508-8cc4-800c7091d8d1)

**2. Pass:** Have the logout button
[image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/05e44e08-fa65-4e75-bbd6-8aa0a8a50019)

**3. Pass:** 
- Have the default selected channel
- always having verification banner
[image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6fd8a9a1-3b7f-44be-8d7e-bc1999b3f3ee)

4. Pass: Click the verify email will show the toaster as in the image below. 
[image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/b47a022b-608c-4f0a-b3fc-a5d000adbd18)
