### ISSUE TITLE
[Workspace] Display many workspaces and name of workspace is hide

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1077]
## Describe the bug

After sign up account then sign in twakeweb then display many workspaces and name of workspace is hide

### Precondition: sign up successfully

- 1.Go to Sign in page

- 2.Input email and password

- 3.Click sign in

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

  - Firefox ,version 85.0.2

  - Chrome version 88.0.4

- Mobie Oppo reno version 11.1,chrome app

## image

![2021-03-29_10-07.png](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/43e7432d-ca2c-49f6-a2dc-0ec9358fed5b)

**Comment by phamtuanchip** [comment]
- every time we refresh the page, it created a new workspace 
- the workspace name should not same as the company name, when we signup the company name is "My company" and workspace is the same as "My company" workspace, suggest default workspace should be General/Default etc
