### ISSUE TITLE
[Twake console/twake web] Click twake web icon on grid then redirect to log in page

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1078]
## Describe the bug

Click twake web icon on grid then redirect to log in page

### Precondition: sign in twake console successfully

- 1.Click twake web on the grid

- 2.Check twake web page

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

  - Firefox ,version 85.0.2

  - Chrome version 88.0.4

- Mobie Oppo reno version 11.1,chrome app

image:
![2021-03-29_15-08.png](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/208bd7fb-1bad-4320-b589-eb8995951a05)

![2021-03-29_15-08_1.png](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/8683c836-c598-414d-8465-14d6ca0b8dcb)

**Comment by BenoitTallandier** [comment]
@hieuhoang998 could you try on qa or prod env ? It seams that it is working on these platform : 

https://user-images.githubusercontent.com/22451567/124457000-a0a08880-dd8b-11eb-8ab5-6545d1623fc9.mov
