### ISSUE TITLE
[Sign in] Can't sign in

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1079]
## Describe the bug

Can't sign in twake console

### Precondition: 

- 1.Go to Sign in page : http://web-twakeconsole.linagora.vn/

- 2.Input email and password

- 3.Click sign in

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

  - Firefox ,version 85.0.2

  - Chrome version 88.0.4

- Mobie Oppo reno version 11.1,chrome app

## image/video

[kazam_nxuqtoxr.movie](/uploads/33759c6e1e34e3dc5717951f27e88544/kazam_nxuqtoxr.movie)

User story link: https://ci.linagora.com/linagora/lgs/saas/portal/specifications/issues/47

**Comment by RomaricMourgues** [comment]
Is it working when coming from http://twake.dev.lin-saas.com/ ?

**Comment by BenoitTallandier** [comment]
@hieuhoang998 could you try it again? :)

**Comment by hieuhoang998** [comment]
Can't sign in at the first time, after 2-3 times just sign in successfully, i mean http://twake.dev.lin-saas.com/

**Comment by BenoitTallandier** [comment]
@hieuhoang998 Could you try again? I tested and it is working on my side.

https://images.zenhubusercontent.com/271994210/762f2dc4-c4ca-4635-939d-50ac007af432/signin.mov

**Comment by hieuhoang998** [comment]
it's ok
