### ISSUE TITLE
[Twake app] Owner can not add user/admin to work space  when owner click icon twake app on twake console

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1080]
pre: user/admin had account and active

1.Open twake console and sign in successfully

2.Click Users and checklist user added

3.Click the Twake app on the header 

4.Create workspace and add user/admin

Actual result: Can not search user/admin by email and can not add

Expect result: Can not find user/admin and add user/admin successfully

**Comment by RomaricMourgues** [comment]
Can you give me the endpoint ?
Also can you confirm that if you want to invite the user with `Twake > Collaborators > Add Collaborator` you get "Not a console company" error ?

**Comment by hieuhoang998** [comment]
I use staging enviroment, no i don't got notice
