### ISSUE TITLE
[Workspace] Display many workspace and even can't see name of work space on mobile phone

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1081]
## Describe the bug

Display many workspace and even can't see name of work space on mobile phone

### Precondition: 

- 1.Sign in successfully

- 2.Click twake icon on the grid 

- 3.Check workspace

#### Expect result:

- Display 2 workspaces with names (I have two workspaces in this company)
- Show the company at the bottom

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

- iphone 11 pros, safari

- Mobie Oppo reno version 11.1,chrome app

## image

![6D15D76B-5ECB-445C-AF6C-534FE4D8E038.jpg](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/fbdecf37-4864-4e1b-9fdc-14479375e235)

![processed4.jpeg](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/42188616-f6fa-443e-85f3-0ab8e4378f9f)

**Comment by hantt12** [comment]
As far as I can see, there are more than 2 workspaces being displayed on mobile now
![IMG_8431.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/30d3d3ae-3680-483e-8218-1f0c04d9844e)

**Comment by RomaricMourgues** [comment]
@hantt12  this is the expected output: be able to see all workspaces and the company at the bottom.

**Comment by hantt12** [comment]
Then please update the backlog description when you change your mind. Thanks

**Comment by RomaricMourgues** [comment]
Well the description is accurate, @hieuhoang998 did have 2 workspaces but the app showed an infinite list of workspaces, you do have 4 workspaces and the app successfully shows 4 workspaces. I add this precision to. the description.
