### ISSUE TITLE
A guest cannot see the channel details

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1084]
Related to #333

# Actual Result
A guest cannot see the channel details (channel name, description, privacy...), excepts the member list in the channel
![Peek 2021-03-30 14-37.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d83496df-f247-40b9-9119-02c551c8caee)

# Expected Result
A guest should be able to see the channel details, and cannot edit.

# Environment
QA environment

**Comment by tlle14** [comment]
Cc: @BenoitTallandier @hantt12

**Comment by BenoitTallandier** [comment]
I don't think that we should print the information popup. All of these information are already shown in the interface :
- Privacy is shown on with the lock
- Name & description is shown in the header of the channel
:)
