### ISSUE TITLE
Cannot upload an attached image in the message

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1109]
**Describe the bug**
Cannot upload an image to the message. It displays an error log in the console debug.
![image](https://user-images.githubusercontent.com/69950655/113547212-a913e680-9617-11eb-895d-c54e252f8a89.png)

**To Reproduce**
1. Open a channel
2. Click a clipping icon
3. Upload an image
4. Verify the issue

**Expected behavior**
It should be able to send an attached image in the message

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - QA Environment

**Comment by BenoitTallandier** [comment]
It was fixed :)

**Comment by tlle14** [comment]
Retest pass on QA environment
![image](https://user-images.githubusercontent.com/69950655/122176170-853e0e00-ceae-11eb-832a-b3e1f6bb62c9.png)
