### ISSUE TITLE
Able to add a non-workspace-member to a channel of the workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1110]
**Describe the bug**
The user is able to add another user, who is not a member of the corresponding workspace, to a channel of the workspace.

Workspace member list:
![image](https://user-images.githubusercontent.com/69950655/113554677-e1212680-9623-11eb-99d8-f71cc61b01a7.png)

Channel member list
![image](https://user-images.githubusercontent.com/69950655/113554742-fd24c800-9623-11eb-86f2-254d1adbf5bf.png)

**Expected behavior**
It should only be able to add a member of the workspace to the channel.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome 
 - QA Environment

**Comment by BenoitTallandier** [comment]
It was fixed :)

**Comment by tlle14** [comment]
Hi @BenoitTallandier 
I don't think the problem was solved on QA environment. 
The actual result is when a guest is invited to a channel (of a workspace that he is not a member), he is added to the workspace but unable to see the channel. 
![image](https://user-images.githubusercontent.com/69950655/122175056-83277f80-cead-11eb-9294-3065b0fa6638.png)

**Comment by BenoitTallandier** [comment]
Ok, it's not the same bug I guess. 
It's about the guest system. We'll fix this soon. 
Thank you for this feedback :)

**Comment by tlle14** [comment]
Ah we have the issue already https://github.com/linagora/Twake/issues/1273#issuecomment-862426036
I should close this ticket
