### ISSUE TITLE
Bug in email confirmation

### ISSUE THREAD

**Issue by odin78** [linagora/Twake#1112]
**Describe the bug**
The url to click when you confirm your inscription is truncated
"La page que vous consultiez essaie de vous rediriger vers une url non valide (http:///login?verifyMail&m=xxxx@gmail.com&c=1ed-994-a45&token=dce22ff70867743acb08c5e43e1445f0a49049180768544446955e17e7a93fd0ab9745c9aeb94729).
(i put "xxx" instead of my personal email)

**Expected behavior**
The url should be something like this "http://name.xx/....)

**Desktop (please complete the following information):**
 - OS: Redhat
 - Browser Firefox
 - Version 78.9 ESR

**Comment by odin78** [comment]
just another detail: i notice the same problem ,whatever the system

**Comment by RomaricMourgues** [comment]
Is it on a local installation or online (beta.twake.app) ?

**Comment by odin78** [comment]
It is a local installation
Before, i've tried to install by the sources but i had errors.
whatever the system (linux or windows), i have the same thing

**Comment by RomaricMourgues** [comment]
Can you send me the configuration you have in Parametesr.php in the "mail" section ?

**Comment by odin78** [comment]
I've defined nothing
In Parameters.php, what i see 
  "mail" => [
                "sender" => [
                    "host" => "",
                    "port" => "",
                    "username" => "",
                    "password" => "",
                    "auth_mode" => "plain"
                ],
                "template_dir" => "/src/Twake/Core/Resources/views/",
                "twake_domain_url" => "https://twakeapp.com/",
                "from" => "noreply@twakeapp.com",
                "from_name" => "Twake",
                "twake_address" => "Twake, 54000 Nancy, France",
                "dkim" => [
                    "private_key" => "",
                    "domain_name" => '',
                    "selector" => ''

To gain time, I've just downloaded here https://twake.app/en/download the linux package,unzipped,created the account and the confirmation email was sent. The problem was the same
