### ISSUE TITLE
Emojis in emoji picker look blurry

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1118]
**Describe the bug**
Emojis in emoji picker look blurry. There is a way to improve the quality of images ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/22451567/113709021-4cc9c900-96e2-11eb-978a-cb096c321954.png)

**Comment by RomaricMourgues** [comment]
We can't fix this with this emoji picker.
