### ISSUE TITLE
After I create company I can't see it.

### ISSUE THREAD

**Issue by johnathanarroyo** [linagora/Twake#1121]
![image](https://user-images.githubusercontent.com/26065238/113872777-09ff0400-9769-11eb-9ad1-b5579e0fff76.png)
After I create company it shows nothing.
Can you please let me know what the bug is?

Thanks

**Comment by RomaricMourgues** [comment]
It seems the bottom of your screen is truncated, what browser / OS are you using ?

**Comment by johnathanarroyo** [comment]
I am using Chrome and I tested on Mac on local and Linux (Ubuntu) on server.
And I can't see the Twake icon at bottom
![image](https://user-images.githubusercontent.com/26065238/113873493-b8a34480-9769-11eb-8340-918402c81eb9.png)

**Comment by johnathanarroyo** [comment]
If I refresh browser, it shows this screen
![image](https://user-images.githubusercontent.com/26065238/113873996-2fd8d880-976a-11eb-9cc8-793358a474b8.png)

**Comment by RomaricMourgues** [comment]
"Twake" in my image is my company name, this is where you should see the list of companies.

When you click on "Create my company" and follow the process you are back to the first image but as soon as you reload it shows this again ?

**Comment by johnathanarroyo** [comment]
There are 3 steps in creating company.
After I input company name and go the next steps ( total 3steps), then it shows dashboard but without company as I mentioned above.
And if I refresh the page, it shows "Create my company" again.

**Comment by RomaricMourgues** [comment]
Can you try reinstall Twake following this procedure:

- Remove the folder docker-data completely (it will remove your database content)
- Start scylladb and wait 3-5 minutes: docker-compose up -d scylladb
- Start php only and wait again 3-5 minutes: docker-compose up -d php
- If you look at the php logs you will see that it is creating the Twake tables
- Start every other nodes: docker-compose up -d

Also ensure you have enough memory and CPU (2cpu + 8go ram is good)

Romaric

**Comment by johnathanarroyo** [comment]
![image](https://user-images.githubusercontent.com/26065238/113896755-15f5c080-977f-11eb-8bf3-ed2a688664a9.png)
Looks like there are errors in creating table?

**Comment by RomaricMourgues** [comment]
How yes, you're right, there is an error in the code, let me check for you

**Comment by RomaricMourgues** [comment]
A fix was pushed on main and on the docker repositories just now. Can you try again after a `docker-compose pull` ?

**Comment by johnathanarroyo** [comment]
on php docker, it shows many errors about Db.
![image](https://user-images.githubusercontent.com/26065238/113919969-0aaf8e80-9799-11eb-9073-68403d0e79d3.png)
![image](https://user-images.githubusercontent.com/26065238/113920056-24e96c80-9799-11eb-8c0e-b351961c66dd.png)

**Comment by RomaricMourgues** [comment]
Ok, I investigate more tomorrow, I don't know yet where it comes from

**Comment by linuxart** [comment]
Same issue with 2021.Q1.434

**Comment by RomaricMourgues** [comment]
I found the issue and I am currently fixing it, sorry all for the installation bug.

**Comment by RomaricMourgues** [comment]
Thank you very much for your help finding this bug 🙏
A fix was pushed and published to docker-hub just now. I hope it will work fine now!

Don't forget to:
- Remove the folder docker-data completely (it will remove your database content)
- Start scylladb and wait 3-5 minutes: docker-compose up -d scylladb
- Start php only and wait again 3-5 minutes: docker-compose up -d php
- If you look at the php logs you will see that it is creating the Twake tables
- Start every other nodes: docker-compose up -d

**Comment by linuxart** [comment]
Works for me. Thanks!

**Comment by johnathanarroyo** [comment]
Thank you very much. It works!
