### ISSUE TITLE
"Edit from console" is linked to the QA server

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1122]
**Describe the bug**
The console url is hard coded 

**To Reproduce**
1. Go to Collaborateur settings
2. Click on '...'
3. "Edit from console" 
4. You'll be redirected in the QA version

**Screenshots**
![image](https://user-images.githubusercontent.com/22451567/113879731-1dd35600-97bb-11eb-9bcd-5813d4de49cc.png)

in workspacePartner.js
![image](https://user-images.githubusercontent.com/22451567/113880049-6a1e9600-97bb-11eb-923e-56b6eebffd78.png)

**Comment by hantt12** [comment]
I will verify this issue when the new version is deployed to Production

**Comment by RomaricMourgues** [comment]
We replaced the hard-coded link, so if it still works on qa then it means we are successfully using the configuration from backend and so you can mark it as successful :)

**Comment by BenoitTallandier** [comment]
When I click on the button "edit from the console", I'm redirected to "https://console.twake.app/company/users", but now, we need this url: "https://console.twake.app/company/:companyID/users".
We need to update the URL

**Comment by RomaricMourgues** [comment]
Configuration updated on prod 👍
