### ISSUE TITLE
Upload popup

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1126]
**Describe the bug**
There is a little glitch in css. The button is above the popup

**Screenshots**
![image](https://user-images.githubusercontent.com/22451567/113889742-d00f1b80-97c3-11eb-8c96-656db84ec5d0.png)

**Comment by chamerling** [comment]
Hello,

I was about to open an issue about the upload popup about some refactoring on it. Can we discuss about that tomorrow? (This can be a good issue for @tissarni to work on since he is working on the new upload service) cc @RomaricMourgues

**Comment by RomaricMourgues** [comment]
Of course it will be part of his work, for now we focus on the backend rewrite but then we will redo the frontend part, including the progress indicator. I affect @tissarni to this right now.
