### ISSUE TITLE
Have a button to invite user when there is <= 5 collaborators in the company

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1131]
![image](https://user-images.githubusercontent.com/22451567/114147799-58eb9b80-9919-11eb-8cc3-3ec83feeb621.png)

**Comment by hantt12** [comment]
Does it mean that the button is available ONLY when there is only one person in the workspace? Please kindly confirm your expectation @BenoitTallandier 

Currently "Add colleagues" button is always there as long as user has the permission to do that

**Comment by RomaricMourgues** [comment]
The thresold was changed to 5, I update the description

**Comment by hantt12** [comment]
Button is still shown when number of collaborator = 6 even though I have refreshed the page

![Peek 2021-04-15 11-10.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/82a1c7d5-f32d-4a14-a54e-962e7abbf5a7)

**Comment by hantt12** [comment]
Another minor isssue https://github.com/linagora/Twake/issues/1152

**Comment by RomaricMourgues** [comment]
It seems to be an error from the hooks in Twake, when we invite a lot of people each of them send a hook event in the same time so our value can be not the last one.
I create a new issue for this (I think it is minor as we don't display this value anywhere yet).
You can close this issue (this is not relted to the button itself)

Thanks for the minor issue :)

**Comment by hantt12** [comment]
ok
