### ISSUE TITLE
Update url (id company)  

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1145]
Des:Display blank page when user select collaborators -> identity of company

**Comment by hieuhoang998** [comment]
@phamtuanchip

**Comment by phamtuanchip** [comment]
Currently in console we update new format of URL 
- Detail company profile http://host/companies/e09389a9-6861-4824-a3c8-973b3b740e5b
- List users http://host/companies/e09389a9-6861-4824-a3c8-973b3b740e5b/users
-> every link to users or company profile should send the format: http://host/companies/{companyid} and http://host/companies/{companyid}/users 
Please update in dev env

**Comment by RomaricMourgues** [comment]
Thanks, I fix it and it will be on QA very soon
