### ISSUE TITLE
User mentions are converted to twacode in inconsistent way.

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake#1149]
**Describe the bug**
Sometimes in twacode the user mention is stored as
```
                   {
                        "start": "@",
                        "content": "username:023cc4e8-6e82-11ea-9fc9-XXXXac120004"
                    },
 ```
And sometimes (rarely), you can also see

```
                    {
                        "start": "@",
                        "content": "username:023cc4e8-6e82-11ea-9fc9-XXXXac120004:023cc4e8-6e82-11ea-9fc9-XXXac120004"
                    },
```
i.e. the userID is doubled

**To Reproduce**
You can go through the last 50 messages of QA channel in Software workspace (Linagora company). You can find both cases there.

**Expected behavior**
Content part of the twacode mentions should be consistent. We should stick to a single format.

**Comment by BenoitTallandier** [comment]
@bobs4462 Is this issue still up to date ? Did you see recently this bug ?

**Comment by bobs4462** [comment]
No, I haven't seen it for quite some time

**Comment by BenoitTallandier** [comment]
Ok, I check too and I couldn't neither find this bug. I close this issue, If you see this again, we'll open an new issue :)
