### ISSUE TITLE
Firefox/Incorrect highlight in left menu after user click Back/Next in browser

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1154]
**Describe the bug**
After user uses Back/Next button everything should work as normal

**To Reproduce**
1. User is currently viewing channel A
2. User click on channel list to move to channel B
3. User clicks on Back button on browser to go back to channel A
4. User click on channel list to go to channel B

**Expected behavior**
Channel B is highlighted on the channel list

**Screenshots**
Channel A is still highlighted instead of channel B

![Peek 2021-04-15 14-37.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/7dcb58f1-8eec-473c-a1d0-cd89f9facc67)

**Comment by BenoitTallandier** [comment]
Seams to be fixed.
https://images.zenhubusercontent.com/271994210/b0a85edc-cb28-4eee-91ba-0f7cf3e54a0e/higlight.mov
