### ISSUE TITLE
Firefox/ Highlighter stays in Tasks 

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1155]
**Describe the bug**
Once user clicks on Tasks in the left menu, the highlighter stays there until user refreshes the page

**To Reproduce**
1. Go to Twake web
2. Click on a channel in left menu
3. Click on Tasks in the left menu
4. Click on a certain channel or Calendar/Documents...

**Expected behavior**
When user clicks to select, the highlighter is on the selected item

**Current behavior**
Highlighter stays in Tasks. User has to refresh the page so that Twake web can work as normal

![Peek 2021-04-15 14-58.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/505c8d52-9ab3-4c93-b37a-80672699bce9)

**Comment by BenoitTallandier** [comment]
Seams to be fixed on firefox
