### ISSUE TITLE
Emoji are not aligned with the text

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1159]
**Describe the bug**
Some emoji are not aligned with the text (like : skull_and_crossbones:)

**To Reproduce**
1. Send a message with text and : skull_and_crossbones:
2. See the alignement
 
**Screenshots**
![image](https://user-images.githubusercontent.com/22451567/114990674-0c640b00-9e99-11eb-8d8f-89937987f393.png)

**Comment by chamerling** [comment]
☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️
