### ISSUE TITLE
Logout in Twake web does not kill session in Twake Console and other way

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1160]
**Solution**
1. The OIDC logout callback is `/ajax/users/console/openid/logout_success`
2. It redirects to `/login?auto` or `/login?error_code=aaa` if error
3. We need to delete the JWT session in localstorage when passing to login?auto

**Comment by chamerling** [comment]
Don't we use OIDC? If yes, everything is already provided by it to manage logout called Global logout.

**Comment by RomaricMourgues** [comment]
Are you so sure with LemonLDAP? :p 
Just kidding, we provided the logout endpoint for OIDC (that should be run in an iframe by LemonLDAP standards) but it is probably badly configured or url is not set, I will check as soon as I have time.

**Comment by RomaricMourgues** [comment]
Related to #1332
