### ISSUE TITLE
"Identity of company" link is not working

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1170]
**Describe the bug**
Company identity link go to https://console.twake.app/company
This should be https://console.twake.app/companies/:companyID

**Screenshots**
![image](https://user-images.githubusercontent.com/22451567/115206157-97900b80-a0fa-11eb-9618-17ef0505fb2e.png)

**Comment by RomaricMourgues** [comment]
The configuration as updated few minutes ago, can you try again after reload ?
+ If this is a "old" company, could you try to change the company name from console, reload Twake and click on the button again ?

**Comment by BenoitTallandier** [comment]
True, it's working 👏
