### ISSUE TITLE
Scroll bar disappear when openning a parent message which is too long

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1171]
# Precondition
A Parent message has about 25000 characters
![image](https://user-images.githubusercontent.com/69950655/115223204-bbbd0e00-a135-11eb-86bb-53683df1a167.png)

# Actual Result
When opening a thread with a parent message too long, the scroll is lost. 

# Expected Result
1. The message should have a limitation. 
2. When the message is too long, it should have a scroll

# Environment
Chrome, Firefox on Linux
QA environment

**Comment by RomaricMourgues** [comment]
@stephanevieira75 You fixed this one but there is a small issue on QA, the message is displayed with its answers, it should not.

**Comment by RomaricMourgues** [comment]
![Screenshot 2021-07-20 at 10.23.51.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/783e51ca-bdfa-461d-8722-3df2a3d97c83)

**Comment by stephanevieira75** [comment]
Fixed [here](https://github.com/linagora/Twake/pull/1470)
