### ISSUE TITLE
No notification for first message in a direct channel (probably that badge try to be created before user is in the channel)

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1175]
#### Describe the bug
When I start a new direct discussion with someone by sending the first message, the other user is not notified with a badge.

#### To Reproduce
- Open a new direct discussion
- Send the first message
- Go on the other account
- You won't see the badge

#### Screenshots
https://user-images.githubusercontent.com/22451567/118807606-cee40a80-b8a8-11eb-871d-e08d691d8e42.mov

**Comment by hantt12** [comment]
still happens in https://web.qa.twake.app/
Tested 22.06.2021 using Chrome in Windows 10

**Comment by RomaricMourgues** [comment]
Thanks let me check this

**Comment by RomaricMourgues** [comment]
Can you try again?
