### ISSUE TITLE
[Direct messages] When user send a direct message, the message doesn't appear (using "new discussion" button)

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1177]
## Describe the bug

When user sign up account then add user to direct chat then can't display content message 

### Precondition: sign up successfully

- 1.Go to twake web

- 2.Add user to direct chat

- 3.Input hello 

### Server
 - staging, qa environment
### Client 
- Desktop (please complete the following information):*

  - Firefox ,version 85.0.2

  - Chrome version 88.0.4

- Mobie Oppo reno version 11.1,chrome app

## image/video

please contact me to give you video

**Comment by hantt12** [comment]
Tested in QA platform today: 
- There is no "new discussion" button. As far as I remember we don't have this button in direct chat then I am not sure about the title of this bug
- When I send the direct message, the message is not shown. I had to refresh the page to see it

**Comment by RomaricMourgues** [comment]
Thanks, so it doesn't pass, ignore the "new discussion" button, it is just about the input. I try to fix it today

**Comment by RomaricMourgues** [comment]
It is fixed, can you try again ?
Also giphy, jitsi, and reactions should be faster / work better than before
