### ISSUE TITLE
User is now able to find himself to send direct message

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1217]
**Describe the bug**
User is able to find himself to initiate direct message but the message can't be sent

=> System should exclude the current user from search result 

![Peek 2021-04-28 14-37.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a3dc3638-4fdc-4a7f-8fdd-bedc8d91594b)

**Comment by chamerling** [comment]
IMO being able to send messages to myself is a feature we should keep.
For example, I save stuff in this self conversation (this is possible to do in other messaging system like slack or mattermost)

**Comment by RomaricMourgues** [comment]
Yes it is a feature and works as expected @hantt12 (for once :) )

**Comment by chamerling** [comment]
Anyway, the message should be sent...

**Comment by hantt12** [comment]
Currently the message is not sent as you can see in the video

**Comment by chamerling** [comment]
OK, so message is sent but not displayed. F5 will display it. And this is only for the first message... I will check if it is related to the new message feed.

**Comment by chamerling** [comment]
Just tested and was not able to reproduce on main. Probably a random websocket issue @hantt12
