### ISSUE TITLE
User search on cmd + K is not always working

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1219]
**Describe the bug**
When I try to find Sébastien Garcia on Linagora, I don't find him when I search "Sébastien"

**To Reproduce**
1. Go to Linagora Software
2. Cmd+K
3. Try to find Seb ;)

**Screenshots**

https://user-images.githubusercontent.com/22451567/116418856-cca80680-a83c-11eb-9cff-5c95be988a38.mov

**Comment by chamerling** [comment]
Is it a `é` issue?
