### ISSUE TITLE
[Integration Twake web] Can't Display content twake web

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1221]
## Describe the bug

Can't Display content twake web 

### Precondition: 

- 1.Sign in successfully

- 2.Click twake web icon on header

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

  - Firefox ,version 85.0.2

  - Chrome version 88.0.4

- Mobie Oppo reno version 11.1,chrome app

## image/video

![2021-05-06_09-30.png](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/34be4a19-61b1-4325-9870-996b7c2441ec)

us:https://ci.linagora.com/linagora/lgs/saas/portal/specifications/issues/67

see:https://ci.linagora.com/linagora/lgs/saas/portal/twake-console-web/issues/346 for video

**Comment by RomaricMourgues** [comment]
On two accounts I have I see there is two companies with more that 70 workspaces in it, we currently cannot support so many workspaces.

**Comment by hieuhoang998** [comment]
I create new account and can't open twake web so please check this case

**Comment by RomaricMourgues** [comment]
Did you try on private browser ?

**Comment by BenoitTallandier** [comment]
@hieuhoang998 It is ok now ? Could you try again ? :)

**Comment by hieuhoang998** [comment]
No, It's redirect to sign in page :D
