### ISSUE TITLE
[Mobile/UI/Twake app]  Display content wrong when user click twake app icon

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1223]
pre:iphone-android

1.Access twake console chrome

2.Click twake app icon

3.Check Document, calendar, task, channel: general

Actual result: display content wrong

Expect result: Display content properly

![IMG_0066](/uploads/3cbd704df127e80cb0fd0c16452e6fc2/IMG_0066.PNG)

![IMG_0067](/uploads/10d163f24ebf7f75ce8ac67be99398e3/IMG_0067.PNG)

![IMG_0068](/uploads/83f2bd222349a00b00936967a1e67494/IMG_0068.PNG)

![IMG_0069](/uploads/1b4a98a4a76d5c2e552182c2cf9cff1d/IMG_0069.PNG)

**Comment by BenoitTallandier** [comment]
@hieuhoang998 Do you remember what was the problem ? I can't access to the images.
