### ISSUE TITLE
Company logo from the console is not updating

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1226]
**Describe the bug**
When I update the company logo on the console, I don't see it on Twake

**To Reproduce**
1. Open the console
2. Update the logo
3. Open Twake
4. You don't see the logo

**Comment by RomaricMourgues** [comment]
Knew by the console team, it's on them :)

**Comment by stephanevieira75** [comment]
Looks like it's fixed :)
![Capture d’écran de 2021-11-29 11-47-07](https://user-images.githubusercontent.com/36481167/143854365-a59f1613-a7eb-434d-9790-29d81387ceb2.png)
