### ISSUE TITLE
Notifications page is always empty

### ISSUE THREAD

**Issue by johnathanarroyo** [linagora/Twake#1227]
![image](https://user-images.githubusercontent.com/26065238/116620455-b5c5ea80-a8f6-11eb-830f-bd2426ca9003.png)

**Comment by BenoitTallandier** [comment]
Hi Johnatan ! 
Thank you for your feedback! 🙏 
The content of this page will be implement in the following weeks.
Our US is here :  https://github.com/linagora/Twake/issues/538

I close this issue to not have duplicate :)

**Comment by johnathanarroyo** [comment]
How's the progress?
It's already passed 2 weeks.
