### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1240]
**Describe the bug**
Some translation are missing

- [x] In tasks home page, "View task for other members"  is not translated
![S8](https://user-images.githubusercontent.com/22451567/116979286-18d3ca80-acc5-11eb-84a1-1adf83dc3e60.jpg)

- [x] In tasks home page, "View task for other members" > "search" is not translated
![S7](https://user-images.githubusercontent.com/22451567/116979288-196c6100-acc5-11eb-8061-a7f2dde3c5e8.jpg)

- [x] Upload a file in a message, "From computer" is not translated
![s6](https://user-images.githubusercontent.com/22451567/116979289-196c6100-acc5-11eb-887a-f1815bccd031.jpg)

- [x] Collaborator page, "name" is not translated
![s5](https://user-images.githubusercontent.com/22451567/116979290-1a04f780-acc5-11eb-95e5-e4cd16f51247.jpg)

- [x] In the Twake header "Search" is not translated
![s4](https://user-images.githubusercontent.com/22451567/116979291-1a04f780-acc5-11eb-904b-6c901dbb672a.jpg)

- [x] Create a new file in the drive "New link" is not translated
![s2](https://user-images.githubusercontent.com/22451567/116979295-1a9d8e00-acc5-11eb-9ba1-2a4eddd63b3b.jpg)

- [x] When I create a new file, the default name "Untitled" is not translated
![s1](https://user-images.githubusercontent.com/22451567/116979297-1b362480-acc5-11eb-830b-aaf1d15bf22a.jpg)

- [x] On emoji picker, "search" is not translated
![S9](https://user-images.githubusercontent.com/22451567/116979282-183b3400-acc5-11eb-940e-2580f350674e.jpg)

**Comment by tlle14** [comment]
7. Document > New file > Untitled: failed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/26eab055-fe8f-48af-9006-1101edd79f57)

8. Emoji > Search: passed but the font size doesn't fit the search bar
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6f830594-ffab-47f5-a4d1-2ce648adc0ce)

9. New issue: Emoji category should be translated
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/482916dd-2acd-448a-92eb-6c984878afc6)
--------------------
1. View task for other members: passed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a9be4e66-57ad-4650-a7fb-0784d49cbec4)

2. Search users: passed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2850383b-f7e7-4b8a-90bd-c8f91648a4fb)

3. Upload files "From computer": passed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f25a15ec-8b99-4e78-b88e-81be21464874)

4. Collaborator > Name: passed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6e21cae9-7672-4fbb-916c-aee3e5d7db48)

5. Search: passed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/010a16bb-de57-4963-a5cb-f7814efa969b)

6. New link: passed
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a4ce7517-f994-43b3-be69-81eba64dddfb)

**Comment by hantt12** [comment]
7. Document > new file
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/8063cfc9-3bf6-40a6-b04d-64a395e5e95a)

**Comment by hantt12** [comment]
8 & 9: Passed

**Comment by RomaricMourgues** [comment]
7 comes from the Onlyoffice application and cannot be fixed here. It will be antoher issue specific to Onlyoffice
