### ISSUE TITLE
The number of uploading file doesn't have the limit

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1242]
**Describe the bug**
It doesn't have a limit for the number of files uploaded
I can upload more than 10 files in a message.
![image](https://user-images.githubusercontent.com/69950655/116989746-5b64c980-acfc-11eb-995f-c5db60e18871.png)

**Expected behavior**
It should have a limit for the number of files uploading and the file size (I'm not sure what kind of limit should be applied: limit per file or limit in total uploaded files)

**Desktop**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 88.0

**Comment by BenoitTallandier** [comment]
Thank you for this feedback.
Slack & Teams allow to send up to 10 files in a message.
We'll implement that 👍

**Comment by chamerling** [comment]
Let's say 11 files so we are better than everyone :D

**Comment by hantt12** [comment]
System still tries to upload all the files that user selects but attaches only the first 10 files to the message.
Can we stop the upload after 10th file? Or can we limit the number of files selected to 10?
It would take system resource and burden performance to try to upload all the files
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/0d32ef8e-5402-4a5d-85d7-3f6feb3e2154)
