### ISSUE TITLE
Small bug fix

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1254]
- [x] Remove the text "Change company" in a list of companies if there is only one company
![image](https://user-images.githubusercontent.com/22451567/117298818-16fe3880-ae78-11eb-8da7-5029f10df671.png)

- [x] Delete text about adding only 5 users on inviting collaborators feature inside settings
![image](https://user-images.githubusercontent.com/22451567/117299159-7f4d1a00-ae78-11eb-9dfe-82e589d41c0d.png)

- [x] Change text from "Search people" => "Add or search people" 
![image](https://user-images.githubusercontent.com/22451567/117299316-aefc2200-ae78-11eb-9e84-e552860b551b.png)

- [x] When list of channel members shown, change text from "It's you" to "You"
![image](https://user-images.githubusercontent.com/22451567/117299426-d521c200-ae78-11eb-9d4c-d47799f83672.png)

- [x] When user create a channel, the check box "Add all collaborators" is not visible. Need to be made coloured: darker, etc.
![image](https://user-images.githubusercontent.com/22451567/117299527-ef5ba000-ae78-11eb-9e03-3e9ac07ef804.png)

- [x] Fix error while trying to login `Globals.getDevice() is not a function`

- [x] Change in all Twake "Collaborator" "Colleagues" "Members" by "People"

- [x] When a button is loading, the css cursor is "not-allowed", it should be "wait"
- [x] Change the term on document upload : "Importation" ==> "Uploading"
- [x] Remove Giphy icon in the input

**Comment by hantt12** [comment]
Delete text about adding only 5 users on inviting collaborators feature inside settings
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/03c4ecde-963d-4c68-aa9d-e506da47ebee)

**Comment by hantt12** [comment]
Change text from "Search people" => "Add or search people": OK

**Comment by hantt12** [comment]
Remove the text "Change company" in a list of companies if there is only one company: OK

**Comment by hantt12** [comment]
When list of channel members shown, change text from "It's you" to "You": OK

**Comment by hantt12** [comment]
When user create a channel, the check box "Add all collaborators" is not visible. Need to be made coloured: darker, etc.: OK

**Comment by hantt12** [comment]
Change in all Twake "Collaborator" "Colleagues" "Members" by "People": 
It seems that you guys replace those words by "Users" instead of "People"?
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/fb65e4fd-f69a-4add-8774-983f205a3b77)

**Comment by hantt12** [comment]
It is still "Importation"
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/55125fab-04d4-43b5-8057-6bd53eff957c)

**Comment by hantt12** [comment]
Giphy is still there
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/5b0b88d1-98fc-4707-aede-d129d67a2ec3)

**Comment by stephanevieira75** [comment]
> Change in all Twake "Collaborator" "Colleagues" "Members" by "People":
> It seems that you guys replace those words by "Users" instead of "People"?
> ![image.png](https://camo.githubusercontent.com/12cec77baabf44795b2190e096e4418f3f7e064403d312a98416cda8462b6f6e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565653964656637633430623438343437613433363265322f66623635653466642d663639612d346164642d383737342d393833663230356133623737)

Yes, "People" doesn't fit very well everywhere so we replaced by "Users" instead.


For everything else, I made a pull request with the the bug fixes [here](https://github.com/linagora/Twake/pull/1512) :)

**Comment by hantt12** [comment]
Tested on 9th August on https://web.qa.twake.app
Giphy is still there 
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/7bf19ad5-97b4-4ad7-b768-b28098d2e8b5)

**Comment by RomaricMourgues** [comment]
@benoittallandier do we still want to remove giphy ? Why ? Could we put this in another issue to close this one ?

**Comment by BenoitTallandier** [comment]
Yes, I still want to remove Giphy from the input bar. It's done in production but not in QA. 
So we can close this issue.

![image](https://user-images.githubusercontent.com/22451567/128822909-081c1651-a70c-4e64-9bab-898ea2ba662f.png)

**Comment by hantt12** [comment]
May I know why it's done on production but not QA? Did you deploy it directly to production?

**Comment by RomaricMourgues** [comment]
Because it is a server configuration option not a code change. We prefer to keep it in QA to continue testing “having application in the bottom bar of messages”.
