### ISSUE TITLE
Guest Management > The user role changed after the company member is added in Guest Management screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1271]
# Precondition
Story: https://github.com/linagora/Twake/issues/333
The user role is Admin
[image](https://user-images.githubusercontent.com/69950655/117632629-7ecdbf80-b1a7-11eb-801b-0ecd4d28e294.png)

# Actual Result
After being added to the Guest Management screen, the user role change from Admin to Guest
![Peek 2021-05-10 16-16](https://user-images.githubusercontent.com/69950655/117636575-27c9e980-b1ab-11eb-93f3-6c74648d1b9a.gif)

# Expected Result
The user role shouldn't be changed.

# Environment
QA Environment

**Comment by chamerling** [comment]
There are several issues here:

1. If the admin is already in Twake, we should not be able to add it as guest, or at least we should block at the API side
2. The Twake console code allows to update role on existing user from `admin` to `guest` by being authenticated as an application.

**Comment by chamerling** [comment]
From point 1, we may have several admins on the console side and the one added as guest never connected to twake so it is not provisioned on the twake side. This may be hard to resolve, a solution will be to have better API responses (with status codes) and be able to notify user about this (or provision the user in twake at the invitation time so that everything goes well then...)

**Comment by chamerling** [comment]
@tuanlc any plan on making this work on the console side? @RomaricMourgues told me that you plan to do things on this invitation side

**Comment by tuanlc** [comment]
> @tuanlc any plan on making this work on the console side? @RomaricMourgues told me that you plan to do things on this invitation side

We are going to handle it and expect to release a new version with the enhancement at the end of this week. So, basically, you can have the update at the beginning of next week.

**Comment by chamerling** [comment]
Great! Can you also plan to add error codes in your JSON responses? Relying on human readable messages is not so great to handle this on the consumer side.

**Comment by tuanlc** [comment]
Yes, it is a good improvement. I will create a TODO ticket for it.

**Comment by RomaricMourgues** [comment]
@tuanlc can we close this issue on Twake side and ref a Console issue ?
