### ISSUE TITLE
Guest Management > Unable to invite a guest to the private channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1273]
# Precondition
Task: https://github.com/linagora/Twake/issues/333

# Actual Result
When adding a guest in the Guest Management screen to a private channel, the guest is able to join the workspace but cannot see the private channel.

# Expected Result
Please confirm if a guest is able to be invited to a private channel. 
If yes, after invited, the guest should be able to see the channel.

# Environment
QA Environment

**Comment by BenoitTallandier** [comment]
I confirm that a guest is able to be invited to a private channel.

**Comment by BenoitTallandier** [comment]
The feature is working inside the "participants" panel.
The "guest" panel will be removed with the issue  #2100
