### ISSUE TITLE
Guest Management > Missing the subject in the invitation email 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1274]
# Precondition
Task: https://github.com/linagora/Twake/issues/333

# Actual Result
Missing the subject in the invitation email
![image](https://user-images.githubusercontent.com/69950655/117649317-93b34e80-b1b9-11eb-9cd2-b86bcfeec0dc.png)

# Expected Result
The invitation email should contain the inviter/host name.

# Environment
QA Environment

**Comment by chamerling** [comment]
This happens when we are authenticated as an application. My proposal will be:

1. Use the application display name in this case
2. OR, Add the requester in the incoming request so that we can get its profile and its display name

cc @tuanlc

**Comment by tuanlc** [comment]
This is a known/duplicated issue with https://github.com/linagora/Twake/issues/1148#issuecomment-834247896

Check my last comment in the issue. Twake Console ehanced the endpoint by adding `inviter` attribute in the invitation request.

**Comment by chamerling** [comment]
Oh OK, I did not saw this in the source code. I will update it and check it again.

**Comment by chamerling** [comment]
I checked the code, for some reason we call the `/users/invitation` endpoint when our user role is `member`, and we call `POST /users` when our user role is `guest` and so this will not work as expected.

But `/users` does not allow to set the guest role, it will set role to `member` by default.

What is the plan? Can we have a single endpoint which allows to invite user from its email, be it guest or member, or anything else

**Comment by RomaricMourgues** [comment]
@tuanlc this is related to our initial discussion, here is the issue https://ci.linagora.com/linagora/lgs/saas/portal/twake-console-account/issues/71
@chamerling isn't it what you want?

**Comment by chamerling** [comment]
@RomaricMourgues yes this is it, I saw it and I saw that @tuanlc plans to do it soon so this is nice

**Comment by RomaricMourgues** [comment]
"inviter" was implemented.
