### ISSUE TITLE
Guest Management > The reset password link is reuseable

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1275]
# Precondition
Task: https://github.com/linagora/Twake/issues/333
Add a guest in a channel by using Guest Management

# Actual Result
In the invitation email, after resetting the password, the link is still active.
![image](https://user-images.githubusercontent.com/69950655/117653362-7f258500-b1be-11eb-9996-bd48bd269900.png)

# Expected Result
After resetting the password, the link in the invitation mail should be inactivated

# Environment
QA Environment

**Comment by chamerling** [comment]
This is not a Twake issue, this is a Console one cc @tuanlc 

From the console code, the link generated to change the password is signed with the current user password. So if the user updated his password, the link should be invalid. Also, it contains an expiration date, which is used on token verification and which must make the link invalid.

**Comment by chamerling** [comment]
Some other feedback on this: Please do not send password, send a one time link which allows to connect and to change password on first connection @tuanlc

**Comment by tuanlc** [comment]
> This is not a Twake issue, this is a Console one cc @tuanlc
> 
> From the console code, the link generated to change the password is signed with the current user password. So if the user updated his password, the link should be invalid. Also, it contains an expiration date, which is used on token verification and which must make the link invalid.

You are right. That the way we are using at Console side.

**Comment by tuanlc** [comment]
> Some other feedback on this: Please do not send password, send a one time link which allows to connect and to change password on first connection @tuanlc

1. We don't send the password but use the current password to sign the JWT token.
2. This is not change password but recover/reset password feature.
3. Can you give me some suggestions to implement `one time link`?

**Comment by chamerling** [comment]
1. I see it in the email screenshot above
2. Yes I know
3. Generate a token and store it somewhere on your side, push this token in the link you send. Once the user opens the link, validate the token, remove it from the store. You can also add some TTL (on Mongo collection for example) to clear the store automatically if the user did not open the link within the time window.

This should be the way to go for the password recovering feature but also for the first login when a user is invited to join Twake for example: The workflow can be to open Twake Console from it and ask the user to change his password immediately.

**Comment by tuanlc** [comment]
> 1. I see it in the email screenshot above

This is the case when a new user (does not exist in the system) is invited. The password is used to login.

BTW, this is the business and was decided by BA. We are going to implement the new flow for inviting non-existing users. [ticket](https://ci.linagora.com/linagora/lgs/saas/portal/specifications/issues/208)

**Comment by RomaricMourgues** [comment]
@tuanlc can we close this issue on Twake side and ref a Console issue ?

**Comment by hantt12** [comment]
I'll close this one because it's Console task. 
For now, nothing changed yet
