### ISSUE TITLE
Notification page is empty still.

### ISSUE THREAD

**Issue by gsong101** [linagora/Twake#1277]
![image](https://user-images.githubusercontent.com/26065238/117684774-2926f200-b16a-11eb-8c3a-e187810e801c.png)

**Comment by RomaricMourgues** [comment]
Hi, unfortunately our team member working on this issue is not available for some week, so the solving was delayed for now.
Sorry for the inconvenance.

**Comment by johnathanarroyo** [comment]
Thank you for letting me know.
I am grateful if you could keep me up to dated.
Thanks

**Comment by BenoitTallandier** [comment]
We don't have this page anymore
