### ISSUE TITLE
Guest Management > It always displays the hyphen after a guest name

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1280]
# Precondition
Story: https://github.com/linagora/Twake/issues/333
A guest is added to the channel by Guest Management modal

# Actual Result
When creating a private discussion with the guest, there is a hyphen displaying after the guest name. 
It also appears in the invitation email

![image](https://user-images.githubusercontent.com/69950655/117757397-429f6b00-b24a-11eb-9a3d-d22a70b46f24.png)

# Expected Result
The hyphen shouldn't display

# Environment
QA environment

**Comment by chamerling** [comment]
That was a user creation issue where lastname was set to "-". This has been fixed in https://github.com/linagora/Twake/pull/1366/commits/82b1bd768f55000e55a87f7d764dafdf65ab5919
