### ISSUE TITLE
[Story] Remove a workspace integration

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1319]
## User story summary
[Definition](#Definition)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Related](#related)  

## Definition
```gherkin
Given I am a workspace admin
When I look to remove a workspace integration
Then I go on "workspace settings" > "Integrations"
And I click on the trash button
And a confirmation popup appears to validate the choice
```

## Criteria
- [ ] As an admin, when I delete an integration, the integration should appears in the "All integration" section
- [ ] As an admin, when I delete a channel integration on this page, the integration is removed from all channels where it was installed
 
## UI UX Design
![removeInt.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/ef0e0a00-942c-4892-9c53-4871c39f27d2)
## Related
#1311

**Comment by hantt12** [comment]
Tested on 21st Dec.
There is no Confirmation dialog. Please check again @RomaricMourgues

**Comment by RomaricMourgues** [comment]
@BenoitTallandier do we still want a confirmation dialog, just to confirm as some time we want to reduce confirmation dialogs for some actions

**Comment by BenoitTallandier** [comment]
Yes, specially for integration with token like n8n, zapier, ... If we remove one of this component by mistake, it can take time  to undo that.
But let's release the solution like that. We'll add it in an other version.

**Comment by RomaricMourgues** [comment]
Fixed here: https://github.com/linagora/Twake/pull/1838

**Comment by tlle14** [comment]
Thanks, retest pass! 
![Peek 2022-01-04 17-09.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9f490f29-2fbb-452f-b204-963b0da0f19d)
