### ISSUE TITLE
OIDC in frontend

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1332]
**For QA**
- Check that we can still logout
- Check that we can still login
- Check that we can still create an account
- Check that we are still logged in even if we reload after 24h

**Comment by hantt12** [comment]
User can still login/logout/create account. 

For the last point " we are still logged in even if we reload after 24h" I will need to wait and update later

**Comment by hantt12** [comment]
After 24 hours, I am automatically logs out. I don't have to reload the page

**Comment by RomaricMourgues** [comment]
I didnt understand at first but your right, if the tab is kept open it logs out automatically after 24 hours... If the tabs is closed, after 24h  we are still logged in. I will invetigate.
