### ISSUE TITLE
Cannot logout on the QA environment

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1337]
# Actual Result
I cannot logout of the QA environment
![Peek 2021-06-03 22-16](https://user-images.githubusercontent.com/69950655/120680752-e506e300-c4c4-11eb-84fd-695c9c95cd4b.gif)

# Expected Result
Please fix the issue. 
User should be able to logout

# Environment
QA environment

**Comment by BenoitTallandier** [comment]
@tlle14  Could you try again ? I think it's working now :)
