### ISSUE TITLE
The page is logout/ refreshed/ relogin unintendedly

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1342]
# Actual Result
1. Every morning, when I access beta.twake.app, it displays the login page, even I didn't logout before.
2. When I'm typing a message, the page is refreshed and re-login unintendedly (That time the internet connection is quite slow and unstable)

# Expected Result
Please investigate and fix this issue. 

# Environment
Production
beta.twake.app

**Comment by chamerling** [comment]
This is something we are working on it right now. It may also be fixed on the QA platform.

**Comment by tlle14** [comment]
This issue does not happen anymore
