### ISSUE TITLE
[Story] Banner if there are a payment warning

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1360]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a company
And I'm currently in a workspace of this company
When there is an warning in the payment in this company
And I open Twake chat
Then I should see a banner saying that the administrator of the company has to pay
```

## Criteria
- [x] As a user, I can not close this banner.
- [x] As a user, if there are no payment issue (I am in free plan or I already paid), I can't see this banner.
 
## Related
#1339

**Comment by RomaricMourgues** [comment]
@BenoitTallandier it will be a banner, is it ok for you ?

**Comment by stephanevieira75** [comment]
> @BenoitTallandier it will be a banner, is it ok for you ?

![Capture d’écran de 2021-06-17 17-28-01](https://user-images.githubusercontent.com/36481167/122557534-34105480-d03d-11eb-8e20-9ea38a1490a5.png)

**Comment by BenoitTallandier** [comment]
The problem with a banner is that a user will be able to use the app even if there is this banner. 
Let me check with the console. A banner could be enough if at the end, company that didn't pay are downgraded to the free plan. :)

**Comment by RomaricMourgues** [comment]
So it is not a warning ? I though it was a warning and after some weeks we block the access. I suppose the warnings comes by email then ?

**Comment by BenoitTallandier** [comment]
My idea with this US was to block the access :p 
You're right, there are reminders by mail during month. And we can add warning banner like that. 
I'll update the US.
**We build this banner as a warning** and I'll create an other US for blocked companies.

**Comment by stephanevieira75** [comment]
> The problem with a banner is that a user will be able to use the app even if there is this banner.
> Let me check with the console. A banner could be enough if at the end, company that didn't pay are downgraded to the free plan. :)

I genuinely think that we shouldn't block companies with a popup and agree with this solution ! 👍🏻

**Comment by RomaricMourgues** [comment]
Ok @BenoitTallandier let's go for two user stories :p
