### ISSUE TITLE
Join call button is not shown

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1371]
when user A create a Jitsi call in a channel, user A see message: 
"User A invite you to the call...." 

Other people in the channel see the same message button there is no "Join call" button as we used to have => People are not able to join call

![2021-06-23_16-03-31.jpg](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/f7706484-f62d-4036-8a3f-821cc596f118)
![2021-06-23_16-02-42.jpg](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/bb520edc-e55b-4f72-b6a0-4b3d62ffdbf8)

**Comment by RomaricMourgues** [comment]
Related to #1375
