### ISSUE TITLE
Channel name is shown again in the bottom of the channel when we scroll

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1372]
https://images.zenhubusercontent.com/271994210/3700c098-d7a0-4252-8e9c-629d4a2d943a/aa22a5bb_7f0d_4aeb_8a58_a8722efd52e9.mp4

**Comment by RomaricMourgues** [comment]
Do you have a way to reproduce it ? I can't find why it happened

**Comment by RomaricMourgues** [comment]
Fixed on QA

**Comment by hantt12** [comment]
@RomaricMourgues  you can try these steps
![Peek 2021-06-25 14-06.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/243fd67e-d6d1-43b0-a1ae-a8f081c66450)

**Comment by RomaricMourgues** [comment]
This time it is directly related to #1373 after a reload the duplicata disapear.
But I need to fix the "empty" channel bug
