### ISSUE TITLE
Original message disappears if user replies by adding a Jitsi call

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1375]
https://images.zenhubusercontent.com/271994210/51305c9c-1055-4eab-9605-3e10896d8f20/b7f063c5_2590_4f77_9613_6e7931413bfd.mp4

**Comment by RomaricMourgues** [comment]
Fixed on QA

**Comment by hantt12** [comment]
message no longer disappears however we found another issue at https://github.com/linagora/Twake/issues/1384
