### ISSUE TITLE
Not redirect to twake console when user click Account setting in twake web

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1383]
## Describe the bug

Not redirect to twake console when user click Account setting in twake web

### Precondition: 

- 1.Sign in twake web successfully

- 2.Click Name -> account setting

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

chrome

## image

![2021-06-25_08-58_1.png](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/7db6b94a-9eee-4a77-82a1-6f3f4a64eba6)

![2021-06-25_08-58.png](https://images.zenhubusercontent.com/601377d6b51eaea2fe48ca85/b9ced032-864c-439b-b848-83570ee04c7f)

**Comment by RomaricMourgues** [comment]
Thanks it is a configuration issue, I fix it soon
