### ISSUE TITLE
Update Electron application icon (to respect new color)

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1403]
![logo-squarrish](https://user-images.githubusercontent.com/14353924/130741788-fca23ad0-4f25-4300-81c8-c1599c1b1b8c.jpg)

**Comment by hantt12** [comment]
Hi @RomaricMourgues could you please update the description to this backlog so that our QA can know the expected icon?

**Comment by RomaricMourgues** [comment]
Done
