### ISSUE TITLE
As a user I want to quote a message

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#1409]
#### US
https://www.notion.so/linagora/Replies-on-Web-for-direct-chat-4c1617d650d9412893875085ca9db564

#### Work to do:

- [ ] Add a "Reply" option in the "..." of any message only in direct channels
- [ ] Create the reply hook and recoil atom that will display the quoted original message at the top of the message editor. A: This should be relative to the channel (if I change channel then it should disappear and when I o back then it should be there again). B: It should be cancellable with the X icon.
- [ ] When press "send" (or press "enter") the original quoted message should be put in the new field "quote_message" in the message object
- [ ] Create the "message with a quoted original message" view. Make sure it work when the original message is deleted.
- [ ] Remove all ability to answer to a thread in direct channels (the reply button at the bottom of a thread, but also the ability to view a thread in the side view from the "..." or on the top right of any message)

**Comment by tprudentova** [comment]
Hi @rezk2ll ! 
When you send a reply to a message, the replied message stays “chosen” in the message editor even though you haven’t used the Reply button again![Screenshot 2022-08-25 at 10.35.30.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/0999ebd4-8658-4734-aff3-f634b80f92e7)
Maybe it's meant to be like that? However, it caught my eye

**Comment by rezk2ll** [comment]
yes @tprudentova  it's intended to keep replying to the same message.
