### ISSUE TITLE
Rich input > underline button is not working

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1420]
**Describe the bug**
When I try to underline a text, it is not underlined but I get that `++underlined++`

**To Reproduce**
1. Open the QA env
2. Send a message with underlined text
3. See the message sent

**Screenshots**

https://user-images.githubusercontent.com/22451567/124452308-9039df00-dd86-11eb-986f-c19ad6d51fc7.mov

**Comment by tlle14** [comment]
Retest pass! Thank @chamerling 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/1c2276c8-9812-414d-b34e-5c8b15d918a2)
