### ISSUE TITLE
Wordings and grammar issues in Lock account notification popup

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1427]
There are some wordings that need updating in this screen:

1. functionality => functionalities
2. please, verify your account => please verify your account (remove comma)
3. In addition, in my opinion, we should not use the word "blocked" and "unblock". We can consider using "locked" and "unlock"
"Block" has negative meaning it makes users have a feeling that they did something wrong (when they didn't). "Lock" is a more friendly wording

![2021-06-19_12_09_19-](https://user-images.githubusercontent.com/14353924/124833632-c5108680-df7e-11eb-9b1d-dee853a475c2.png)

**Comment by RomaricMourgues** [comment]
Original issue from @hantt12 , I agree to all this points

**Comment by Intelrunner** [comment]
Please assign to me. I need a good first issue, and I'm a native speaker/writer.

**Comment by RomaricMourgues** [comment]
> Please assign to me. I need a good first issue and I'm a native speaker/writer.

Done, please pull the **feature/2021.Q3.dev** branch and base your PR on this same branch.

Thanks a lot for your time 🙏

**Comment by RomaricMourgues** [comment]
@intelrunner any news on this PR ? If not I will affect it to an other developer :)

**Comment by Intelrunner** [comment]
Oh no! Please pass it on. I became far too busy. I apologize for not
getting back sooner.

**Comment by RomaricMourgues** [comment]
Don't worry, totally understand :)
