### ISSUE TITLE
Message length don't have a limit

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1440]

**Comment by RomaricMourgues** [comment]
@BenoitTallandier what is the limit? :)

**Comment by BenoitTallandier** [comment]
What others do : 
Slack : 12 000
Mattermost : 16 383
Rocketchat : 5 000
Teams : 16 237

What we can do : **12 000** seams an average number.

**Comment by RomaricMourgues** [comment]
@stephanevieira75 you can work on this one later

**Comment by hantt12** [comment]
I can still able to send message/reply with more than 12000 characters. Please check

**Comment by RomaricMourgues** [comment]
Thanks @hantt12 we look into this
