### ISSUE TITLE
Mention shows @username instead of [@Complete Fullname] block

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1454]

**Comment by chamerling** [comment]
@RomaricMourgues are you talking about the editor block? This is actually the same behavior as in production. Do you want to change it to have the fullname displayed in the editor when user selects one from the dropdown?

**Comment by RomaricMourgues** [comment]
Yes, because username are depreciated (not in console, not anywhere in Twake except this input).
We want the same display as in Messenger for instance (@Full name with spaces)

**Comment by chamerling** [comment]
OK let's do it!

**Comment by chamerling** [comment]
From what I see we need to change several things:

- If `@username` is not supported anymore, we should remove it from the dropdown item display ie currently it displays like `Christophe Hamerling - @chamerling`
- The way we serialize ie `Hello @Christophe Hamerling` should be serialized as something like `Hello @someid`
- On the message rendering side, support the other way
- The current markdown serialization does not allow this, I found a lib which seems to work, it needs more test

**Comment by RomaricMourgues** [comment]
We do not **show** usernames, it doesn't mean we can't use it for technical purposes.
I agree for points 1 (remove from drop down UI), point 3 (UI of block in text input).
And for markdown I'm not sure of the user workflow that would go to this issue, a copy paste from somewhere else ? If we tries to write @something then the auto-complete will do the replacement for him. If he doesn't know the username he has no reason to try using it in markdown mode no ?

**Comment by chamerling** [comment]
OK I found some ways to do what we want. Do we put the use avatar in the text editor (not a big fan of this). It will be good if we do not have the `@`, but `@` is used to trigger the dropdown suggestion

<img width="350" alt="Capture d’écran 2021-07-21 à 15 49 57" src="https://user-images.githubusercontent.com/264403/126500043-41e505a3-e284-46c1-b875-b50019a08e7a.png">

**Comment by RomaricMourgues** [comment]
We can remove the avatar or the @ but not keep both for sure.
I am OK to keep only the @. (Messenger like)

**Comment by RomaricMourgues** [comment]
I'm adding something, I just noticed "tab" and "right arrow" are not working to select the mentioned user when in the drop down.

**Comment by chamerling** [comment]
> I'm adding something, I just noticed "tab" and "right arrow" are not working to select the mentioned user when in the drop down.

Let's do it in another issue
