### ISSUE TITLE
[Story] Free company : only 1 workspace

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1455]
## Definition
```gherkin
Given I am a free user
When I look to create a new workspace
And I click on the button "+"
Then a popup appears saying that I am in a free company and I can not create an other workspace
```

## Criteria
- [x] As a free company, I can not create 2 workspaces in the same company
- [x] As a paid company, I can create more than 1 workspace in the same company

## UX 
Title : "You can not create more workspace"
Subtitle : "In the free version, you can have only 1 workspace in your company."
Text : "Whoops!! Seems like you want to create a new workspace in your company. You might want to consider upgrading your plan if you want to collaborate in several workspaces. Explore our pricing options and select the best option for your team collaboration needs.

**Comment by hantt12** [comment]
In my opinion, the content needs revising @hkotthapalli @RomaricMourgues 
Title: "workspace" => "workspaces", "can not" => "cannot"
Subtitle/text: is subtile necessary because the content is duplicated to the text below. The "whoops" below does not really match.  If you really like "whoops", it should be placed in the title instead

**Comment by hkotthapalli** [comment]
Title: "You can not create more workspaces"
Subtitle: "In the free version, you can have just one workspace in your company."
Text: "Whoops!! Do you want to create a new workspace in your company? You might want to consider upgrading your plan. Explore our pricing options and select the best choice for your team collaboration needs.

**Comment by RomaricMourgues** [comment]
I will implement the changes here: https://github.com/linagora/Twake/pull/1671
