### ISSUE TITLE
[Story] Onlyoffice is not available for free company

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1457]
## Definition
```gherkin
Given I am in a free company
When I open the preview of an office file
And I click on "edit with onlyoffice"
Then a popup appears saying that I have to upgrade if I want to edit my file online
```

## Criteria
- [x] As a user in a free company, I can not edit a file with onlyoffice
- [x] As a user in a paid company, I can edit a file with onlyoffice

## UX
Title : "You can not edit this file"
Subtitle : "In the free version, you can not use onlyoffice."
Text : "Whoops!! Seems like you want to edit the file from Twake. You might want to consider upgrading your plan if you want to collaborate around office files. Explore our pricing options and select the best option for your team collaboration needs.

**Comment by hantt12** [comment]
I am not able to test this backlog in both QA/Production platform because the preview is not working even though I enable Only Office for the workspace
![image](https://user-images.githubusercontent.com/53081477/135563546-506eca2c-877d-4f9b-a64e-793e3aadb9ac.png)

**Comment by hantt12** [comment]
There are 2 cases to test on Production: 
Case 1 for Free Company => Unable to edit file with Only Office => Passed
Case 2 for Paid Company => not able to test this yet because event Linagora is a free company. 
Is there anyway we can test cases related to Paid Company in Production?

**Comment by RomaricMourgues** [comment]
I am currently doing the changes to ensure QA and prod has onlyoffice by default.
By the way hen installing an application we still need to reload the page to have the changes.
