### ISSUE TITLE
Rich text editor improvements

### ISSUE THREAD

**Issue by stephanevieira75** [linagora/Twake#1462]
## Long inline text breaks the UI
![Capture d’écran de 2021-07-16 13-59-38.png](https://images.zenhubusercontent.com/5f4e3d2d91dca0478164f0b5/068b6993-512f-4a30-87dc-0c9b725c17fc)

## Allow vertical scrolling
![Capture d’écran de 2021-07-16 14-01-40.png](https://images.zenhubusercontent.com/5f4e3d2d91dca0478164f0b5/bbff12c8-0ec5-4d62-994f-875d1d47f584)

**Comment by tlle14** [comment]
Scroll works. Retest pass!
Thank @chamerling 
![Peek 2021-07-30 16-26.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/b7487579-7f6c-4f14-8dae-58c89d4e01fe)
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3403fa93-1237-4dc1-938d-60cdbc739afa)
