### ISSUE TITLE
Code block (and other blocks) take the full text instead of the selecting part / creating a new block

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1468]
https://images.zenhubusercontent.com/271994210/3a73abc7-47f4-44af-84e2-ff2ebe35c5e6/kapture_2021_07_20_at_11_32_29.mp4

**Comment by tlle14** [comment]
Thank @chamerling 
Retest pass!
![Peek 2021-07-30 16-20.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4b781b05-5df8-482b-ae95-848ac387ea55)
