### ISSUE TITLE
Cannot get selfhosted working - github master

### ISSUE THREAD

**Issue by working-name** [linagora/Twake#1469]
Hello there,

Tried creating an account at community.twake.app but the activation email never reaches me since sendgrid's IPs are on spamcop blacklist - hence my post here.

I've been trying to get twake up and running to play with it for a long time now, I clearly cannot do it by myself.

Attached the logs from all containers. Using latest git master branch, and I'm manually running the commands in your start.sh because the timeout is ridiculously long and it also allows me to keep an eye on what's going on in the container.
[docker-logs.zip](https://github.com/linagora/Twake/files/6852761/docker-logs.zip)

I've repeatedly erased the whole repo folder (which includes docker-data), did `docker rm -v` - no change. I always get a login prompt vs a signup form, and I have no clue what login/password it expects me to feed it :grin:

Any ideas of what I might try to get this going?

**Comment by RomaricMourgues** [comment]
Hi @working-name ,

If you get the login and signup pages it means you probably already successfully installed Twake! When you get there, you just need to signup, no mail verification will be needed, you will be redirected right away to the app.

From your point there is three possibilities:
- Twake is not installed well and you will not be able to finish the signup process (you can see the logs in the browser debugger, network tab)
- Twake is well installed but you changed the default configuration and it requires email verification or something else
- Everything works fine and we need to details the signup procedure in our installation guide :)

**Comment by working-name** [comment]
That's the thing - I don't get the signup page, only the login page :disappointed: 

- nothing in the browser logs, and the request for login or password reset gets an unknown user response back, which is normal since I have no idea what that username might be
    - I have removed docker-data and the whole repo folder numerous times as I said, no idea where it gets its account
- configuration is so vanilla `supersecret` stuff is still in place, didn't touch it
- there's no signup procedure, I tried manually navigating to `/signup` or `/register`, no go, it goes back to login.

**Comment by RomaricMourgues** [comment]
Could you share a screenshot of the current login page ?

**Comment by RomaricMourgues** [comment]
I found out the issue, let me apply a patch right now

**Comment by working-name** [comment]
![loginpage](https://user-images.githubusercontent.com/16505052/126492845-18c45cff-9c59-44c8-8fbc-978662420097.png)
![try-reset](https://user-images.githubusercontent.com/16505052/126492848-438bc8dc-506e-461a-94da-28be4bfca423.png)

**Comment by RomaricMourgues** [comment]
Thanks for spotting this, it affected only new on-premise deployments. I just published the patch and it should work if you try again a re-install. Or just do `docker-compose pull; docker-compose up -d nginx node php;`.
Please wait 30 minutes to 1h for the auto deployment to ends.

**Comment by working-name** [comment]
Thank you! That got me up and running to test it out.
