### ISSUE TITLE
Workspace and company counters

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1474]
Currently number of users in a workspace or in a company is not up to date. We need to get it right.

- [x] Add a counter table (special Cassandra table type)
- [x] Increment / decrement the counter on user added / removed
- [x] Randomly (ex. 1 time our of 10 for instance) or when we list the users, decide to do a re-count (asynchronously preferably) and add the delta value to the counter to set it to the right value.

**Comment by romanesko** [comment]
Did like you asked, but I'm not sure that recount users by random 1/10 is a good solution. Guess we need to make a strong periodical tasks that checks the db and fix all it can find. But that for the future.
