### ISSUE TITLE
Suggestion selection in text editor

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#1478]
When suggestion is displayed, user should be able to select one with TAB or RIGHT ARROW

**Comment by chamerling** [comment]
@RomaricMourgues I just checked on Slack: We can not select user suggestion from TAB. Only right arrow, enter, click are allowed

**Comment by RomaricMourgues** [comment]
I can use tab on Slack and Messenger I just tried (chrome version)

**Comment by RomaricMourgues** [comment]
But i cannot with right arrow (it closes the suggestion list for the right arrow, and this is useful if I just want a @ without mention anyone).

**Comment by chamerling** [comment]
My bad, I reversed the things...

We can select user using `TAB`, but not using ➡. ➡️ will hide suggestion list as soon as it finds a not empty character (probably a bug on Slack when there are empty lines after the current position)
So, I will do this:

1. Select current suggestion on `TAB`
2. Hide suggestion and move cursor correctly on ➡️
