### ISSUE TITLE
Scroll bar appears when hovering over the left side bar

### ISSUE THREAD

**Issue by stephanevieira75** [linagora/Twake#1493]
![Capture d’écran de 2021-07-27 17-26-49.png](https://images.zenhubusercontent.com/5f4e3d2d91dca0478164f0b5/cc9e1545-108c-4775-9bb3-f398d5929f42)

**Comment by hantt12** [comment]
It's still there?
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/b8d4d337-661e-4b55-8506-ae400742fcf1)

**Comment by RomaricMourgues** [comment]
It seems it's not

**Comment by hantt12** [comment]
Oops sorry the screenshot can't show it. I upload the video instead
![2021-12-21_11-54-06](https://user-images.githubusercontent.com/53081477/146918500-2ab0782e-48a3-4422-b5e0-f860d71e8647.gif)

**Comment by hantt12** [comment]
I upload the video instead 
![2021-12-21_17-53-29](https://user-images.githubusercontent.com/53081477/146918706-3945392a-0de9-4d00-8a4a-c4125e6c751a.gif)

**Comment by RomaricMourgues** [comment]
Yep, not resolved, thanks it goes back to todo
