### ISSUE TITLE
When user removes a reply to discussion, the message is shown as blank

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1507]
We should either completely remove the message or show message like "deleted message"
Otherwise it's very confusing to user to see a message without any content

https://images.zenhubusercontent.com/271994210/c4c81fc2-1158-4e26-99a9-a58d6ec232bc/53bf472e_064b_4be7_8718_ff40c788c027.mp4

**Comment by RomaricMourgues** [comment]
This is related to https://github.com/linagora/Twake/issues/1423 , there is a bug but it should behave like you said.
