### ISSUE TITLE
Unable to upload file to reply

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1508]
File browser is not shown to select file
![CF2FDD91-EE0E-4B5E-9095-BE96BF19FD24](https://user-images.githubusercontent.com/53081477/127638832-0f76a167-1b2e-4dec-aa8b-2dfd3fe5028f.GIF)

**Comment by RomaricMourgues** [comment]
I think the video is not the right one @hantt12

**Comment by hantt12** [comment]
sorry. I reuploaded the right one
