### ISSUE TITLE
[Workspace Setting] There is no a successful notification message when changing the workspace name or uploading the logo successfully

### ISSUE THREAD

**Issue by vttuann** [linagora/Twake#1519]
**Describe the bug**

Currently, If the user changes the workspace name or uploads the logo successfully, but there is not a message to notify the user that they have successfully updated.

**To Reproduce**
1. Go to 'Workspace Setting'
2. Changing the name of workspace or upload a logo successfully 
3. Verify issue

**Expected behavior**

After changing the workspace name or uploading the logo successfully, nothing happens when I click on the Update button. This means that the user does not know if they have successfully updated or not. For me, we should give a success message in this case.

**Screenshots**

![Peek 2021-08-03 10-15](https://user-images.githubusercontent.com/69950706/127952781-32734c1e-ed1e-4926-8acd-490aad24076a.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.06 LTS
- Browser [Chrome, Firefox]
- Version [90, 88]

**Enviroment**
Tested on QA Environment

**Comment by RomaricMourgues** [comment]
Technical notes:
- You should use the existing toaster library to display notification `import { ToasterService } from 'app/features/global/services/toaster-service';`
- Make sure this is not already fixed
