### ISSUE TITLE
Review / refactor the login and JWT renew algo

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1523]
User complain they are disconnected on a regular basis from Twake.
We need to do a review of our current code.

- [ ] Check our current system that check the JWT before doing any request (to try auth again the user just before the request)
- [ ] Check how we update the JWT when OIDC token is renewed from library
- [ ] Ensure we use the new node endpoints for JWT renewal

**Comment by hantt12** [comment]
Hi @RomaricMourgues is this the reason for https://github.com/linagora/Twake/issues/1696

**Comment by hantt12** [comment]
ok as it's not fixed yet, I'll move this backlog to In Progress
