### ISSUE TITLE
[Channel - Users] Duplicate invited user in the user screen of channel. 

### ISSUE THREAD

**Issue by vttuann** [linagora/Twake#1535]
**Describe the bug**

UserA creates a channel, then he invites userB to that channel. User B sees the invited channel in his workspace. When userA opens the user screen in the channel, he sees the  duplicated user. 

**To Reproduce**
1. User A creates a chanel 
2. User A invites User B to channel.
3. User B got channel that User A invited 
4. User A click on the Users buton 
5. Verify issue 

**Expected behavior**

NOT duplicate invited user. The user screen must consist of the creator and the inviter.

**Screenshots**

https://user-images.githubusercontent.com/69950706/128323885-48e8e811-377e-4231-935b-c34cb68346a5.mp4

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.2 LTS
- Browser [Chrome, Firefox]
- Version [90, 88]

**Environment**
Tested on QA env

**Comment by RomaricMourgues** [comment]
@TuanQA92 thanks! Could you upload videos next time instead of gif ? It is difficult to rewind and forward :)

**Comment by TuanQA92** [comment]
Hi @RomaricMourgues 
Yes, I do  as you said. btw, I uploaded again for this issue.

**Comment by BenoitTallandier** [comment]
It is working now. I close the issue.

https://user-images.githubusercontent.com/22451567/149940910-4c1fb204-546b-41f8-8c2e-88109cc2f751.mov
