### ISSUE TITLE
The not-yet-login user doesn't appear in the workspace member list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1539]
# Precondition
- User is created on Console 
- User has not logged in yet

# Actual Result
On the default workspace member list, the new user doesn't appear.
If the user is added to the workspace, the console log screen said he has already been in there.
![image_2021_08_05T08_27_03_569Z](https://user-images.githubusercontent.com/69950655/128327843-1d2c2268-d5ff-4185-839c-b5d7b006d3b8.png)

# Expected Result
Even the user has not logged in yet, he should display in the member list of the workspace

# Environment
QA environment
Chrome Ubuntu

**Comment by RomaricMourgues** [comment]
Note: we need to refresh after 2 seconds this list because it is async behind (waiting for refactor of this pge with node backend)
