### ISSUE TITLE
Integration > Twake Web doesn't display the correct user's name in the channel list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1540]
# Precondition
After created, the user changed his name from the default (username) on Console

# Actual Result
On the channel member list, it displays the default name instead of the new name

**Channel member list**
![screenshot_78](https://user-images.githubusercontent.com/69950655/128332385-3e897bf0-9670-4800-b1af-622f7c3d1a26.png)

**Console**
![screenshot_79](https://user-images.githubusercontent.com/69950655/128332548-662c02e1-f2f1-4101-a26a-98996c26b729.png)

# Expected Result
The member list should display the updated name

# Environment

- QA environment
- Chrome on Ubuntu

**Comment by RomaricMourgues** [comment]
When someone work on this: check that it is still the case after clearing browser cache

**Comment by BenoitTallandier** [comment]
It's fixed

https://images.zenhubusercontent.com/271994210/ef8430f1-a2ca-4709-9c41-80d931df6216/changename.mov
