### ISSUE TITLE
Company Owner cannot add members to the workspace he didn't create 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1546]
# Precondition
The workspace is created by a Company Admin
Console setting:
![screenshot_87](https://user-images.githubusercontent.com/69950655/128499186-eec68fe3-15a4-4b62-8848-31039f8479ce.png)

# Actual Result
The adding member button doesn't appear for the Company Owner to add more users
![screenshot_86](https://user-images.githubusercontent.com/69950655/128499166-acbfa07d-31b2-4d2e-ab39-fbaf3d3fddb5.png)

# Expected Result
Please confirm if the Company owner has permission to add member to any workspace in his company?

# Environment
- QA environment
- Chrome on Ubuntu

**Comment by BenoitTallandier** [comment]
Yes, company owner and company admin should be workspace administrator in any workspace. 
That means that they should be able to invite users 👍

**Comment by BenoitTallandier** [comment]
The bug is still here

https://images.zenhubusercontent.com/271994210/851f97a1-2eab-419a-b364-b8789716e803/addadmin.mov

**Comment by tlle14** [comment]
Thanks,
Retest pass!
![Peek 2022-02-07 18-01.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6830ce25-16a8-4d23-8243-4982068bf3e4)
