### ISSUE TITLE
[Edit Channel] Admin is unable to update the channel privacy 

### ISSUE THREAD

**Issue by vttuann** [linagora/Twake#1554]
**Describe the bug**

Owner creates a channel and invite Admin to his channel.  Admin got the channel and he click on the Edit channel. However, he is unable to update the channel privacy. 

**To Reproduce**
1. Owner creates a channel and invite Admin to channel.
2. Admin clicks on Edit channel
3. Verify issue

**Expected behavior**
It should show the privacy selection when Admin edits a channel

**Screenshots**
https://images.zenhubusercontent.com/271994210/faa057d6-603f-4ce2-b2c5-52fb27706f36/screencast_2021_08_10_10_13_31.mp4

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.2 LTS
- Browser [Chrome, Firefox]
- Version [90, 88]

**Additional context**

**Comment by BenoitTallandier** [comment]
It's fixed, I close the issue.
https://images.zenhubusercontent.com/271994210/afa0b7ac-103c-4ad3-98a2-525ece1ccde8/createchannel.mov
