### ISSUE TITLE
Twake allows duplicate workspaces

### ISSUE THREAD

**Issue by LSC-LINAGORA** [linagora/Twake#156]
**Describe the bug**
Twake allows creating a workspace with the name of an already-existing workspace.

**To Reproduce**
Home -> Create a workspace -> Name it test#1 -> Add users
then
Home -> Create a workspace -> Name it test#1 -> Add users
There are two test#1 workspaces

**Expected behavior**
I expected Twake app to tell me that there already was a workspace with that name. Or to append a number to the workspace name.

**Solution**
In backend, add a digit at the end of the workspace name and increment this digit until we have a unique name across the company

**Comment by RomaricMourgues** [comment]
Need to wait complete migration of workspaces APIs to node

**Comment by hantt12** [comment]
i am still able to create duplicate workspace name
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a1bc75ea-e5ae-4111-ac78-996c84f428bf)

**Comment by RomaricMourgues** [comment]
@stephanevieira75 this is because we do not use the node endpoint and still use the php endpoint. Could you plan to fix this (should be very quick to change)
