### ISSUE TITLE
Localstorage is polluted by old OIDC related data

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#1562]
Looks like old OIDC data is kept in localstorage, check the screenshot below (comes from prod):

<img width="2560" alt="Capture d’écran 2021-08-13 à 14 54 22" src="https://user-images.githubusercontent.com/264403/129360229-4742ff97-cb50-4b46-a263-bb11f46a2072.png">

**Comment by RomaricMourgues** [comment]
Same issue on Console, I notified them already some weeks ago. It seems it comes from our OIDC library x LemonLDAP.
We could remove it manually.
I did not open an issue on the OIDC lib GitHub repo yet.

**Comment by chamerling** [comment]
I used it in other projects and never saw such noise, will check soon since I am refactoring the login/auth parts.

**Comment by stephanevieira75** [comment]
Looks like it's fixed.
@RomaricMourgues could you check if it's the case for you ?
