### ISSUE TITLE
Fix tracker for messages

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1571]

**Comment by BenoitTallandier** [comment]
We also have an issue with the event "open_client", coming from the node servers. It is probably related ;)

**Comment by RomaricMourgues** [comment]
Could it be related to this #1296 what do you think ?

**Comment by BenoitTallandier** [comment]
Hum, can be possible. Let me test :p

**Comment by RomaricMourgues** [comment]
For the message duplicate event I just found and fixed it now
