### ISSUE TITLE
Implement account deletion

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1572]
Hook event name is `user_deleted` and `company_deleted`

We should also remove it from segment if user was tracked:
https://reference.segmentapis.com/?version=latest#57a69434-76cc-43cc-a547-98c319182247

**How to test**

1. Go to console and into "My profile"
2. Push the "Delete my account button"
3. You should not be able to login anymore
4. Any other in the company will see you as 'Deleted Account' in Twake. (For now you need to check this in private window or clear cache)

**Comment by hantt12** [comment]
Hi @RomaricMourgues could you please give me more details for the requirement of this backlog?

**Comment by hantt12** [comment]
I don't see "Delete my account" button in my profile
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/563de4fe-a423-4464-bc67-6aa185fe994c)

**Comment by RomaricMourgues** [comment]
Ah, it is not yet deployed by the Console it seems. You can try on https://twake.dev.lin-saas.dev/ or wait before implementing this

**Comment by hantt12** [comment]
ok let me know when it's deployed to QA. Thanks
