### ISSUE TITLE
Search applications show both English and French versions

### ISSUE THREAD

**Issue by digitalfredy** [linagora/Twake#158]
**Describe the bug**
When looking applications I noticed Twake show me some options twice (English and French mixedup)

**To Reproduce**
1. Go to 'any channel or conversation'
2. Click on '+ in message box (left side)'
3. Note: when documents is not active
4. See the error in the screenshot (Documents in both languages)

**Screenshots**
![twake-english-french-repeated](https://user-images.githubusercontent.com/1372919/91082863-4be29c00-e617-11ea-9e96-0a6287ea2e43.png)

**Expected behavior**
Show items just for the main language

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser: Firefox 
 - Version 68.11.0esr (64-bit)

**Additional context**
Mi browser have both English and French languages for content but English is the default.

**Comment by RomaricMourgues** [comment]
Outdated, we are currently also changing the application endpoints.
