### ISSUE TITLE
QA Aditionnal checks prior to Q3.700 update

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1599]
1. Check auto-add to workspace when coming from console (when invited to a workspace, check we are in the invited workspace after signup workflows ends)
2. Check default channels creation (when you create a workspace, it should contain a "General" channel)
3. Check default channels join (when you join a workspace you should be member of the General channel automatically)
4. Check how deleted users are shown (when a user deletes its account, other users must see him as "deleted account", also check after cache reset)

**Comment by hantt12** [comment]
1&2&3 is ok
4: waiting for Delete account feature is deployed to QA
