### ISSUE TITLE
No company after signup

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1612]
**Describe the bug**
When I signup, my company is not created.

**To Reproduce**
1. Signup from the console
2. See the Twake message saying you need to be invited somewhere

**Screenshots**

https://user-images.githubusercontent.com/22451567/132651642-1105b07b-de1a-4196-a52d-8f8bfabf3679.mov

**Desktop (please complete the following information):**
 - On the QA environment

**Comment by RomaricMourgues** [comment]
:,( I though I just fixed it yesterday

**Comment by BenoitTallandier** [comment]
![](https://media0.giphy.com/media/OPU6wzx8JrHna/giphy.gif)

**Comment by RomaricMourgues** [comment]
Should be fixed on QA
