### ISSUE TITLE
Invite with error 500

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1613]
**Describe the bug**
When I try to invite someone as a guest, it is not working. I got an error 500.
When I try to invite someone as an internal user, it is not working. I got an error 500.

**To Reproduce**
1. Open twake qa
2. Open the guest management popup in a channel
3. Try to add someone
4. See error in the console

1. Open twake qa
2. Click on "+ invite user"
3. Try to add someone
4. See error in the console

**Screenshots**
https://images.zenhubusercontent.com/271994210/4c2e1af7-e842-4b86-a0fb-0cf2d30e3a53/guest.mov

https://images.zenhubusercontent.com/271994210/73a12d7c-f36f-4b1e-a869-cb8d41da2879/invite.mov

**Desktop (please complete the following information):**
 - Version : QA

**Comment by RomaricMourgues** [comment]
Fixed on QA
