### ISSUE TITLE
[Story] Upload view of file in the chat

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1619]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am user
When I want to upload a file in a message
Then I drag&drop a file from my computer to the message input or I select file from the input
And I can see the file in the message with the loader
And I can see a little popup at the right with the recap of which file I'm uploading 
```

```gherkin
Given I am user
When I want to send a message with a file 
And I don't want to wait that the file is totally uploaded
Then I send the message
And I can see the file in the message with the loader
And other user can see the message with "files are being uploaded..." label
```

## Criteria
- [ ] If I upload a file, the popup should be shown even if I go in an other channel / workspace / entreprise
- [ ] If I hover the loader, a cross replace the loader and I can cancel the uploading process of the file.
- [ ] I can upload up to 10 files in one single message.
- [ ] If I send a message with a file that is not totally uploaded, I can see the loader attached to the file
- [ ] If I send a message with a file that is not totally uploaded, other user can see a tag "files are being uploaded..." in the message
- [ ] If I send a message with a file that is not totally uploaded, I can stop the upload, then the tag "files are being uploaded..." is removed
- [ ] In the popup uploading popup title, I can see the number of document that are currently uploading in the popup / number of document that were uploaded

## Translation 
"files are being uploaded..." :
- FR: fichiers en cours de téléchargement
- RU: 
- VN:
 
## UI UX Design
![fileupload.drawio.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/89532d62-1824-46e8-995b-354a6c79cb0f)

## Related
Mobile : https://github.com/linagora/Twake-Mobile/issues/920
Competition : https://www.notion.so/twake/File-upload-4c1b8ad3f3864df1ad917abce3d07151

**Comment by RomaricMourgues** [comment]
@BenoitTallandier where is the UI frames ? :)
