### ISSUE TITLE
Cannot edit any files with Fantastic Only Office

### ISSUE THREAD

**Issue by christophechevalier** [linagora/Twake#1624]
**Describe the bug**
When I open a file from "Document", I am unable to edit.
Test format: **.odt**  
Regarding the **.md** format, I have the display, but without the editing as well.

**Expected**
Have the button "Edit with OnlyOffice" and the iframe from OnlyOffice Servers.

**To Reproduce**
1. Go to "Document" part
2. Click on **.odt** file

**Screenshots**
![image](https://user-images.githubusercontent.com/7148846/133410963-e3e82409-313a-4cc4-93b2-c820dc7e97a7.png)

**Desktop:**
 - Browser: chrome
 - Version: 93.0.4577.63 (Official Build) (64-bit)

**Comment by RomaricMourgues** [comment]
@hantt12 currently in QA

**Comment by hantt12** [comment]
Only Office is not installed for QA Platform => Unable to test this issue
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/f5620452-02fa-4b20-96e2-8d0e3bbfd3bb)

**Comment by RomaricMourgues** [comment]
Oh yes that’s right.

We can consider this issue as fixed because the button “Edit with only office” was not visible (now it is visible so it was fixed).

Romaric
