### ISSUE TITLE
Cannot see "Document, Calendar, Tasks" part

### ISSUE THREAD

**Issue by christophechevalier** [linagora/Twake#1625]
**Describe the bug**
After clicking on the other channel, the "Document, Calendar, Tasks" disappears.  

**To Reproduce**
1. Go to the random channel  
2. See the "Document, Calendar, Tasks" part visible  
3. Click on the other channel  
4. See the "Document , Calendar, Tasks" part not visible

**Screenshots**
![image](https://user-images.githubusercontent.com/7148846/133408684-80e14299-9b6a-4a47-984f-04417bffbb48.png)  

**Desktop:**
 - Browser: chrome
 - Version: 93.0.4577.63 (Official Build) (64-bit)

**Comment by RomaricMourgues** [comment]
Related to #1605
