### ISSUE TITLE
Error when open "search applications"

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1627]
**Describe the bug**
When I open the application menu, I have an error.

**To Reproduce**
1. click on "Search application"
2. See error

**Screenshots**
https://images.zenhubusercontent.com/271994210/11dcbc44-a491-47b6-a35e-19fb65d72562/searchapplication.mov

**Comment by RomaricMourgues** [comment]
@hantt12 currently in QA

**Comment by hantt12** [comment]
This is quite random to me. 
I have just tried this 3 times and got the same issue once
