### ISSUE TITLE
No application in tab creation popup

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1628]
**Describe the bug**
We can't create a tab.

**To Reproduce**
1. Open a channel
2. Create a tab
3. Click on the 'application' menu

**Screenshots**
https://images.zenhubusercontent.com/271994210/f993ba79-9c08-44c8-ba62-671510618692/tabapp.mov

**Comment by RomaricMourgues** [comment]
@hantt12 currently in QA

**Comment by hantt12** [comment]
Isn't it because the application is not enabled for the workspace?
