### ISSUE TITLE
User company role (member, admin, guest) not updated when changed from the console

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1636]
**Describe the bug**
When I update a user from the console (from `guest` to `internal`), the user is not updated on Twake chat

**To Reproduce**
1. Go to the console
2. Open the "user page"
3. Update the status of a user
4. Login as this user
5. See that the status is not changed

**Comment by RomaricMourgues** [comment]
It is an issue on php side, PR is open 👍
