### ISSUE TITLE
Duplicated company

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1665]
**Describe the bug**
For some company, the route `ajax/users/current/get` send me company twice whereas the console has only one company registred

**Screenshots**
https://user-images.githubusercontent.com/22451567/134939201-61b31cfc-b4d9-41d3-beda-d3f7f78d6d16.mov

**Comment by RomaricMourgues** [comment]
Not possible anymore, tested on new account on QA and previous accounts on canary
