### ISSUE TITLE
As a company admin, I can't remove an application from a workspace

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1666]
**Describe the bug**
As a company admin, I can't remove an application from a workspace

**To Reproduce**
1. As a company admin, go to application page
2. Try to remove an application from the company
3. See error

**Screenshots**

https://user-images.githubusercontent.com/22451567/135037011-027d65f1-3ae1-4007-8e85-b5528e582ec7.mov

**Comment by hantt12** [comment]
Workspace settings is not available for company admin
![admin.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/e4995226-9d37-46f5-8fab-e8162aa16079)

![settings.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/10130cb8-f4ab-4abc-b953-d1aa64ea24da)

**Comment by BenoitTallandier** [comment]
It's true, so we should first fix this issue : 
A company admin **is always** a workspace moderator.

**Comment by BenoitTallandier** [comment]
I tested it, user are shown as `company administrator`


![Capture d’écran 2022-02-08 à 16 00 19](https://user-images.githubusercontent.com/22451567/153013543-9ec5b8d0-5a91-436f-810a-a2ef9789e21a.png)


![Capture d’écran 2022-02-08 à 16 00 36](https://user-images.githubusercontent.com/22451567/153013663-097c9f13-1dd2-4a8d-9f6c-202009314be6.png)

**Comment by RomaricMourgues** [comment]
Ok, then I know where to fix it thanks
