### ISSUE TITLE
Default channel is not created after registration

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1678]
**Describe the bug**
After registration, a default channel called "General" should be automatically created for user

**To Reproduce**
1. Go to https://web.qa.twake.app/
2. Click on Register
3. Register a new account

**Expected behavior**
default channel is automatically created

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/873a6e41-7a49-4cd6-87b5-b180e969cb69)

**Comment by hantt12** [comment]
This does not happen on beta.twake.app

**Comment by BenoitTallandier** [comment]
It is fixed. I close this issue
https://images.zenhubusercontent.com/271994210/2e9f5941-0153-4e6c-bdf9-3b0a4c7a2462/createaccountqa.mov
