### ISSUE TITLE
Unable to create workspace/add guest after payment

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1679]
**Describe the bug**
User still sees message to ask for payment for plan in order to create workspace

**To Reproduce**
1. Go to web.qa.twake.ap
2. Register a new account
3. Login new account above in console.qa.twake.app
4. Pay for Standard plan
5. Go to Twake web and try to create new workspace OR add guest to channel

**Expected behavior**
After paying for Standard Plan, user should be able to create workspace

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/70c9071d-e4b6-4406-9ac4-4a4c97c26746)
![image](https://user-images.githubusercontent.com/53081477/135964889-73cd59e7-8e9a-4f08-9f19-8c375a95142f.png)

![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/c20143b5-6d59-4ce0-9b9b-d6c44146edd5)

**Comment by RomaricMourgues** [comment]
Event after reloading the page ?
