### ISSUE TITLE
Cannot use the message functionnality after fresh installation - Ubuntu 18.04

### ISSUE THREAD

**Issue by Valzul** [linagora/Twake#1686]
1. Using the documentation here : [Installation - Twake](https://doc.twake.app/gettingstarted/installation) I installed Twake on Ubuntu 18.04 ( Already installed it a while ago ).
2. Got everything working, I believe ( no warning upon starting ).
3. Created a first channel, and tried to send a message, the message does not appear on the channel after sending it.

Here is the stack trace from **twakeapp_dev_error.log** when I try to send the message :

`
PHP message: PhpAmqpLib\Exception\AMQPConnectionClosedException: ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.(0, 0) in /twake-core/vendor/php-amqplib/php-amqplib/Php$

Stack trace:

#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))

#1 /twake-core/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(216): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))

#2 /twake-core/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '\x01\x93oACCESS_REFUS...', NULL)

#3 /twake-core/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(258): PhpAmqpLib\Channel\AbstractChannel->wait(Array, false, 3)

#4 /twake-core/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(217): PhpAmqpLib\Connection\Abstract" while reading response header from upstream, client: 192.168.0.78, server: localhost, request: "POST /ajax/discussion/save HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "srvubu:8000", referrer: "http://srvubu:8000/client/sxuvE7eNzLFnefLsWVKVb5/c/32r1GT4dEbF1wPgBdS1E8N"

`

Could it be that some module is not installed properly ?

**Comment by RomaricMourgues** [comment]
It seems more a trouble with node. Try to run a `docker logs -f --tail 100 node` to see what it is. And don't hesitate to do a second `docker-compose up -d` maybe node just stopped.

**Comment by Valzul** [comment]
Reissued **docker-compose up -d**, no error there, everything is up to date, this is the log concerning **scylladb** : 

1)

root@srvubu:/Twake/twake# sudo docker-compose up -d
twake_rabbitmq_1 is up-to-date
twake_scylladb_1 is up-to-date
twake_php_1 is up-to-date
twake_node_1 is up-to-date
twake_nginx_1 is up-to-date

2)

root@srvubu:/Twake/twake# docker-compose logs -f --tail 100 scylladb
Attaching to twake_scylladb_1
scylladb_1  | INFO  2021-10-11 11:47:45,711 [shard 0] init - starting messaging service
scylladb_1  | INFO  2021-10-11 11:47:45,711 [shard 0] repair - Setting max_repair_memory=107374182, max_repair_memory_per_range=33554432, max_repair_ranges_in_parallel=3
scylladb_1  | INFO  2021-10-11 11:47:45,711 [shard 0] init - starting storage service
scylladb_1  | INFO  2021-10-11 11:47:45,712 [shard 0] storage_service - Loading persisted ring state
scylladb_1  | INFO  2021-10-11 11:47:45,712 [shard 0] storage_service - loaded_peer_features: peer_features size=0
scylladb_1  | INFO  2021-10-11 11:47:45,712 [shard 0] storage_service - Checking remote features skipped, since this node is a new seed node which knows nothing about the cluster
scylladb_1  | INFO  2021-10-11 11:47:45,714 [shard 0] storage_service - Restarting a node in NORMAL status
scylladb_1  | INFO  2021-10-11 11:47:45,893 [shard 0] compaction - Compacted 2 sstables to []. 10954 bytes to 0 (~0% of original) in 0ms = 0.00MB/s. ~256 total partitions merged to 0.
scylladb_1  | INFO  2021-10-11 11:47:46,013 [shard 0] database - Schema version changed to 57f5e195-b1b8-363a-86a9-d961f380c461
scylladb_1  | INFO  2021-10-11 11:47:46,014 [shard 0] storage_service - Starting up server gossip
scylladb_1  | INFO  2021-10-11 11:47:46,697 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-7-big-Data.db:level=0, /var/lib/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-8-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:46,698 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-63-big-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-64-big-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-62-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:46,698 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-293-big-Data.db:level=0, /var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-292-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:46,698 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-146-big-Data.db:level=0, /var/lib/scylla/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-145-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:46,726 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-309-big-Data.db:level=0, /var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-308-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:46,910 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-26-big-Data.db:level=0, ]. 11613 bytes to 5993 (~51% of original) in 1080ms = 0.01MB/s. ~256 total partitions merged to 8.
scylladb_1  | INFO  2021-10-11 11:47:46,910 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-305-big-Data.db:level=0, ]. 11179 bytes to 5868 (~52% of original) in 1078ms = 0.01MB/s. ~256 total partitions merged to 6.
scylladb_1  | INFO  2021-10-11 11:47:46,910 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-143-big-Data.db:level=0, ]. 25076 bytes to 18366 (~73% of original) in 1079ms = 0.02MB/s. ~256 total partitions merged to 3.
scylladb_1  | INFO  2021-10-11 11:47:46,910 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-295-big-Data.db:level=0, ]. 13612 bytes to 8308 (~61% of original) in 1079ms = 0.01MB/s. ~256 total partitions merged to 3.
scylladb_1  | INFO  2021-10-11 11:47:46,910 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/aggregates-924c55872e3a345bb10c12f37c1ba895/mc-9-big-Data.db:level=0, ]. 11166 bytes to 5739 (~51% of original) in 1080ms = 0.01MB/s. ~256 total partitions merged to 2.
scylladb_1  | INFO  2021-10-11 11:47:46,951 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-306-big-Data.db:level=0, ]. 32975 bytes to 23103 (~70% of original) in 1109ms = 0.02MB/s. ~256 total partitions merged to 6.
scylladb_1  | INFO  2021-10-11 11:47:47,056 [shard 0] messaging_service - Starting Messaging Service on port 7000
scylladb_1  | INFO  2021-10-11 11:47:47,530 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-16-big-Data.db:level=0, /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-15-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:47,530 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-285-big-Data.db:level=0, /var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-284-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:47,530 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/mc-7-big-Data.db:level=0, /var/lib/scylla/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/mc-8-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:47,628 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-294-big-Data.db:level=0, ]. 11027 bytes to 5676 (~51% of original) in 740ms = 0.01MB/s. ~256 total partitions merged to 2.
scylladb_1  | INFO  2021-10-11 11:47:47,628 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-147-big-Data.db:level=0, ]. 18104 bytes to 12761 (~70% of original) in 740ms = 0.02MB/s. ~256 total partitions merged to 3.
scylladb_1  | INFO  2021-10-11 11:47:47,707 [shard 0] compaction - Compacted 3 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-66-big-Data.db:level=0, ]. 24431 bytes to 12439 (~50% of original) in 832ms = 0.01MB/s. ~384 total partitions merged to 1.
scylladb_1  | INFO  2021-10-11 11:47:47,707 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-310-big-Data.db:level=0, ]. 61040 bytes to 49251 (~80% of original) in 803ms = 0.06MB/s. ~256 total partitions merged to 6.
scylladb_1  | INFO  2021-10-11 11:47:47,708 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-9-big-Data.db:level=0, ]. 10950 bytes to 5631 (~51% of original) in 833ms = 0.01MB/s. ~256 total partitions merged to 2.
scylladb_1  | INFO  2021-10-11 11:47:48,274 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-65-big-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-66-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:48,274 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/functions-96489b7980be3e14a70166a0b9159450/mc-7-big-Data.db:level=0, /var/lib/scylla/data/system_schema/functions-96489b7980be3e14a70166a0b9159450/mc-8-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:48,332 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-286-big-Data.db:level=0, ]. 19797 bytes to 13311 (~67% of original) in 744ms = 0.02MB/s. ~256 total partitions merged to 6.
scylladb_1  | INFO  2021-10-11 11:47:48,332 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-17-big-Data.db:level=0, ]. 107473 bytes to 102376 (~95% of original) in 744ms = 0.13MB/s. ~1408 total partitions merged to 1288.
scylladb_1  | INFO  2021-10-11 11:47:48,332 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/mc-9-big-Data.db:level=0, ]. 10828 bytes to 5570 (~51% of original) in 744ms = 0.01MB/s. ~256 total partitions merged to 2.
scylladb_1  | INFO  2021-10-11 11:47:48,679 [shard 0] compaction - Compacting [/var/lib/scylla/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/mc-298-big-Data.db:level=0, /var/lib/scylla/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/mc-297-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:48,726 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-67-big-Data.db:level=0, ]. 19044 bytes to 12276 (~64% of original) in 404ms = 0.03MB/s. ~256 total partitions merged to 1.
scylladb_1  | INFO  2021-10-11 11:47:48,739 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/functions-96489b7980be3e14a70166a0b9159450/mc-9-big-Data.db:level=0, ]. 11360 bytes to 5836 (~51% of original) in 416ms = 0.01MB/s. ~256 total partitions merged to 2.
scylladb_1  | INFO  2021-10-11 11:47:49,034 [shard 0] compaction - Compacting [/var/lib/scylla/data/twake/websockets_route-5c2ad930277d11ec9c8d000000000000/mc-8-big-Data.db:level=0, /var/lib/scylla/data/twake/websockets_route-5c2ad930277d11ec9c8d000000000000/mc-7-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:49,117 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/mc-299-big-Data.db:level=0, ]. 12469 bytes to 7333 (~58% of original) in 355ms = 0.02MB/s. ~256 total partitions merged to 3.
scylladb_1  | INFO  2021-10-11 11:47:49,357 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/twake/websockets_route-5c2ad930277d11ec9c8d000000000000/mc-9-big-Data.db:level=0, ]. 21447 bytes to 16073 (~74% of original) in 236ms = 0.06MB/s. ~256 total partitions merged to 15.
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] gossip - No gossip backlog; proceeding
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature COMPUTED_COLUMNS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature CORRECT_COUNTER_ORDER is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature CORRECT_NON_COMPOUND_RANGE_TOMBSTONES is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature CORRECT_STATIC_COMPACT_IN_MC is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature COUNTERS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature DIGEST_INSENSITIVE_TO_EXPIRY is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,057 [shard 0] features - Feature DIGEST_MULTIPARTITION_READ is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature HINTED_HANDOFF_SEPARATE_CONNECTION is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature INDEXES is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature LARGE_PARTITIONS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature LWT is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature MATERIALIZED_VIEWS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature MC_SSTABLE_FORMAT is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature NONFROZEN_UDTS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature PER_TABLE_PARTITIONERS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature RANGE_TOMBSTONES is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature ROLES is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature ROW_LEVEL_REPAIR is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature SCHEMA_TABLES_V3 is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature STREAM_WITH_RPC_STREAM is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature TRUNCATION_TABLE is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] system_keyspace - Got cluster agreement on truncation table feature. Removing legacy records.
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature UNBOUNDED_RANGE_TOMBSTONES is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature VIEW_VIRTUAL_COLUMNS is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature WRITE_FAILURE_REPLY is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] features - Feature XXHASH is enabled
scylladb_1  | INFO  2021-10-11 11:47:59,058 [shard 0] init - starting system distributed keyspace
scylladb_1  | INFO  2021-10-11 11:47:59,060 [shard 0] system_keyspace - Legacy records deleted.
scylladb_1  | INFO  2021-10-11 11:47:59,063 [shard 0] storage_service - Using saved tokens {9179370184217959991, 9059161670935965074, 9018663435223161997, 8737973183885753, 862366712485601610, 8578650921853700909, 8337440378839773986, 8245614949546720487, 8053605911822010659, 7919421304528500661, 7907949565415429556, 7892253656403514048, 7877237515037557931, 784559745240517235, 7783861227489761039, 7565232038290605554, 7542903215496620551, 7395910561163053926, 7348896345215364463, 7342804904345048453, 7301334518799626841, 7300323509946294465, 7235974797043456951, 7189944177105800513, 706071530721678158, 6949495565105147955, 691532557513894088, 6897658692357350713, 6747204013888276156, 6741879065322196683, 6697979699996747748, 7154792785873712503, 6666178969969159643, 6598846794816797047, 6557438328151936784, 6719947242346989590, 6481408902866913123, 6255981133110708299, 77856589538203101, 6114629127089849383, 6095303194981987753, -8014548543685480324, 1595172506413178843, -2440340027356770774, -7690865745459557087, -2435908627959229583, 4945284283663215319, -7643328628184031683, -8658538720400087450, -7874761148512265813, 4238489938649148639, -7044118854625772596, -807074721963501193, -700009096139711922, -8517683890799137988, -7755757331444460248, 1608686658044716841, 5736832968195785464, -6909031560549296801, -928774433790137904, 1890381018453405399, -1463619418257168319, -9070051486818497895, -3736459671645914925, 5606414187631885208, -5965629298572497051, -7105354548724272797, -2989621280822403728, -5795295070968762470, 5413143375278428935, 8815507107048838016, -5538405472526491989, 6182490506483877475, -553591102189899444, -5029092447366827194, -4448844913829661050, -7776546110795983166, -2456944807952956719, 796123603533037034, 6495024588319868961, -5505781292040152428, -6722207280413594153, -4983627186988462960, 1845569783633053639, -4803299022708473254, -5659556169419784279, -729283684876760366, 2030687494551149964, 8616693449995821819, -1495987627426995739, -9034672318803345181, -5987013715092199020, 3179759016717526953, -2394327446422919536, 2110711139681478082, -3365692305357461945, 1542824307364987330, -225531425307935780, 2246987841916435128, 2506585419102602592, 3489414805843678126, -7047355713338766672, -7898357359501164597, -8165783799914245839, -3264740656273742466, -1552778508840108505, -8083511032461846860, 5094172867361832448, -2049374998396520362, -1746967564469795301, -3001825751385089757, -7275561917033730503, -1591374061298919587, -2038939428252072175, -4808722492152851814, 271817971464863743, 3565876190107354084, -1806175208532858273, -4412132296210642563, 5011473159639339833, -2923914576680523557, -2345455502995737986, -5961420607856951484, -4166998894791481179, 4603011572602238918, -3072188294491888667, 4823335601371543247, 1450143298858905042, -1416463475869565862, 4724659329950433007, -2841450430430237771, 3160428609218721271, -1440790775470216219, -361108617925302618, 7452824213029581055, -6428441169265232678, -3415282340723653512, 6912893676904487054, -7490868834984391549, -16313994002195320, -3463693673221155645, -169222359243992159, -6334133343265883934, -9039791388648479191, -2123152385053857988, 4129221887900638992, -4495264514819387090, -285540602440126890, -4247575295800942844, -4500839378750718050, -3935775611874901004, 2631549980163137781, -3537290141555313027, 7453501517492487243, 2358275043458487966, 126287021904734216, -3023447544014881340, -3037970198366723063, -3085837453034422222, -7900005645556459694, 3155020934640191332, -7375031550284728410, 5053085172839653601, -3105951485596061669, -3140633884204185397, -2741733209704496235, -4899129521019102960, 1100834635425824207, -6593347744093706255, -2449151840196098030, -8191398946946659320, 3743052912504884595, -3679712169741952759, 5254153660270944733, -1338228097316577546, -1535146557302180906, -8111416112914940014, -8245290696305535861, 3787270561019989919, -8751694320063814991, -8269506388160143355, 7056716053629104415, 4464274672373169288, -8345211283176692850, -911666839585370186, -8456394930099401575, -8471142374061177879, 5735656629725077977, -703863934615598061, -3147053463143753419, -8511593691184067006, 4512195356852139087, -8686636770948886278, -8853426153914642529, -6729597456542953191, -8908739563606009077, 5989806788541815025, -8989185757367987640, 4157123820118068048, -8442817893212098378, -9096511318794125290, -956880541760653194, 135441592996380702, 1841685910951026134, -7009352613304962842, 1756936044675966267, 1981221103671040325, -3793430775592044357, 2032696101117485731, 4617881761247424150, 5093396088530426041, 2142886481835604766, -5823416327407473222, 2279036086403734654, 449321174061279744, 6492034350706414664, 2312395860957792988, 2416832170979278666, -6761414868354060200, 2603454278979834535, -7831025261658801503, 2669456700376610971, 908527228283175465, 2716753939704035822, 2749815011977551415, 7475758487068798513, 7376632589182825951, -7173992457839654748, 2826318530200115233, -2244055623322450635, 2858225563647627291, -8659725755570551330, 2903691902071218931, 3630820250265826300, 3324520141052733693, -2658775585030081061, 3619514452807759411, 3672503476728662001, 7548270499886647272, 4468411619393581031, 3698413396115755621, -927754989555042950, 377966185095080996, 8998819586136032645, 4251959201078717578, 1534743928885001386, 4861015972889752978, 4890202389553218954, 7422388505157518729, -4576036327632586296, 5030129075900815951, 563103262172279281, -8920349202313185930, 3360343656976635255, 5633043760190834982, 5703897833938835603}
scylladb_1  | INFO  2021-10-11 11:47:59,123 [shard 0] database - Schema version changed to 1003f045-6b17-3ef5-b09a-c4a2a485ce89
scylladb_1  | INFO  2021-10-11 11:47:59,166 [shard 0] database - Schema version changed to 1003f045-6b17-3ef5-b09a-c4a2a485ce89
scylladb_1  | INFO  2021-10-11 11:47:59,167 [shard 0] database - Schema version changed to 25fd105f-ec10-3dbb-962d-846e011c03a3
scylladb_1  | INFO  2021-10-11 11:47:59,380 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-68-big-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-67-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:47:59,504 [shard 0] storage_service - Node 172.18.0.2 state jump to normal
scylladb_1  | INFO  2021-10-11 11:47:59,504 [shard 0] storage_service - Remove node 172.18.0.2 from pending replacing endpoint
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] storage_service - NORMAL: node is now in normal status
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] cdc - No generation seen during startup.
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] init - starting tracing
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] storage_service - SSTable data integrity checker is disabled.
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] init - starting batchlog manager
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] init - starting load meter
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] init - starting cf cache hit rate calculator
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] init - starting view update backlog broker
scylladb_1  | INFO  2021-10-11 11:47:59,808 [shard 0] init - Waiting for gossip to settle before accepting client requests...
scylladb_1  | INFO  2021-10-11 11:47:59,845 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-70-big-Data.db:level=0, ]. 18355 bytes to 12112 (~65% of original) in 427ms = 0.03MB/s. ~256 total partitions merged to 1.
scylladb_1  | INFO  2021-10-11 11:47:59,845 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-69-big-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-70-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:48:00,110 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-71-big-Data.db:level=0, ]. 18191 bytes to 12110 (~66% of original) in 182ms = 0.06MB/s. ~256 total partitions merged to 1.
scylladb_1  | INFO  2021-10-11 11:48:11,809 [shard 0] gossip - No gossip backlog; proceeding
scylladb_1  | INFO  2021-10-11 11:48:11,809 [shard 0] init - allow replaying hints
scylladb_1  | INFO  2021-10-11 11:48:11,809 [shard 0] init - Launching generate_mv_updates for non system tables
scylladb_1  | INFO  2021-10-11 11:48:11,809 [shard 0] init - starting the view builder
scylladb_1  | INFO  2021-10-11 11:48:12,314 [shard 0] init - starting native transport
scylladb_1  | INFO  2021-10-11 11:48:12,314 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-27-big-Data.db:level=0, /var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-26-big-Data.db:level=0, ]
scylladb_1  | INFO  2021-10-11 11:48:12,315 [shard 0] storage_service - Starting listening for CQL clients on 172.18.0.2:9042 (unencrypted)
scylladb_1  | INFO  2021-10-11 11:48:12,315 [shard 0] storage_service - Thrift server listening on 172.18.0.2:9160 ...
scylladb_1  | INFO  2021-10-11 11:48:12,315 [shard 0] init - serving
scylladb_1  | INFO  2021-10-11 11:48:12,315 [shard 0] init - Scylla version 4.1.0-0.20200618.b443b2574a8 initialization completed.
scylladb_1  | INFO  2021-10-11 11:48:12,494 [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-28-big-Data.db:level=0, ]. 11228 bytes to 5993 (~53% of original) in 142ms = 0.04MB/s. ~256 total partitions merged to 8.

I assume it is good looking, but still the app is not working properly, so here is the content of production.json : 

![image](https://user-images.githubusercontent.com/72873887/136792257-02f6aee5-0694-4bf5-bbf0-bc7b77c4a371.png)
