### ISSUE TITLE
Unable to search the new member to add to the channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1719]
# Precondition
- Actor is the Company Owner
- On Console page, adding a new user to the company
- Adding the new user to the workspace
![image](https://user-images.githubusercontent.com/69950655/138679437-d3c866ac-d3b5-44ea-a2fa-c9f5d2a5b501.png)

# Actual Result
The Owner cannot search the new user to add to the channels 
![Peek 2021-10-25 17-35](https://user-images.githubusercontent.com/69950655/138680831-9589383a-267e-45dc-8161-4ba01ceda372.gif)

# Expected Result
When the newly created user is invited to the workspace, it should be able to appear in the search for adding to a channel (of a corresponding workspace)

# Environment
- Chrome/Firefox on Ubuntu
- QA environment: 
https://web.qa.twake.app/
https://console.qa.twake.app/

**Comment by hantt12** [comment]
The newly added is only available to be added to channel after his first login

**Comment by RomaricMourgues** [comment]
It should work now but I will double check today

**Comment by RomaricMourgues** [comment]
@tlle14 could you confirm that the user was successfully added to the workspace like we see in the first screenshot ?

**Comment by tlle14** [comment]
Hi @RomaricMourgues 
After being created on the Console, the user is added TO THE WORKSPACE successfully.
