### ISSUE TITLE
Can't create new direct discussion mobile app

### ISSUE THREAD

**Issue by alexandreChichmanian** [linagora/Twake#173]
On the mobile app (a s8+ don't know if it is relevant), i can't create a new direct message. There is no + sign compare to the website version next to direct message
![20200825_142751](https://user-images.githubusercontent.com/19286000/91213168-346ee600-e6df-11ea-808c-a1b8994ecfd8.jpg)
.

**Comment by RomaricMourgues** [comment]
Mobile is not a dedicated repository and was started from scratch
