### ISSUE TITLE
Unable to create direct message

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1732]
**Describe the bug**
There is no (+) button to create direct message

![2021-11-03_14-14.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/1d8d162f-78a9-4e76-a492-017b7eec38d0)

**Comment by BenoitTallandier** [comment]
Was it after account signup ?

**Comment by RomaricMourgues** [comment]
I have it on my side too, I'll check

**Comment by RomaricMourgues** [comment]
Fixed in here: #1698

**Comment by hantt12** [comment]
@RomaricMourgues please check 

![2021-12-21_11-54-06.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/9088e8fb-cd1b-4f91-a13f-acb8950e4c40)

**Comment by RomaricMourgues** [comment]
Thanks I saw too yesterday !

**Comment by hantt12** [comment]
Yes this should be fixed before deployment imo

**Comment by tlle14** [comment]
Thanks,
Retest pass!
![Peek 2022-01-04 16-09.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3c583a49-c0b9-400c-9f86-09762e054ccf)
