### ISSUE TITLE
Direct chat > Doesn't display the chat box in the direct chat

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1753]
# Actual Result
It doesn't display the chat textbox in the direct chat 
![image](https://user-images.githubusercontent.com/69950655/141894594-5542676f-b58b-4f4e-a7c3-51236a663eb0.png)

# Expected Result
It should display the chat textbox in the direct chat
![image](https://user-images.githubusercontent.com/69950655/141895559-7850c94b-d2f4-45b3-bdf0-1c856104c990.png)

# Environment
QA Environment
Chrome on Ubuntu

**Comment by tlle14** [comment]
@RomaricMourgues hi, please bring the chat textbox back

**Comment by RomaricMourgues** [comment]
Fixed on QA (but sending message is'nt working as described in #1792
