### ISSUE TITLE
Implement realtime for the current user in frontend

### ISSUE THREAD

**Issue by stephanevieira75** [linagora/Twake#1790]
The goal is to make sure user information (first name, language, timezone, avatar etc) is updated in realtime without needing to reload the page.

For this we will create a `/me/{user-id}` realtime room and each time the user entity is updated (in the user service) we should send the user entity in this room.

When the frontend receive an event from this room, it should refresh the current user completely.

This should work for any of this cases:
- first name / last name / avatar / status update
- companies list of the user update
- language / timezone update
- any preferences of the user is updated

This websocket room will be protected only by the user's jwt that contains the user id (user can only access it's own room of course).

**Comment by RomaricMourgues** [comment]
Not working on canary server (Prod console <-> Canary Twake issues ?)
