### ISSUE TITLE
Implement realtime for the current company in frontend

### ISSUE THREAD

**Issue by stephanevieira75** [linagora/Twake#1791]
The goal is to get update anytime a company name / logo / pricing plan is updated/
The room name will be: `/company/{company-id}`.
The room will be protected by a jwt generated when getting the company details.

**Comment by RomaricMourgues** [comment]
Not working on canary server (Prod console <-> Canary Twake issues ?)

**Comment by RomaricMourgues** [comment]
OK on QA
