### ISSUE TITLE
QA what to test 6/12/2021

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1792]
The tests will be separated in two part:
- 1 part focused on everything **except** the messages sending / listing and opening tabs
- 1 part focused only on the messages part (not yet ready)

First part:
- [ ] Workspace management page (update name, default switch, logo, delete workspace)
- [ ] Applications management page (add or remove application)
- [ ] Sync with the console #1766
- [ ] Changing companies / workspaces / channels (we changed the state management)
- [ ] Workspace changes in realtime on two tabs
- [ ] Check we still get notification badge
- [ ] Messages reaction, deletion and pinned
- [ ] Connection indicator next to user to test (should be green if user is logged in, red if not, ~1 minute precision)

Second part
- [ ] Sending messages
- [ ] Add attachments to messages (from computer, drag and drop or from the button), remove attachment
- [ ] Scroll in feed of messages, open list of replies of a thread
- [ ] Edit message content
- [ ] Messages realtime
- [ ] Send message with attachment still in progress
- [ ] Change my status #1808

Third part (end of week)
- [ ] Create a call
- [ ] Attach "Drive" files (from the Drive and not directly from the computer)
- [ ] Test mentions

**Comment by RomaricMourgues** [comment]
@hantt12 Hello, I started to prepare the list of things to test for the next release on the 22. The release will comes to the canary.twake.app server for one month because there is a lot of changes.
Tell me if you can allocate testers next week or not, knowing that for next week you can only test the first part, the second one isnt ready yet.

**Comment by RomaricMourgues** [comment]
@hantt12  Second part will be available tonight, I added a third part I am still working on for the end of the week.

**Comment by hantt12** [comment]
Thank you Romaric. We'll starting testing part 2 today
