### ISSUE TITLE
Emojis in the channel creation are too small

### ISSUE THREAD

**Issue by shivam9593** [linagora/Twake#1812]
Emojis in the channel creation are too small for someone to see. 

Is it possible to maybe increase the size of them a bit for better user experience. 

![image.png](https://images.zenhubusercontent.com/619e1750e7e4f47b0d4a07ff/d5ea32f7-f164-40e5-b786-67f790528253)

**Comment by RomaricMourgues** [comment]
Done
![Screenshot 2021-12-14 at 13 44 14](https://user-images.githubusercontent.com/14353924/146000657-791ae5a9-071b-46b1-a8b4-07bf953a4aa8.png)
