### ISSUE TITLE
Magic Link/Receive Link > Incorrect flow when the user opens the Magic link on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1818]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
```
Given I am not a Twake user 
And I don't have the application on my mobile installed
 When I look to signup with a magic link
1. Then I open the link
2. And the mobile store opens on the Twake page,
3. And I click on "install"
4. And I click on "open"
5 And I see a page explaining that I can join the workspace
6. And I click on "join"
And I am redirected to the signup form (console)
Then I am redirected to Twake chat in the workspace related to the magic link
```
- The user is not a Twake user, have not installed the Twake App

# Actual Result
The behavior when opening Magic Link is not following the user story:
- When opening the Magic link, it redirects to the page in step 6 on the browser.
- When clicking on the button "Login or create an account first", it opens Sign In page on the browser

https://user-images.githubusercontent.com/69950655/146112146-6d847b17-e526-4514-9ac1-312cad62ea44.mp4

# Expected Result
The behavior should follow the user story:
- When opening the Magic link, if the user has not installed Twake App, it should redirect to App Store
- "The page explaining that I can join the workspace" should be displayed on Mobile App.
- When clicking on the button "Login or create an account first", it should redirect to Welcome Page on Mobile. 

# Environment
Mobile Browser

**Comment by RomaricMourgues** [comment]
Thanks, I think this is caused by the fact you open the link in the skype webview and it doesn't trigger the deep linking. I know how to fix this but I will need to have the application deployed first.
So we'll fix this start of January.

**Comment by tlle14** [comment]
> Thanks, I think this is caused by the fact you open the link in the skype webview and it doesn't trigger the deep linking. I know how to fix this but I will need to have the application deployed first. So we'll fix this start of January.

Hi, I've tried opening the link on the browser, it doesn't open/trigger the popup redirect to App Store.
In fact, I saw that small pop-up but not regularly.
https://user-images.githubusercontent.com/69950655/146333797-8b7c5f65-abf6-4793-8165-89b42cd11e19.mp4

**Comment by RomaricMourgues** [comment]
It is still not working, for unknown reason redirection does not occurs even if os is correclty detected as "ios"

**Comment by hantt12** [comment]
For me this is not a valid bug. 
User should be able to Join on browser. It shouldn't be mandatory for user to install mobile app.
Mobile app installation should only be a suggestion.
Currently system works in that way and it's ok for me
