### ISSUE TITLE
Integration with system (menu, imgs) does not work debian buster kde plasma

### ISSUE THREAD

**Issue by digitalfredy** [linagora/Twake#182]
**Describe the bug**
I launched Twake from the command line and answered yes for his first question about integration with my system but is not working.

**To Reproduce**
1. Go to twake webside and download the AppIImage for linux
2. tar -zxf twake-lin-latest.tar.gz
3. sudo mv twake-lin-latest.AppImage /usr/local/bin/twake
4. sudo chown root: /usr/local/bin/twake
5. Launch `twake` from command line
6. Answer yes to the first question about integration with your system
7. Click in KDE Plasma menu and write "Twake" or "twake" in the search box, is not there.
8. Logout the desktop session and then try again previous step

**Expected behavior**
Take supposed to be in KDE Plasma menu beside all the apps I have in my system

**Desktop (please complete the following information):**
 - OS: Linux (Debian Buster) 64
 - Desktop: KDE Plasma: 5.17.5

**Comment by RomaricMourgues** [comment]
Moved here: https://github.com/linagora/Twake-Desktop/issues/14
