### ISSUE TITLE
Improve Linux binary distribution

### ISSUE THREAD

**Issue by digitalfredy** [linagora/Twake#183]
**Is your feature request related to a problem? Please describe.**
* Actual tgz contains `._twake-lin-latest.AppImage` file, please remove
* If possible distribute binary instead of tgz because binary and tgz are same size in MB (my guess, appimg is compressed but I could be wrong).
* File name `twake.appimage` or just `twake` instead of twake-lin-latest.AppImage

**Describe alternatives you've considered**
If the tgz is to ensure the file will have execution permission then just tar to avoid useless compression

**Comment by RomaricMourgues** [comment]
Moved here: https://github.com/linagora/Twake-Desktop/issues/13
