### ISSUE TITLE
Magic Link/Receive > Cannot join the workspace via Magic Link on Web

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1850]
# Precondition
- Story: https://github.com/linagora/Twake/issues/1711
- The magic link is generated on the Mobile App
[Magic Link](https://web.qa.twake.app?join=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjIjoiYjQ0NjhhZTAtNjM5ZC0xMWVjLWI5ODAtODdlODliNjNjNzY0IiwidyI6IjQxNDQ5OTAwLTYzOWUtMTFlYy1iOTgwLTg3ZTg5YjYzYzc2NCIsInQiOiJ0RGthWm9IWm1kRWFLNXNUQ0hmSVJ1Y3dwUEY4UXRkRS92eWV5MnNPUFVJPSIsImlhdCI6MTY0MDIyOTIwMn0.iGQoCnpr1qHxjfQDGojZ5Bz8Ydj-9wFL1rjQXNVOgKU)
# Actual Result
On Web, when opening the magic link, the user cannot join the new workspace successfully. 

# Expected Result
Please investigate.
The user should be able to join the workspace successfully via Magic Link. 

# Environment
Chrome on Ubuntu

**Comment by tlle14** [comment]
Hi @RomaricMourgues 
Retest failed

Step 1: Copy a magic link on Mobile then paste it to a channel
https://images.zenhubusercontent.com/271994210/2579617c-57c5-41a6-8fb6-af4bd7fa1914/xrecorder_07022022_171926_0___1_.mp4

Step2: The other user opens the link to join the workspace. The user cannot join successfully
![Peek 2022-02-07 17-36.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/8cd2e454-b3f1-4b52-8b01-ed43c73be682)

**Comment by RomaricMourgues** [comment]
@EvGen94 the link format is wrong:
domain.com**?join=aaa-bbb-ccc**
instead of domain.com**/join/aaa-bbb-ccc**

**Comment by RomaricMourgues** [comment]
After discussion with the team we will use the ?join=aaa-bbb-ccc format on web too
