### ISSUE TITLE
File edit button is hidden and under file name

### ISSUE THREAD

**Issue by jcabannes** [linagora/Twake#1853]
**Describe the bug**
After opening a file in Twake a part of the edit button is hidden. When we click on the edit button an empty dialog is opened.

**To Reproduce**
1 - Open a file in Twake
2 - Edit button is hidden and under file name
3 - Click on edit button, an empy dialog is displayed

**Expected behavior**
The edit button should be to the right of the file title.

**Screenshots**
![hidden-edit-button](https://user-images.githubusercontent.com/17238459/147223765-d4b217a6-0093-4e14-a3f2-a24e83d5d058.png)
![empty-dialog](https://user-images.githubusercontent.com/17238459/147223792-4268c860-ce75-4c02-a8bb-dcf7b9ed6561.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Chrome
 - Version: 95.0.4638.54 (64 bits)

**Comment by RomaricMourgues** [comment]
Hi it should be fixed with #1858
