### ISSUE TITLE
Cannot close an open file

### ISSUE THREAD

**Issue by jcabannes** [linagora/Twake#1854]
**Describe the bug**
After opened a file in twake, we cannot close it or go back to Twake.

**To Reproduce**
1. Open a file in Twake
2. The cross button in page header is not present
3. Click on "previous page" button in browser does not redirect to Twake

**Expected behavior**
- A cross button should be present in page header to close file and redirect to Twake.
- "previous page" button in browser should redirect to Twake

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.3 LTS
- Browser: Chrome
- Version: 95.0.4638.54 (64 bits)

**Comment by RomaricMourgues** [comment]
Related to #1853 and so probably fixed :)
