### ISSUE TITLE
Sign-up still takes to beta.twake.app

### ISSUE THREAD

**Issue by shivam9593** [linagora/Twake#1855]
A user who signs up still goes to beta.twake.app instead of web.twake.app. 

Tested on 23/12/2021

**Comment by RomaricMourgues** [comment]
@tuanlc some configuration on console side ?
@shivam9593 or is it from the signup button on landing page ?

**Comment by shivam9593** [comment]
Yes - it is after entering a new email address to create a new account on Twake. Steps followed: 

1. Clicked on Sign-Up button on the landing page. 
2. Entered a new email address to register. 
3. Clicked on Register
4. Link in the address bar is beta.Twake.app to take me to the product.

**Comment by tuanlc** [comment]
@RomaricMourgues you are right, it is from console side. Can you create a ticket for the new value in saas repo on the gitlab and assign it to me.

**Comment by RomaricMourgues** [comment]
Done, it will be the issue 117 on your repo

**Comment by tuanlc** [comment]
The address was updated on the production. You can re-check now.
