### ISSUE TITLE
Generated link is too long and the link does not work properly. 

### ISSUE THREAD

**Issue by shivam9593** [linagora/Twake#1856]
Steps followed: 
1. Invite new users
2. (First Problem) Generate a link to invite users to the workspace - the link is too long. Is there a way to make it shorter? 
3. I copy the link on the address bar -> sign-in/sign-up -> Click on 'Join the team' -> The screen I see is not the product - it shows me a blank screen in Twake and I have to click on the name of the Workspace to see the product. (Screenshot attached) - The user should directly see the workspace with documents and channels inside. 
![Screenshot - 1.png](https://images.zenhubusercontent.com/619e1750e7e4f47b0d4a07ff/0ef0d8c8-381f-482f-8b62-ce33fbce0984)

**Comment by RomaricMourgues** [comment]
Links are shorter: tested and validated ex. https://canary.twake.app/join/900f1hb4g4747g1he9gah80g024Aac120i5-fbef67cag601eg1hE9g70ahg0242ac120l5-VZ54SO0569FXQCydzu3mAux2UEI1Hil2ElMmmjsEPPk-

**Comment by RomaricMourgues** [comment]
Issue: when link isn't valid anymore I have a 'create company' button that does nothing (and I am not logged in so probably should redirect to sign up in this case)

**Comment by hantt12** [comment]
after registering from invitation link, user see this
![2022-02-17_18-09.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/932c17fc-90aa-4236-8e79-5c41381377a2)

**Comment by hantt12** [comment]
Tried in QA platform with private browser. This issue still remains after your fix @RomaricMourgues 
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/788d44a0-4bae-4421-9ec6-6ad8fe11b7a6)

**Comment by RomaricMourgues** [comment]
Could you send me a video of what you are doing exactly ?

**Comment by RomaricMourgues** [comment]
Nevermind I found the issue

**Comment by hantt12** [comment]
Here you are 
![invitation link](https://user-images.githubusercontent.com/53081477/155096928-2258ed1f-bef5-4406-8300-410228ea5d58.gif)
