### ISSUE TITLE
Twake Web doesn't display the attached file correctly on the chat 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1859]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1137
- Uploading an image from Mobile App

# Actual Result
The file displaying on Web is not the uploaded one
- The file size is always 0KB
![image](https://user-images.githubusercontent.com/69950655/147653341-84de615b-d8cd-4d1b-aa76-a760220d109b.png)

- The content is totally different
![image](https://user-images.githubusercontent.com/69950655/147653361-5cfe947e-83a5-4198-8262-cceb1a283a76.png)

# Expected Result
The Web should display the attached image/file correctly (both size and content)

# Environment
QA Environment
Chrome on Ubuntu

**Comment by tlle14** [comment]
CC: @huynguyennovem @EvGen94

**Comment by RomaricMourgues** [comment]
Please check and share your usage of the API it is probably a bad usage from mobile :)

**Comment by huynguyennovem** [comment]
@tlle14 @RomaricMourgues: The cause of this is because the API file has changed from version 1 to version 2. I already updated file API change, just wait to merge.
So, this bug will not occur in the next release. Or you can watch the demo here first:
https://github.com/linagora/Twake-Mobile/pull/1163#issue-1089169245

**Comment by tlle14** [comment]
Thank guys,
I will retest in the next build.

**Comment by tlle14** [comment]
Thanks, 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/308e1b84-89be-4087-a1df-33b4ed5d6c99)
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/1bf904a2-32e9-439b-80fd-37d6a9f77263)
