### ISSUE TITLE
Implement CalDAV Integration

### ISSUE THREAD

**Issue by shivam9593** [linagora/Twake#1885]
**Describe the solution you'd like**

Ability to integrate Twake calendar with other calendar apps. For example Android, iPhone or CalDAV integration. 

Two customers have asked for this feature in the recent past: 

https://app.crisp.chat/website/9ef1628b-1730-4044-b779-72ca48893161/inbox/session_b6995576-e3d1-47af-acef-29afa0bb6a7d/

https://app.crisp.chat/website/9ef1628b-1730-4044-b779-72ca48893161/inbox/session_b35b197f-2c4e-4a33-8ab9-b4b3ab08d960/

**Comment by BenoitTallandier** [comment]
It will be done with the openpaas calendar integration

**Comment by RomaricMourgues** [comment]
I close it because it is not in our scope anymore.
