### ISSUE TITLE
Add a notice to warn users that the company has reached the maximum number of users it can invite

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1901]
In order to fix #1744

To do this, we must leverage the stats.members_count information in the company object + the plan.features.members limit also in the company object.

If the plan.features.members is undefined or <= 0 then it means there is no limitation and banner should not be shown.

In the mockups bellow you can see how it looks from the workspace users management page or if we directly try to open the "invite members" popup.

![Screenshot 2022-01-26 at 15.35.53.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/d0467b96-6232-4179-8b07-abb6dbdec85d)

![Screenshot 2022-01-26 at 15.35.59.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/86add00c-fb44-42b7-8935-f5ba63528526)

**Comment by RomaricMourgues** [comment]
@BenoitTallandier do you validate this ?

**Comment by BenoitTallandier** [comment]
Perfect, 
Just for the link to the console in the popup, I think something like "Upgrade your plan" is more clear for the user :)

**Comment by hantt12** [comment]
As I can see there is no warning message and user is still able to add users after maximum number is reached

![Peek 2022-02-17 15-57.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/490c4ba6-fd5f-425c-a21d-1bc4609bc0b3)

**Comment by hantt12** [comment]
System shows unfriendly message (404 error) if we add users when the company has reached the maximum number of users

![2022-02-22_15-09-09.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/ae85e778-d4ff-4dff-9de0-2f4040938fa0)
