### ISSUE TITLE
Logging into Twake - takes me to the wrong company

### ISSUE THREAD

**Issue by shivam9593** [linagora/Twake#1919]
When I log in to Twake, it re-directs me to a random company. 
Instead of the last company where I was active. 

For example, when I log in to my Linagora account, it always re-directs me to the company "DT" instead of "Linagora", even though I have zero activity on "DT". 

# TODO
As a user, when I reopen Twake, I should be redirected to the workspace and company I was before.

Tech : In user preference, we'll store the `recent_workspaces` preference that will be a list of the 1 last company x workspace we where in (it is a list in case we want to store some kind of small history)

**Comment by RomaricMourgues** [comment]
Solution: use our backend user preference storage endpoint to store this preference ("last company used")

@BenoitTallandier could you put it in some sprint ? @stephanevieira75  probably can do it very quickly

**Comment by BenoitTallandier** [comment]
Ok, I added it to this sprint if it's quick to do :)

**Comment by BenoitTallandier** [comment]
@RomaricMourgues I update the comment. Could you validate the `tech` part ? I created the mobile version that will use this tech description : linagora/Twake-mobile#1257

**Comment by RomaricMourgues** [comment]
Updated
