### ISSUE TITLE
Guest management > Can't invite guest as moderator

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1921]
**Describe the bug**
As moderator, I can't invite guest user in a channel

**To Reproduce**
1. Open a paid company where you are moderator
2. Try to add the user

**Screenshots**

https://user-images.githubusercontent.com/22451567/151805857-2e69a7b6-2426-401a-ba19-90a72a0077b9.mov

**Comment by BenoitTallandier** [comment]
@RomaricMourgues do you think it's fast to fix this bug ? We had this issue with a customer. :)

**Comment by RomaricMourgues** [comment]
I need to see with the console team, they return a 403 to us I need to see why

**Comment by RomaricMourgues** [comment]
Console team working on it: https://gitlab.com/COMPANY_LINAGORA/software/saas/twake-console-account/-/issues/35

**Comment by RomaricMourgues** [comment]
@BenoitTallandier could you test it again on canary and QA when you have time?
