### ISSUE TITLE
Fix Database 2

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1945]
- [x] Install new redis machine
- [x] Ensure that we have the good seeds in scylla.conf following deletion of scylla-1
- [x] Ensure that we use QUORUM for read and write (on code side, issue to be created)
- [x] Create a new blank cluster with:
       - pass num_token to 16 cf https://thelastpickle.com/blog/2021/01/29/impacts-of-changing-the-number-of-vnodes.html --> from default of 256 to 16
- [x] dclocal_read_repair_chance = 0.1 a changer vers dclocal_read_repair_chance = 0 cf https://thelastpickle.com/blog/2021/01/12/get_rid_of_repair_repair_chance.html --> it was the defaults of scylla
- [x] Bloom filter false ratio: 0.01229 -> 0.01 --> it was the defaults of scylla
- [x] Init tables in keyspace Twake
- [x] use sstablesloader

- [x] Create a script that is able to read a complete scylla table reliably to copy it later to another cluster
- [x] Copy data from one to another
- [x] Send a message to all users

**Comment by BenoitTallandier** [comment]
I agree, let's try to fix this cluster 💪
