### ISSUE TITLE
Update workspace name reset the logo

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1950]
**Describe the bug**
When I update the workspace name, it reset the current logo

**To Reproduce**
1. Go on workspace settings
2. Change the name of the workspace
3. Save

**Screenshots**

https://user-images.githubusercontent.com/22451567/153879134-c22afd84-659d-4621-b252-b80d7a0864ac.mov

**Comment by hantt12** [comment]
still fail today 18/04

**Comment by RomaricMourgues** [comment]
Yep, https://github.com/linagora/Twake/pull/2059 was never merged, I put it back to TODO
