### ISSUE TITLE
Photos application on iOS hangs after file sharing

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2014]
Step:
   open Photos
   click "sharing" button on one photo and select Twake
   select company, workspace, channel and clock "ok" as a result you will be in Twake with shared file
   click back in the tom right corner to return to "Photos" app
Result:
   "Photos" don't respond to any gestures

Consider opportunity to automatically return to photos application 
Or jump to channel with shared file if it is a feature to stay in Twake after sharing

**Comment by huynguyennovem** [comment]
Hi @shepilov, 
Can you pls help to record this bug into a video? 
And it will be better if I can know the device information (iOS version, model name)

**Comment by huynguyennovem** [comment]
`Or jump to channel with shared file if it is a feature to stay in Twake after sharing`
FYI, we already implemented this recently. You will see it in the next release

**Comment by shepilov** [comment]
Works now

**Comment by shepilov** [comment]
> Hi @shepilov, Can you pls help to record this bug into a video? And it will be better if I can know the device information (iOS version, model name)

ios 15.3.1
iPhone 11

**Comment by huynguyennovem** [comment]
I tried to simulate  this on iPhone 11 emulator (iOS 15.0), but don't see the bug.

https://user-images.githubusercontent.com/29337364/158581625-aa313b7f-a917-4280-81de-10df8ec4212b.mp4
