### ISSUE TITLE
[Magic link] Not working when click on Magic link in Android 12

### ISSUE THREAD

**Issue by huynguyennovem** [linagora/Twake#2015]
**Describe the bug**
Magic link is not received in Android 12

**To Reproduce**
1. Click on a magic link
2. Browser is opened instead of app

**Expected behavior**
Magic link should be opened on app

**Smartphone (please complete the following information):**
 - Device: Android Pixel 4
 - OS: Android 12
 - Version 1.0.7

**Comment by RomaricMourgues** [comment]
What environment ? QA should shows a selection screen to continue on web or mobile
+ we changed the 304 to 200 for .well-known folder, it'll be online in about 2h for auto deployment on QA

**Comment by huynguyennovem** [comment]
> What environment ? QA should shows a selection screen to continue on web or mobile
> 
> * we changed the 304 to 200 for .well-known folder, it'll be online in about 2h for auto deployment on QA

This bug occurred on all environments. 
`QA should shows a selection screen to continue on web or mobile` -> This case only happen when user hasn't installed Twake app and it will go to store if user selects App option. But this bug is only for case user has already installed app in their device and can not go to app when clicked on magic link

FYI:
- https://developer.android.com/about/versions/12/behavior-changes-12#android-app-links-verification-changes
- https://www.reddit.com/r/androiddev/comments/ni33zr/anyone_else_experience_completely_broken_deep

**Comment by RomaricMourgues** [comment]
Ok, QA and dev are up to date with the 304->200 fix, could you try it?

**Comment by huynguyennovem** [comment]
Thank you, it's 200 now as I see. But this solution doesn't fix the bug. I will find another way for this.

**Comment by huynguyennovem** [comment]
For some reasons, can not edit/assign this issue, so continue to issue:
https://github.com/linagora/Twake-Mobile/issues/1311
