### ISSUE TITLE
Ability to share channel link

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2029]
**For QA**: This is only possible for public channels for now.

--

Can we have the action "Share channel link" for public channel, so I can copy the channel url to share for my college to join?

![Screenshot 2022-03-25 104137](https://user-images.githubusercontent.com/14353924/160087684-de658480-2b9b-4f4a-9550-2a40770d230b.png)

**Comment by hantt12** [comment]
Tested in https://staging-web.twake.app/ 
This is what is happening now:

User A is NOT a member of Channel X (public channel)
User B send channel X's link to user A
User A click the link 
=> Expected: user A goes to channel X
Actual: user A is not able to go to channel X, he is led to General Channel


If user A is already a member of channel X, then channel X is shown correctly

**Comment by RomaricMourgues** [comment]
For now it is the expected behaviour, we just have the "get channel link" button, the ability to display that we don't have access to the channel, or provide a preview of this channel, isn't possible yet.

**Comment by hantt12** [comment]
hi @RomaricMourgues  but what you expect in the description is: 

> Can we have the action "Share channel link" for public channel, so I can copy the channel url to share for my college to join?

Then the current solution can't help other users to join the channel you are sharing

**Comment by RomaricMourgues** [comment]
It is about copy channel link for this issue. Sharing it will be implemented later with all the process of proposing to join the channel or displaying a "you cannot join this channel" error if privzte.

**Comment by hantt12** [comment]
ok
