### ISSUE TITLE
I can't mention user in message

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2037]
https://canary.twake.app/internal/services/workspaces/v1/companies/56393af2-e5fe-11e9-b894-0242ac120004/workspaces/f339d54a-e833-11ea-92c3-0242ac120004/users?search=Ste

`{"resources":[],"next_page_token":"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAE-_FktsSWJacVNjUXF1LWJqclNERnR5bFEAAAAAAABPwBZLbEliWnFTY1FxdS1ianJTREZ0eWxRAAAAAAAAagAWTEt2TnpHQXNSajYwRmpQbjc0QWgtZwAAAAAAAGn_FkxLdk56R0FzUmo2MEZqUG43NEFoLWcAAAAAAABP-xY0eEY5WUotV1JnU00wOUhMT1dNQ0Nn"}`

**Comment by hantt12** [comment]
I am not able to mention in QA platform today

**Comment by RomaricMourgues** [comment]
It should be ok now, I had to update elastic search version and reindex users + applications sorry for this !

**Comment by RomaricMourgues** [comment]
Backend works now, so it is a matter of frontend now

**Comment by hantt12** [comment]
It's ok now
