### ISSUE TITLE
I can't mark as unread on mobile or manage notifications on mobile

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2040]
I can't mark as unread on mobile or manage notifications on mobile

I miss this 2 options:
<img width="711" alt="Screenshot 2022-03-31 at 17 10 16" src="https://user-images.githubusercontent.com/14353924/161088804-8e354901-89b8-49ed-a94d-eb0b74b0bc7e.png">

**Comment by BenoitTallandier** [comment]
Related to https://github.com/linagora/Twake-Mobile/issues/585.
I close this issue and I prioritize the other one :)
