### ISSUE TITLE
Search without accent do not find firstname with accent

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#205]
Search without accent do not find firstname with accent

**Comment by BenoitTallandier** [comment]
Related to #2115

**Comment by RomaricMourgues** [comment]
I'm unable to reproduce on latest version (qa) but it still occurs on canary.
Also, when doing a mention search in direct channels it searches on the workspace and not the whole company, could we check the business rules in general ? When mention someone from a channel, what should be the search scope ? @BenoitTallandier
