### ISSUE TITLE
Sometimes messages in the chat are in the wrong order (Random)

### ISSUE THREAD

**Issue by EvGen94** [linagora/Twake#2051]
Sometimes the messages coming in the chat are in the wrong order

![signal-2022-03-25-162205_001.png](https://images.zenhubusercontent.com/607dfac6010943855d82cb82/fbad4cbb-fdbe-4424-b66b-e23b1dd73179)

![signal-2022-03-25-162346_001.png](https://images.zenhubusercontent.com/607dfac6010943855d82cb82/e3dca7d5-4f2e-45ee-b4ad-82e7f3966c7f)

**Comment by RomaricMourgues** [comment]
Web is not wrong. Threads are ordered by date of last reply.
