### ISSUE TITLE
Unable to mention someone whose first name has less than 3 letters

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#2090]
**To Reproduce**
1. User A's first name only has 2 letters("Ha" for example)
2. User B tries to mention user A

**Current behavior**
It requires at least three letters to search

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/11640302-04ee-46ab-82dd-7a61d50397e3)

**Comment by RomaricMourgues** [comment]
Please try again, there was an issue with backend

**Comment by RomaricMourgues** [comment]
I should work now
