### ISSUE TITLE
Multiple image/photo visualization to improve UX

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2099]
Feature request: multiple image/photo visualization to improve UX.
As example this post from Alexandre: [...]
I have to click in each photo and then go back, on top of it it takes long to load each image.
The expected behavior: click in any image open the image viewer, from the image viewer at least I can move one image forward or backward.

**Comment by BenoitTallandier** [comment]
Is that easy to do or is it a big feature to build ? :)
