### ISSUE TITLE
We can't know if user is connected on Twake or not

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#210]
**Is your feature request related to a problem? Please describe.**
I want to talk with someone, I would prefer to know if he is connected or not.

**Describe the solution you'd like**
Improve green dot system

**Comment by chamerling** [comment]
We did cool things which are working on OpenPaaS on this subject. We should reuse or create a new service based on this.

**Comment by RomaricMourgues** [comment]
This is what is planned @chamerling

**Comment by chamerling** [comment]
Even better, I am the one who did this in OpenPaaS :p

**Comment by RomaricMourgues** [comment]
We already know ;) If you think it can take less than 2 days, you can work on it this week
