### ISSUE TITLE
Update all plugins

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2121]
- [x] Jitsi
- [x] Simple Poll
- [x] Giphy
- [x] N8n

**Comment by Maddonix** [comment]
Hi, 
is this why permission to pull the docker image twaketech/twake-plugins:latest is currently denied?

Best Regards!

**Comment by RomaricMourgues** [comment]
Hi! Thanks for your feedback, in fact bad code was pushed to our docker-compose files in the main branch, I just fixed it. Our plugins server isn't ready for production yet.
I fixed our docker-compose.onpremise.yml and docker-compose.onpremise.mongo.yml files.

For now installing the plugins isn't documented yet, but you can find them here (and also use this examples to create your own plugins):
https://github.com/linagora/Twake-Plugins-Giphy
https://github.com/linagora/Twake-Plugins-n8n
https://github.com/linagora/Twake-Plugins-Jitsi
https://github.com/linagora/Twake-Plugins-Webhooks
https://github.com/linagora/Twake-Plugins-SimplePoll

And try to install them reading the plugin.json in the root of all plugins and this documentation: https://doc.twake.app/developers-api/get-started/create-your-first-application

**Comment by Maddonix** [comment]
Thanks for the fast and helpful reply!
