### ISSUE TITLE
Get files uploaded by user

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2127]

**Comment by hantt12** [comment]
HI @RomaricMourgues can you please give me more info about this backlog so that I can test

**Comment by RomaricMourgues** [comment]
Oh yes, this one is ready on qa but it is backend only, do you want to test backend APIs or do we wait before testing this one ?

**Comment by hantt12** [comment]
Does it effect frontend? Or I just need to retest file upload feature to make sure that changes in backend does not effect the feature?

**Comment by RomaricMourgues** [comment]
Yes, testing file upload isn't a bad idea 👍

**Comment by hantt12** [comment]
Tested in QA/Canary/Production and it's ok with the file uploading
- Add file to discussion
- Add file to Documents section
