### ISSUE TITLE
Plugins issues

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2136]
TODO:

- [x] Messages stuck when interacting with them (ex. simple poll when vote)

- [x] When just typing "/" alone we should have a list of commands before to write a first letter

- [x] Poll: nothing in mobile app notification (we should create a text field)

- [x] Poll: Name of poll creator changes each time someone vote

- [x] Answer to thread with app open the ephemeral message in the main thread creation editor

**Comment by hantt12** [comment]
Messages stuck when interacting with them (ex. simple poll when vote) OK

 When just typing "/" alone we should have a list of commands before to write a first letter OK

 Poll: nothing in mobile app notification (we should create a text field) - STILL NOTHING ON MOBILE

 Poll: Name of poll creator changes each time someone vote OK

 Answer to thread with app open the ephemeral message in the main thread creation editor OK
