### ISSUE TITLE
Thumbnails of PDF / office docs isn't working

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2138]
The tests pass, but it doesn't display on frontend.

We have a process that wait for the file thumbnail to be generated before to add it to the message attachment, may be the preview is in fact generated but the file cached in the message doesn't have this update yet. (If this is the case then a discussion must be done about the architecture update to work on)

For you Khaled a bit more of information:
There is 3 entities related to files, "message", "file" and "message_file"
- *message*: simply a message in which we attache message_file
- *message_file*: contain the message attachment information, a message file attachment has this information: "source" and "external_id", for instance if a files comes from LinShare the source will be "linshare" if it comes from Twake it will be source=internal.
- *file*: the file itself, this entity is only for message attachements of source=internal

The thumbnail generation is done asynchronously, but we can choose to wait for it to finish with thumbnail_sync=1 option

File doc is here: https://doc.twake.app/internal-documentation/backend-services/files-service/rest-apis
Message doc is here: https://www.notion.so/linagora/Rest-APIs-232eb8e51c3743ccbb7aa3534a5a7db9

--

### Update on the investigation to help:
My guess is in fact the preview is generated BUT we do not display it in frontend.
- The method in frontend "mimeToType" in `twake/frontend/src/app/features/files/api/file-upload-api-client.ts` is missing more detection of pdf, documents types
- In FileThumbnail in `twake/frontend/src/app/components/file/parts/thumbnail.tsx` we have logic to display thumbnail of images but we never show thumbnail for other documents types
- Here is also the "large" props login to change to make video larges when displayed in the context of a message: https://github.com/linagora/Twake/blob/8db6d60ae88bf43c3ec24d94eb8a906ceaaaaed7/twake/frontend/src/app/views/applications/messages/message/parts/MessageAttachments.tsx#L48

**Comment by RomaricMourgues** [comment]
@rezk2ll I did a small investigation it seems maybe it is only a frontend issue, I let you check it on the frontend side (I pointed out the files to modify) and in the same time, you'll be able to enable the video thumbnail you just implemented in backend.

I propose to edit a bit the design only for the case of videos:
- Add an icon react-feather (the icon lib we are using) of type 'play' https://feathericons.com/?query=play on top of the thumbnail to make it more "video-ish"

Have fun !

**Comment by hantt12** [comment]
Tested: PDF, ODS, DOC, ODT
