### ISSUE TITLE
LinksPreview::Link thumbnail on web (and improve on mobile)

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2139]
### Technical implementation (backend)

- Get inspiration from this library: https://github.com/AndrejGajdos/link-preview-generator/blob/master/index.js and create a dedicated service on Twake backend.

- We will add a "links" field to the message entity that will be a list of links at twake/backend/node/src/services/messages/entities/messages.ts

- This should not be blocking for the message creation so it is done asynchronously

- Here is the type of one link:

```
{
  title: 'string',
  description: 'string' | null,
  domain: 'youtube.com',
  img: 'string' | null,
  favicon: 'string' | null,
  img_height: number | null,
  img_width: number | null,
}
```

So in the end:
- In messages service `save()` at the end we call `onSaved()`, in this function we call the localEventBus.
- The preview service can be used for such task so we can subscribe to the localEventBus event here, generate the preview, then call again the localEventBus for callback.
- Back on the messages service we get the link preview generation callback and we call again save on the message with the new attachments. This message change will occurs on frontend thanks to websocket (this part already exists).

### Technical implementation (frontend)

TO DO

**Comment by hantt12** [comment]
There is no thumbnail in Mobile app 
![2AE5E372-6D41-4006-9F89-605063100871.jpg](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/56e2d777-7a84-4741-9df9-5b007c34768d)
