### ISSUE TITLE
Message loading may be displayed

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#214]
**Describe the bug**

When switching channel, there is a delay between displaying the channel and the new messages but there are no information about messages are loading. This causes some UX troubles because it can take some seconds and so the user can start to read old messages and new messages (potentially many) are displayed brutally.

**Expected behavior**

Have a message loader at the bottom of the page which tell user that something is ongoing

**Comment by hantt12** [comment]
Hi @RomaricMourgues , which loader do you mean?
https://images.zenhubusercontent.com/271994210/83f7ffde-b6a3-4d39-8247-57333ce7fe67/2022_03_29_13_00_56.mp4

**Comment by RomaricMourgues** [comment]
It is just the fact that we have this gray lines before messages appear
<img width="1792" alt="Screenshot 2022-03-29 at 09 07 35" src="https://user-images.githubusercontent.com/14353924/160553571-244fe6a7-6113-4cea-ae64-da9df73bd50d.png">
.
