### ISSUE TITLE
Empty channel isn't working

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2146]

**Comment by hantt12** [comment]
Hi @RomaricMourgues what do you mean by "Empty channel isn't working"?

**Comment by RomaricMourgues** [comment]
There was a blank page instead of the default empty channel icon:
<img width="484" alt="Screenshot 2022-05-23 at 09 37 26" src="https://user-images.githubusercontent.com/14353924/169767870-3077657f-d39a-4b62-8f8d-d87eef2a2575.png">

**Comment by hantt12** [comment]
ok on canary

**Comment by RomaricMourgues** [comment]
I just created a canary:passed tag for next time
