### ISSUE TITLE
Search crashes Twake

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2186]
On canary just try to search "Benoit" and wait a second

TypeError: Cannot read property 'name' of undefined
----------------------------

    in Mh
    in div
    in div
    in div
    in t
    in div
    in div
    in div
    in n
    in Unknown
    in Suspense
    in zf
    in n
    in component
    in t
    in t
    in t
    in k
    in j
    in Yn
    in Qn
    in Unknown

**Comment by hantt12** [comment]
Wait until this ís deployed to canary
