### ISSUE TITLE
Pull access denied

### ISSUE THREAD

**Issue by selimsandal** [linagora/Twake#2198]
I'm trying to self host Twake on my Linode server. When trying to run
`docker-compose -f docker-compose.onpremise.mongo.yml up -d`
docker gives the error
_Error response from daemon: pull access denied for twaketech/twake-plugins, repository does not exist or may require 'docker login': denied: requested access to the resource is denied_
When I checked I couldn't find twaketech/twake-plugins on Docker Hub.

**Comment by RomaricMourgues** [comment]
Hi, we are sorry for the issue, could you use instead this docker-compose from the canary branch ? https://github.com/linagora/Twake/blob/canary/twake/docker-compose.onpremise.mongo.yml

**Comment by selimsandal** [comment]
Thank you for the help. :)
One more question, for updating docs show that we need to pull the new docker images only, should I update the repository at the same time?

**Comment by selimsandal** [comment]
Server seems up and running but I think I'm doing something wrong. I can't see any tabs other than chat. Documents, tasks and calendar seems to be missing.
