### ISSUE TITLE
Unable to send jitsi/ giphy command

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#2215]
![Peek 2022-06-02 16-05.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/b5d9ce58-8064-4072-81e8-88087035f41f)

**Comment by RomaricMourgues** [comment]
Plugins only works on canary and web.twake.app
But we also have an issue on canary actually :)
#2220

**Comment by RomaricMourgues** [comment]
I did not removed the connectors from qa when you do / because I hope to deploy them on QA some day.
