### ISSUE TITLE
LinksPreview::Links thumbnail frontend implementation

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2217]
On mobile there is Social network preview but not on web

After backend implementation, start implementation of frontent even if final design isn't ready.

![Screenshot 2022-06-02 at 14.08.01.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/336dafa1-667f-43af-914a-92e50e0e71e6
)

**Comment by hantt12** [comment]
Link preview is available on stage
