### ISSUE TITLE
Search:: the popup is not responsive

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2234]
The popup currently have this CSS:

```
width: 800px;
height: 718px;
```

Instead it should have:

```
    max-width: 800px;
    max-height: 718px;
    height: 90vh;
    width: 100vw;
```

**Comment by hantt12** [comment]
Tested in stage. Search popup is responsive

**Comment by RomaricMourgues** [comment]
@haftus98 in this case for each of stage-passed issues could you put the "QA Passed" label ?

**Comment by hantt12** [comment]
Sure

Hà Nguyễn
