### ISSUE TITLE
LinksPreview::Ability to remove the attached link

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2235]
**Describe the solution you'd like**
Right now links attachments are created next to messages that contains a link. Like on Slack, I would like to be able to remove the link using a small "x" button next to the attachment which appear on hovering the attachment.
![Screenshot 2022-06-07 at 11 20 22](https://user-images.githubusercontent.com/14353924/172344871-4aee337a-895d-48b4-bb65-41d19d44ea34.png)

**Additional context**
In order to implement this we will:
- [x] Create and document the new `DELETE /companies/{company_id}/threads/{thread_id}/messages/{message_id}/links/:url_with_encode_uri` endpoint to document in Messages operations in https://www.notion.so/linagora/Rest-APIs-232eb8e51c3743ccbb7aa3534a5a7db9
- [x] This endpoint will call a service in `src/services/messages/services/messages-operations.ts` and will remove any link attachment to the message with the same url
- [x] Only the owner of the message can do this operation so a rule must be added to compare the context user to the message creator.
- [x] The update must be broadcasted via websockets (using `this.threadMessagesService.onSaved(message, { created: false }, context);`)

- [x] On frontend, we will add the api-client function in `src/app/features/messages/api/message-api-client.ts`
- [x] On frontend, we will add this operation to `src/app/features/messages/hooks/use-message.ts` as removeLink(url: string) accessible from the return of the hook
- [x] On frontend, we will add the "x" using feather icons as usual

**Comment by hantt12** [comment]
Passed on staging
