### ISSUE TITLE
WebSocket error messages

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#224]
**Describe the bug**

There are some error in the Web console which seems related to WebSockets:

![Capture d’écran 2020-09-04 à 10 04 35](https://user-images.githubusercontent.com/264403/92216774-0f286780-ee97-11ea-92ee-5824ea29b4e8.png)

**Desktop (please complete the following information):**

OS X, Chrome 85

**Comment by RomaricMourgues** [comment]
This one was fixed some month ago.
