### ISSUE TITLE
I'm unable to start direct discussion with Evgenii

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2241]
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/18c61424-e0fd-44d2-aa36-b494ea6247dd)
https://canary.twake.app/internal/services/users/v1/users
Request Method: GET
Status Code: 200 OK
Remote Address: 51.91.22.89:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: *
Connection: keep-alive
Content-Length: 16
Content-Type: application/json; charset=utf-8
Date: Wed, 08 Jun 2022 11:09:08 GMT
Server: nginx/1.14.2
Strict-Transport-Security: max-age=31536000
vary: Origin
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB
Authorization: Bearer aaaaaStxxWdQ5eJtOpbQOuUxFg9jKgq0JQ-M
Connection: keep-alive
Content-Type: application/json
Cookie: ajs_anonymous_id=653e8272-1442-4bb9-acf8-5d3b93aa4c25; usetiful-visitor-ident=9719a622-2f52-4bad-8f4c-1024a5696d16
Host: canary.twake.app
Referer: https://canary.twake.app/client/bDxmFx1KPWhhJeetsVj12J/w/w31iupjuCFvvbf8ewYcYg7/c/johojrkh44nJR5qrCsquhx
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Twake/1.2.50 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

{"resources":[]}

Request URL: https://canary.twake.app/internal/services/users/v1/users?include_companies=1&search=evge&search_company_id=56393af2-e5fe-11e

{"resources":[{"id":"e80375ba-ad99-11eb-b6c4-0242ac120003","provider":"console","provider_id":"6098efe16d59de0013a8f5cd","email":"esharanov@linagora.com","username":"esharanov_1620216209","is_verified":true,"picture":"https://account.twake.app/api/avatars/6246b65fed915000129e175e","first_name":"Evgenii","last_name":"Sharanov","created_at":1620216209000,"deleted":false,"status":"","last_activity":1640089856,"preferences":{"recent_workspaces":[{"workspace_id":"f339d54a-e833-11ea-92c3-0242ac120004","company_id":"56393af2-e5fe-11e9-b894-0242ac120004"}],"locale":"en","timezone":-180,"allow_tracking":false},"companies":[{"role":"member","status":"active","company":{"id":"56393af2-e5fe-11e9-b894-0242ac120004","name":"LINAGORA","logo":"https://s3.eu-west-3.amazonaws.com/twake.eu-west-3/public/uploads/grouplogo/dffc6bb54e7b5d6ee45d2d877839aa88.png"}},{"role":"owner","status":"active","company":{"id":"54de1f30-8d61-11ec-98ee-67c89c58d9e2","name":"EvCompany","logo":""}}],"preference":{"recent_workspaces":[{"workspace_id":"f339d54a-e833-11ea-92c3-0242ac120004","company_id":"56393af2-e5fe-11e9-b894-0242ac120004"}],"locale":"en","timezone":-180,"allow_tracking":false}}]}

**Comment by RomaricMourgues** [comment]
So you get it from backend but not from frontend right ?

**Comment by RomaricMourgues** [comment]
Also @shepilov never share the Authorisation headers !!!

**Comment by RomaricMourgues** [comment]
Fixed in #2277
