### ISSUE TITLE
Search:: new series of bugs

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2258]
- The width must be 90vw instead of 100vw (my mistake on previous issue) to have the same with height.
- A "0" appear on the search (see image 1)
- When I searched and changed tab I got a general error "cannot red 0 of undefined" (but I can't reproduce right now)
![Screenshot 2022-06-09 at 10 06 16](https://user-images.githubusercontent.com/14353924/172797662-b08fe489-9fd7-4be3-8480-ff4492c1a065.png)

**Comment by hantt12** [comment]
Tested in stage and I don't see these bugs anymore
