### ISSUE TITLE
Docker compose files reference non-existant docker image

### ISSUE THREAD

**Issue by haithcockce** [linagora/Twake#2264]
**Describe the bug**
The docker-compose files include a service for plugins pulling `twaketech/twake-plugins:latest` however, this does not seem to exist. 

**To Reproduce**
1. Pull the repo

        ❯ git clone https://github.com/TwakeApp/Twake.git
        Cloning into 'Twake'...
        remote: Enumerating objects: 41773, done.
        remote: Counting objects: 100% (1309/1309), done.
        remote: Compressing objects: 100% (737/737), done.
        remote: Total 41773 (delta 701), reused 1053 (delta 527), pack-reused 40464
        Receiving objects: 100% (41773/41773), 64.76 MiB | 12.07 MiB/s, done.
        Resolving deltas: 100% (21455/21455), done.

2. Attempt to start one of the containers; 

        ❯ cd Twake/twake; docker-compose -f docker-compose.onpremise.mongo.yml up -d
        Creating network "twake_default" with the default driver
        Pulling mongo (mongo:)...
        latest: Pulling from library/mongo
        d7bfe07ed847: Pull complete
        97ef66a8492a: Pull complete
        20cec14c8f9e: Pull complete
        38c3018eb09a: Pull complete
        ccc9e1c2556b: Pull complete
        593c62d03532: Pull complete
        1a103a446c3f: Pull complete
        cd6085016f3a: Pull complete
        1e8109db46fc: Pull complete
        Digest: sha256:fdd0492cda0d166e877cc9ec11040767dec2598a60c77f7f7730f9b04f06e19f
        Status: Downloaded newer image for mongo:latest
        Pulling plugins (twaketech/twake-plugins:latest)...
        ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
        
        Continue with the new image? [yN]y
        Pulling plugins (twaketech/twake-plugins:latest)...
        ERROR: pull access denied for twaketech/twake-plugins, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Expected behavior**
It works

Unless I am missing something, the image does not exist?

**Comment by fawqsir** [comment]
Create a `dock-compose.override.yml` and build the plugin from `docker/twake-plugins/Dockerfile``. I trying with

```
services:
  plugins:
    build:
      context: .
      dockerfile: ./docker/twake-plugins/Dockerfile
```

Untested..... but building so far.

**Comment by RomaricMourgues** [comment]
Hi, sorry for late response, it was fixed the missing container was removed from the docker-file :)
