### ISSUE TITLE
Create direct channel search doesn't work

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2277]
For QA: I re-built from scratch the modal to create new direct channels, it should work better than before.

**Comment by RomaricMourgues** [comment]
@shepilov do you think I should fast forward it to canary ?

**Comment by hantt12** [comment]
Tested on Stage today. 
Is that necessary to be able to create direct message to himself?

**Comment by RomaricMourgues** [comment]
Yes it is commonly reuested by users for perosnal notes
