### ISSUE TITLE
[Story] Managing user inside a channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#2293]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a workspace member,
When I look to invite someone inside a channel
Then I open the channel member panel,
And I start to search the user inside the workspace member,
And I click on "add" near the user found
```

## Business case
- If the user is a guest, I can see the "guest" label after his name
- There is a button "invite user in this workspace" leading to the user page of the workspace settings.
- We do not have the "guest management" option in the menu : 
![Group 512711](https://user-images.githubusercontent.com/22451567/173834816-859b693c-cb3a-4270-a6e9-d97eb7ee8985.png)

## UI UX Design

![Group 512710](https://user-images.githubusercontent.com/22451567/173834349-396416d8-4c05-467b-ac2d-36fa0bc6d430.png)

**Comment by hantt12** [comment]
Hi @RomaricMourgues  is this deployed to staging? I am not sure because Guest Management is still there 
![image.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/c96229bb-f8c4-4ddd-9fbe-11b492bb679e)

**Comment by hantt12** [comment]
Please check issue https://github.com/linagora/Twake/issues/2465

**Comment by tprudentova** [comment]
Hi @RomaricMourgues 
It is impossible to remove a user from channel, as well as to leave it. 
Remove -> Confirm/Leave -> Nothing changes

**Comment by RomaricMourgues** [comment]
Close and replace by #2527
