### ISSUE TITLE
Unable to search a file by filename in All tab

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#2302]
But  it's still able to find it in Files tab
Tested in stage

![Peek 2022-06-16 11-29.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/71c5f6b9-a5ef-4b50-9d3e-a2b42356bafd)

**Comment by RomaricMourgues** [comment]
@shepilov @romanesko as expected this is not clear for users, can we hide the "All" tab while doing search or rename it to Channels ?
Even better but heavy on backend, could we add a small number next to tabs to display how many results is there ?

My proposal would be:
- Display files and medias in All
- All tabs have a little number to display number of result in each the category

**Comment by RomaricMourgues** [comment]
@romanesko it still doesnt work on QA, but I see the calls are done to the backend. So probably just frontend stuff
