### ISSUE TITLE
DesktopLink::Add banner to download the app

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2318]
Following #2316 if we detect that we are on desktop AND that the desktop app is not installed, we show a banner to propose to download the desktop app.

- [x] The download link should be added to the backend https://web.twake.app/internal/services/general/v1/server configuration field as `app_download_url`

- [x] A X button must be added to the banner, clicking on it hides the banner and store the user preference to localstorage (to avoid opening the banner again on this session)

- [x] The banner must be open only for desktop devices (no mobiles and tablets)

Here is the design for it:
-> Height of the banner is 72px
-> The banner must not be visible if screen width is < 600px (use tailwind also for this, `hidden sm:block` will do exactly this)
-> It uses a Text.Title with className="text-white", a Button type "secondary" (with an override using bg-white maybe) and a X icon we can get from the feather icon lib (already used in the project). The background color is the following that we can add to the index.scss at the root of the frontend app:
```
.bg-linear-purple {
  background: linear-gradient(263.04deg, #007AFF 2.08%, #C600F9 97.25%);
}
```
- [x] This banner is a "molecule" or a "component" (depending on how you separate the logic for this) but the UI must be available in storybook. In the storybook you'll be able to play with dark mode: it should look exactly the same in dark mode, there is no variation.

![Screenshot 2022-06-17 at 13.13.39.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/ba3c4977-b6c4-4d9d-9a88-765ea0efe7e4)

**Comment by RomaricMourgues** [comment]
@shepilov @BenoitTallandier @BastiaanVanGaalen please confirm that's good for you

**Comment by shepilov** [comment]
Yep, it's fine
