### ISSUE TITLE
Search:: search in medias shows preview of the wrong file

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2326]
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/ff8c7bc5-aac7-4446-b49f-28099e217a63) ![image.png]

- log in as red@yopmail.com to QA env
- Search "Screen" in media
- Click on the very first search result in the picture above
- The the following video displayed

![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/24c92ba3-c4de-40ae-b7e9-0a373988565b)![image.png]

**Comment by RomaricMourgues** [comment]
What wrong type are they ? Medias are images and videos for backend
