### ISSUE TITLE
Search:: search preview doesn't work for files on QA

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2327]
1. Search for "test" in files
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/89f56f7e-33b0-4b2b-bdf8-6065c35b45b2)
2. Click "eye" on the very first file
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/1cb86acb-72d6-403f-bab1-39d8cb20394a)
3. With all other files you will have nearly the same behavior
QA, red@yopmail.com

**Comment by RomaricMourgues** [comment]
What do you mean, are you talking about medias or files ? I just tested without issues. But for files you need to click on the right "eye" icon

**Comment by shepilov** [comment]
Update issue description

**Comment by RomaricMourgues** [comment]
Yes on QA onlyoffice is not enabled, so preview of office files is not possible. Adding onlyoffice to QA will be difficult as it is not migrated to node yet. I can ask Khaled to work on this next maybe it could be ready for end of sprint I thin ?

**Comment by shepilov** [comment]
But for pdf files is the same, do we use OnlyOffice to preview pdfs?

**Comment by shepilov** [comment]
If it's OnlyOffice issue then forgot about it, I don't think we need it on QA right now

**Comment by RomaricMourgues** [comment]
For PDF it should work yes so I'll check PDF, maybe it is related to #2326
