### ISSUE TITLE
https://twake.app/en/pricing/ contact email is wrong what is the correct one now ?

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2328]
contact@twakeapp.com doesn't exist anymore.

**Comment by RomaricMourgues** [comment]
@BenoitTallandier just send me the correct active one I can do the change if you cannot :)

**Comment by MBG1990** [comment]
Hi both, the following email addresses are used to contact Twake. I hope this helps:
helpdesk@twake.app
community@twakeapp.com

**Comment by MBG1990** [comment]
You can even use this: marketing@linagora.com
