### ISSUE TITLE
Search:: just uploaded files doesn't shows in recents section

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2329]

**Comment by RomaricMourgues** [comment]
You need to send the message and not just upload the file without sending the message if this it the test case.

**Comment by shepilov** [comment]
I've sent the message,
QA, red@youpmail.com, Magenta @ Brown company
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/32257e97-134d-441b-b978-92161f6e7f76)
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/b163e296-9924-491e-9bc1-a51632b670a9)

**Comment by RomaricMourgues** [comment]
Thanks !

**Comment by hantt12** [comment]
Still not showing in staging

![2022-06-28_10-49-37.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/57ac17f4-a359-4039-917e-b0a7a293cdfc)
