### ISSUE TITLE
Rebuild desktop app after Khaled work for all OSes

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2352]
- [x] linux
- [x] mac
- [ ] windows

**Comment by RomaricMourgues** [comment]
@rezk2ll could you try to build the app for windows ? I can't do it anymore from my mac because 32bit is not supported.
The process is do `npm run build-w` then:
- get the `*.msi` file and rename it to `Setup_Twake_lastest.msi` and compress it to `twake-win-msi-latest.zip` and move to download (replace the old one)
- get the `*.exe` file and rename it to `Setup_Twake_lastest.exe` and compress it to `twake-win-latest.zip` and move to download (replace the old one)

**Comment by rezk2ll** [comment]
done in https://github.com/linagora/Twake-Desktop/pull/20 @RomaricMourgues
