### ISSUE TITLE
Search:: message search results layout broken

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2368]
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/14399e98-7d80-4710-8b07-d721f93b6267)

QA
red@yopmail.com

**Comment by RomaricMourgues** [comment]
Nice one, thanks fix it now could you send me credentials of QA in Twake MP ?

**Comment by RomaricMourgues** [comment]
Fixed in #2367
