### ISSUE TITLE
Search:: When you click "Go to file button" you are switching to another company account

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2369]
- login as red@yopmail.com
 - chose Crayon company and go to the "Files search" screen
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/52cf0102-7784-415d-ba78-dbabd754cbfc)
 - Click on "Screenshot..."
 - And you ar in the "Company 1"
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/b6d18946-d7ef-4401-a22d-ce12dc508a45)

**Comment by RomaricMourgues** [comment]
Is it possible that you closed the search, changed company, open it again and saw the files from previous company ?
When I try from Crayon company I see 500 errors in the backend, so the list is not refreshed from the previous company I think.
So two issues:
- When changing company we should not display the previous search files that are still in cache
- There is a 500 error in backend for the crayon company

**Comment by RomaricMourgues** [comment]
Fixed in #2367
