### ISSUE TITLE
Search:: channels search screen is broken

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2370]
![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/0db1c56a-f7a4-4ab0-bd6f-2a9375c62120)

**Comment by RomaricMourgues** [comment]
This one is known I noticed in the PR / Issue that channel search wasn't completely done yet :) #2367

**Comment by RomaricMourgues** [comment]
Fixed in #2367
