### ISSUE TITLE
I can't add user to direct chat

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake#2373]
On canary I cant' add Tuan Le Cong to the direct chat

![image.png](https://images.zenhubusercontent.com/61d71534908989d005c70232/4123a787-ea91-4e7d-9a33-2ef2eba390c9)

it exists in the response from server but on UI displayed another person

https://canary.twake.app/internal/services/users/v1/users?include_companies=1&search=tua&search_company_id=56393af2-e5fe-11e9-b894-0242ac120004

**Comment by RomaricMourgues** [comment]
I can reproduce, I will fix it

**Comment by hantt12** [comment]
tested on staging
