### ISSUE TITLE
Give the work to DevOps to install Knowledge graph

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2376]
**Description**

The knowledge graph is a central graph-based database for all our product that will try to detect relations between users and objects to propose AI like proposals (like when sending a message about something the IA could propose to create a meeting or stuff like that, also put some statistics like people we like to talk with the most etc)

This first installation is to test some features over real data, even if it is deployed in production, only Linagora users who authorised usage of their data will be in this graph.

**Our needs**

- [ ] Install the knowledge graph for two environment (so everything after is to do twice): 1 instance for QA environment + 1 instance for production environment. A 4cpu 4gbram 50gb hdd/sdd will be enough for the tests

- [ ] The knowledge graph machines should be accessible in their own environment (QA / Prod) on ports 8082 by all products backends (TMail, Console and Twake for now) (set up the security rules accordingly)

- [ ] Port 80 and 443 will be open through VPN for easy usage of Linagora Labs

- [ ] Install this in the machine https://ci.linagora.com/linagora/lgs/labs/workathome/-/tree/master/WKG contact Yazid Benazzouz for more information on how to set it up. I don't think the Readme is up to date, just run the docker-compose.yml should be ok. (we don't need to init data, we don't need to use the python kg-rest-api neither)

- [ ] Create a Dockerfile to run kg-app (javascript frontend) and expose it on port 80.

- [ ] Notify Yazid and Romaric for each of us to test our access and see next steps.

**Comment by tk-nguyen** [comment]
Is the B2-15 instance sufficient for both QA and production? Or do we have any more requirements for this database?
