### ISSUE TITLE
Implement push notification when someone react to a message

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2414]
**Context**

Today there is no notification if someone react (add a 👍 or any other emoji) to our message.

**Solution**

When a reaction is added, a notification should be sent to the message owner.

See notification current schemas (there is two of them) here: https://www.notion.so/linagora/Notifications-ccfee5c0d50c45bd80f5140c2032f828

This will not add any badge but just create a notification with this content: *[User Name]: 👍 to "[message-content]"*

An exemple of push to desktop and mobile is here: twake/backend/node/src/services/notifications/services/engine/processors/push-to-users.ts but be careful this fucntion also set new badges (which we don't want). This service is triggered by the "notification:mentions" event, **we will create a new "notification:reaction" event and processor.**

**Comment by tprudentova** [comment]
Hi @RomaricMourgues 
Has this issue already been deployed to staging? For now you never receive notifications upon reactions (both for web and mobile)

**Comment by hantt12** [comment]
I don't see push notification at all for both Chrome and Firefox

**Comment by RomaricMourgues** [comment]
@hantt12 just for sure could you test this demo and tell me if this one trigger notifications for you? https://web-push-book.gauntface.com/demos/notification-examples/

I found that latest version of Mac OS doesn't show notification either on Chrome, Safari and Firefox on my side.

Actually for Chrome, I can find the notification if I open the right notification center.
It works using the Desktop app for sure at least.

Note: I actually found an issue anyway with the notification requestPermission stuff. So I have somthing to fix :p

**Comment by hantt12** [comment]
hi @RomaricMourgues  yes push notification is there if I check in https://web-push-book.gauntface.com/demos/notification-examples/ but still no notification on Twake

**Comment by RomaricMourgues** [comment]
Did you try again recently ? Because here it works on all browsers and on desktop now

**Comment by hantt12** [comment]
> Did you try again recently ? Because here it works on all browsers and on desktop now

I tried it today

**Comment by RomaricMourgues** [comment]
Then I don't know, here no problem, try force-reload the app, or go into the dev console of Chrome and type: `new Notification("a")` If it doesnt work try doing `Notification.requestPermission();` then repeat

**Comment by RomaricMourgues** [comment]
Also notice that notification on chrome are forcefuly disabled on incognito mode

**Comment by hantt12** [comment]
I did not test in incognito mode :(

**Comment by RomaricMourgues** [comment]
> Then I don't know, here no problem, try force-reload the app, or go into the dev console of Chrome and type: `new Notification("a")` If it doesnt work try doing `Notification.requestPermission();` then repeat

And what about that ?

**Comment by hantt12** [comment]
Still just the sound.  No push notification. Tested on staging

**Comment by hantt12** [comment]
Tested in 3 other computers and still no push notification. I have no idea :(

**Comment by RomaricMourgues** [comment]
Then I need you to follow this procedure:
- Open a non-incognito window of any browser
- Open the developers tools and go to the console
- Type `new Notification("a")` in the developer console and tell me what happens (test 1)
- Click anywhere on the Twake window
- Type `new Notification("b")` in the developer console and tell me what happens (test 2)
- Then type `Notification.requestPermission();` in the developer console
- Type `new Notification("c")` in the developer console and tell me what happens (test 3)

If you can record the entire procedure it would be helpful :)

What's I guess is happening is that the notification permission are not requested/granted correctly during your tests, we have a very simple notification grant system, when you click on the window the first time (anywhere) it should ask you to enable the notifications. So please follow my procedure and send me the results for me to analyse what is going on.

**Comment by hantt12** [comment]
Out of my surprise, today when I access Twake Staging, system asks me the permission to send notification then I accept. Now I can see the push notification and this function works. Thank you
