### ISSUE TITLE
Fix landing page language auto-selection and agnostic links

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2438]
I can't set the download url to the twake config, because https://twake.app/download returns a 404, so I need to choose a language and so for know it is https://twake.app/fr/download (and it stays to fr). It should automatically choose the right language, or fallback to english. E.g.:

- https://twake.app/download should work and move to https://twake.app/fr/download or https://twake.app/ru/download

- https://twake.app/fr/download if I change to russian (in production) then I am redirected to https://twake.app/ru/ but I should be redirected to https://twake.app/ru/download with english text if russian is not ready yet.

I guess the issues comes from a bad framework / i18n library, so the minimum is to have the /download redirect to /fr/download depending on browser language has hot fix...

**Comment by rezk2ll** [comment]
PR: https://ci.linagora.com/linagora/organization/twake/-/merge_requests/185
