### ISSUE TITLE
Infinite calls to read section on some cases

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2477]
![Screenshot 2022-09-01 at 09.35.14.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/7f9638c1-9357-42c1-b660-e941788544d6)

**Comment by RomaricMourgues** [comment]
@rezk2ll is it fixed in the latest versions ?

**Comment by rezk2ll** [comment]
> @rezk2ll is it fixed in the latest versions ?

Yes
