### ISSUE TITLE
[Mail digest] Email sender

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2492]
US: https://www.notion.so/linagora/Email-notification-deb6cac3b2a6480c840b44b8ac6d53f5

This issue is about sending emails, asserting that we already have the html, subject, and recipient email.

- [ ] Creates a email-pusher platform service if not already created by #2491
- [ ] Add the function `send(to: string, email: {subject: string, html: string, text: string}): Promise<void>`
- [ ] This function will use this API, credentials must be added to the configuration under a new service key "email-pusher" https://apidoc.smtp2go.com/documentation/#/README

**Comment by hantt12** [comment]
Hi @RomaricMourgues  can you please add me to notion so that I can view the US
my email: tthnguyen@linagora.com

**Comment by RomaricMourgues** [comment]
Yes I’ll add you but this should not yet be in qa column sorry
