### ISSUE TITLE
[Mail digest] Notifications preferences

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2494]
US: https://www.notion.so/linagora/Email-notification-deb6cac3b2a6480c840b44b8ac6d53f5

This issue covers the ability for users to configure if yes or not they want to receive digest by email and also re-enable other notification options.

- [ ] Put back the notification preferences page that should be available from here (see screenshot). THE CODE ALREADY EXISTS SO FIND IT FIRST before to duplicate existing work :)

![Screenshot 2022-09-30 at 09.01.37.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/fb9ae175-9c98-449a-a5b7-624489f506b0)- [ ] Fix / remove elements of this pages to make sure everything works (ability to save ans edit fields), see with Romaric if all fields still make sense.

- [ ] Add / fix the Email Digest option. The different options are: "Do not send email digest", "Send after 15 minutes", "Send after 1 hour", "Send after 1 day"

This issue is only about saving the preferences, not sending the email digest or any other actual feature.

**Comment by RomaricMourgues** [comment]
@tprudentova If you can test it, it should send an email after 15 minutes when you did not read a message.

**Comment by tprudentova** [comment]
Preferences work fine except for the imposition on the screenshot, however, I didn't get an email after 15 minutes.
![Screenshot 2022-09-30 at 11.15.29.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/cc641659-f340-46b4-b840-ba79b36becb2)

**Comment by tprudentova** [comment]
Upd: received the email 26 minutes after the message was sent.

**Comment by RomaricMourgues** [comment]
Then it is on purpose for the 26 minutes, it is an approximation and it will be always between the requested delay and +15 minutes
