### ISSUE TITLE
On the canary env the "see users of channel" feature don't work, here the error

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2512]
![Capture dcran de 2022-09-13 12-50-42.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/fc86477c-829a-4672-a036-b48c35b7938f)

![Capture dcran de 2022-09-13 12-52-14.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/c6bd94af-4892-4a07-9062-dc276f87ae70)

**Comment by RomaricMourgues** [comment]
It is ok on QA so maybe a release to do then it will work ?

**Comment by RomaricMourgues** [comment]
Need plug dev frontend to prod backend to test

**Comment by rezk2ll** [comment]
> It is ok on QA so maybe a release to do then it will work ?

it's not ok on QA I still can reproduce it

![image](https://user-images.githubusercontent.com/6764881/190389440-5710fd6e-a470-49d7-8829-1298f0934230.png)

**Comment by RomaricMourgues** [comment]
Ok then it is user related, like some users of channels are null maybe ?

**Comment by RomaricMourgues** [comment]
This one works now, it was some missing null pointer exception tests, anyone experienced this again or can I move this to canary ?

**Comment by RomaricMourgues** [comment]
@tprudentova @hantt12

**Comment by tprudentova** [comment]
Works fine for me!
