### ISSUE TITLE
Status ís Seen when user ís online, not really seen

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#2516]
Steps:

1. There are more than 1 members in a channel
2. User A is opening the above channel in a browser tab, but currently not open that tab
3. User B send a message to the above channel
4. user B check who read the message

Expected result:
User A is not in the list of who read the message

Actual result:
List shows that user A read the message

**Comment by RomaricMourgues** [comment]
@rezk2ll this is about window being focused or not
