### ISSUE TITLE
Unable to leave channel

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2527]
Backend call is done but channel list does not refresh

**Comment by tprudentova** [comment]
When you're the creator of the channel, it is impossible to leave it, you get the following error
![Screenshot 2022-09-26 at 12.22.50.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/f4d9b80a-13da-4ca7-b8d8-d8e106359c7a)

**Comment by RomaricMourgues** [comment]
I will push a potential fix today but I don't know if it will be fixed. Could you open the developer tools (cmd+alt+I) then do the test and send me a screenshot of the request input ?
It should look like this (note the "Payload" tab). The line I want to see will be in red, if you have multiple red lines then send me multiple screen shots.

![Screenshot 2022-09-27 at 10.20.17.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/a65a21bf-5e01-493b-8346-7a42518d16be)

**Comment by tprudentova** [comment]
<img width="1280" alt="Screenshot 2022-09-27 at 12 59 51" src="https://user-images.githubusercontent.com/97684890/192496634-1f90e0bf-8e4f-4071-ba8a-3125b87c115a.png">
I'll need your guidance since I'm an amateur x) I suppose it looks different for macOS, could you tell me what info you need?

**Comment by RomaricMourgues** [comment]
Oh sorry, so from there in Firefox it seems, you need to go to "Network", then you will get a list of all requests, look for all red requests and click on them, a new view will be visible with a tab "Request" that you should select and then send me the screenshots.

On firefox it looks like this:
<img width="945" alt="Screenshot 2022-09-27 at 12 04 25" src="https://user-images.githubusercontent.com/14353924/192497615-95b462d5-4cf2-4e0e-b75c-4e926a80bef6.png">

**Comment by tprudentova** [comment]
Here's the way it looks for Safari, no Request tab in the new menu :( And the bug only seems to happen for Safari
<img width="1280" alt="Screenshot 2022-09-27 at 13 09 01" src="https://user-images.githubusercontent.com/97684890/192499519-bfac5281-8955-4294-8780-14f268251825.png">

**Comment by RomaricMourgues** [comment]
Thanks, that is almost perfect, you see the little select "Response" at the top right of the screenshot ? Do exactly the same but select "Request" before to send it to me :)

**Comment by tprudentova** [comment]
<img width="1280" alt="Screenshot 2022-09-28 at 09 49 27" src="https://user-images.githubusercontent.com/97684890/192708154-8dd3df69-9f60-44bb-9452-08d2bb9a42ae.png">
<img width="1280" alt="Screenshot 2022-09-28 at 09 49 37" src="https://user-images.githubusercontent.com/97684890/192708169-c44dc3cc-cf16-4404-92d8-1616baeddd16.png">
The Response button only gives you view options, but I hope it helps!
