### ISSUE TITLE
Readonly channels option

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2549]
Goal of this issue is to add an option to restrict the write-ability of a channel to only **moderators** and **the owner** of the channel (invisible information that is the creator of the channel).

- [ ] Add a button in the channel editor modal, only moderators and owner can update this value.
- [ ] Add a field in the channel database object
- [ ] Add the field in the channel type in frontend typescript
- [ ] If the channel is readonly and the user is not owner and user is not moderator of the workspace then lock the input like we did for deactivated users. Note that responses to threads must still be allowed.

*Note:* the test to know if the user is an moderator or not is a common service: `AccessRightsService.hasLevel(workspaceId, 'moderator')`

**Comment by tprudentova** [comment]
Hi! 
When writing ability is restricted, user with insufficient access gets a warning about access being restricted, however they can still create new discussions
![Screenshot 2022-10-25 at 17.05.39.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/451e5fc9-adaf-4c81-9681-afee76803d60)

**Comment by RomaricMourgues** [comment]
Thanks again @tprudentova ! Fixes are on their way https://github.com/linagora/Twake/pull/2591

**Comment by RomaricMourgues** [comment]
Should be ready to test again

**Comment by tprudentova** [comment]
@RomaricMourgues hi!
On the video you can see that the second user (they’re not the owner of the company but are the creator of the chat) can send messages in a read-only chat but doesn’t have access to the chat settings thus can’t make the channel read-only. If I understand correctly, it should be either both of the features (for owners and moderators) or none (for everyone else).
https://images.zenhubusercontent.com/271994210/2d6d8b64-aaf0-4f9e-a97e-44600fea7357/screen_recording_2022_11_10_at_15_44_38.mov

**Comment by RomaricMourgues** [comment]
Yes Channel owner should have access to settings, I’ll fix that !

Romaric
