### ISSUE TITLE
Channels settings redesign

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2550]
US: https://www.notion.so/linagora/Channel-Settings-d369e10c5eac4ab48d8a86a643addacc

PR: https://github.com/linagora/Twake/pull/2579

**Comment by tprudentova** [comment]
1.	Channel doesn’t have a profile picture, however it says “remove picture” and you have to press it for it to switch to “upload picture”
https://images.zenhubusercontent.com/271994210/c1b34267-f4b1-4a25-abe3-060fd79930de/vid_20221028_122609.mp4
2.	Set channel group to “$1”
![Screenshot 2022-10-26 at 14.27.14.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/c112504b-8c1d-44dc-a9cb-b4380387be6f)
3.	When you add a channel to a channel group, its profile picture isn’t displayed correctly anymore
https://images.zenhubusercontent.com/271994210/48518151-83e9-4918-b775-6650be93a3d3/vid_20221026_143007_wfxqox2d.mp4
![Screenshot 2022-10-28 at 11.14.28.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/6c4b926a-f4f4-45f8-b712-64450744a1c6)
4.	Channel type isn’t changed from public to private and vice versa instantly, it’s displayed incorrectly in channel settings for a second or so. Not sure it’s that important but decided to mention it anyway
https://images.zenhubusercontent.com/271994210/6bd8cce5-87ca-4974-9d6b-1a48d72cbf66/vid_20221028_115851_0_.mp4

**Comment by RomaricMourgues** [comment]
Thanks @tprudentova ! Fixes are on their way https://github.com/linagora/Twake/pull/2591

**Comment by RomaricMourgues** [comment]
Should be ready to test again

**Comment by tprudentova** [comment]
@RomaricMourgues 
1. Fixed 
2. Still "Set channel group to “$1”" and also I think it's best to name it "channel groups" instead of "channels groups"
3. Fixed
4. Fixed
