### ISSUE TITLE
Message sent isn't visible

### ISSUE THREAD

**Issue by tprudentova** [linagora/Twake#2559]

**Comment by tprudentova** [comment]
When you type and send a message, it isn't seen in the chat until you reload the app. 
https://images.zenhubusercontent.com/271994210/efd994d5-00bc-45e8-80d2-1867fa8aa758/vid_20221006_092916_825.mp4

**Comment by EvGen94** [comment]
I can't reproduce

**Comment by tprudentova** [comment]
This one does get reproduced on canary, check the video. On the 1st video I’m trying to upload any kind of file, none of them seem to be sent. However, once you leave chat and come back, all of the files appear to have been sent. 
https://images.zenhubusercontent.com/271994210/24973cd3-5fd3-41c6-a302-592fbd7791b7/screenrecorder_2022_10_10_15_44_00_241_3b7valgk.mp4
https://images.zenhubusercontent.com/271994210/24f55930-314f-47af-8d4e-15b69e15937a/screenrecorder_2022_10_10_15_44_40_191.mp4
