### ISSUE TITLE
Top panel of the direct chat breaks

### ISSUE THREAD

**Issue by tprudentova** [linagora/Twake#2560]

**Comment by tprudentova** [comment]
Path: open a channel -> member management -> choose any member -> send a direct message -> switch to a different chat/channel -> come back to the direct chat -> top panel is greyed out. 
Fixed by reloading the app.
![Screenshot_2022-10-05-11-35-58-072_com.twake.twake.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/863896c6-9449-4ecb-8ca5-3b76fcbd6367)

**Comment by tprudentova** [comment]
Also, when you follow the path open a channel -> member management -> choose any member -> send a direct message, the top bar of the said channel is displayed instead of the top panel of the direct chat (the contents are of the direct chat though
https://images.zenhubusercontent.com/271994210/1c762174-fd6e-4d9f-baa1-217c32bba154/1234.mp4)

**Comment by EvGen94** [comment]
Done https://github.com/EvGen94/Twake-Mobile/commit/be2894d9c2da22f37f6269920518297efc56c14f
