### ISSUE TITLE
Some of the interface is not English but french

### ISSUE THREAD

**Issue by jhjacobs81** [linagora/Twake#265]
**Describe the bug**
Some items in the mobile (iOS/iPadOS) app are in french.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro & iPad Pro 2017
 - OS: iOS/iPadOS 13.7
 - Version latest version from the appstore

**Additional context**
![14175C4E-4246-46AC-A5F8-FC8B63DAA2E3](https://user-images.githubusercontent.com/5583803/93462520-bfaa5880-f8e6-11ea-94f4-13101c17bc61.jpeg)

**Comment by BenoitTallandier** [comment]
This bug concerns the mobile application.
