### ISSUE TITLE
Add websites as tab in channel

### ISSUE THREAD

**Issue by jhjacobs81** [linagora/Twake#267]
**Is your feature request related to a problem? Please describe.**
Too much open apps :-)

**Describe the solution you'd like**
It would be nice to add external websites to channels. For instance, our dev team could watch the github bugtracker would leaving the app. Our marketing team could check their Graphana dashboard which displays mailclicks, our tech team could follow subreddits related to tech, etc. etc.

**Additional context**
I spend a lot of time in my communications app, it would make my workflow more efficient if i dont have to keep switching apps. More efficient.

**Comment by BenoitTallandier** [comment]
For now, It's possible to add a link in the channel description with markdown : `[mylink](my title)`.
We can say that is enough to answer business need.
