### ISSUE TITLE
Open a default workspace

### ISSUE THREAD

**Issue by jhjacobs81** [linagora/Twake#268]
**Is your feature request related to a problem? Please describe.**
Whenever i open the app or webapp, it always opens the first workspace (name begins with D) while i prefer opening a specific workspace by default (name starts with S) 

**Describe the solution you'd like**
Allow site admins to set a default, which can be overridden by the user’s personal preference.

**Describe alternatives you've considered**
None.

**Additional context**
I want Admins to automaticly open the Admin workspace, while Marketing should automaticly open the Marketing workspace.

**Comment by BenoitTallandier** [comment]
We'll do it in this ticket : #1919
