### ISSUE TITLE
Desktop File Sync

### ISSUE THREAD

**Issue by x3haloed** [linagora/Twake#282]
**Is your feature request related to a problem? Please describe.**
I want to be able to work on documents that aren’t supported by ONLYOFFICE and have them automatically update on the server so that my teammates can quickly see the changes and comment on them or improve them.

**Describe the solution you'd like**
I would find Twake to be a much more useful collaboration tool if it could sync the Documents to my local computer like Google Drive can.

**Describe alternatives you've considered**
Manually uploading new versions, sticking with ONLYOFFICE formats, or avoiding Twake's "Documents" app/plugin altogether.

**Comment by LawlessWorld** [comment]
I would be cautious with the local sync, if this is applied with multiple users working on the same document this will cause issues.  This happens all the time on systems that have this option like nextcloud/owncloud/google with multiple users working on the same shared document and syncing locally.   Single users, it's no problem, but it gets sticky with groups.

In my opinion, i would integrate as you show in the website/saas model, being able to add additional storage's into the system.  I would personally prefer to be able to add files from my self-hosted nextcloud into twake and work on them from there, as well as Linshare when that comes out and some clients of ours have google drive/dropbox.  

BTW, we are integrating collabora online with our instance of twake and will make it available to the community when we are finished for self-hosted.  so you will have another option to edit docs soon aside from only office.

**Comment by BenoitTallandier** [comment]
We won't do it directly. it will be achieved through the LinShare integration (https://github.com/linagora/linshare)
