### ISSUE TITLE
Can not find someone named _Ha Lastname_

### ISSUE THREAD

**Issue by digitalfredy** [linagora/Twake#305]
**Describe the bug**
We have a team member named _Ha_, to keep him anonymous let's say his last name is _Lastname_ and we can not find name using the `@` in the message box

**To Reproduce**
1. Go to 'message box in a channel'
2. Click on 'write' `@ha` and look for _Ha Lastname_ in the list (is not)
3. Do the same procedure but write `Lastname` (it works but not sure if is because is his last name or because is in his username)

**Expected behavior**
The search `@ha` (or any other 2 letters name) must to keep in count names starting by _Ha_ and specially include names that match 100% the search, then `@ha` supposed to show all people named _Ha_ and for sure excluding the tens or hundreds of people with _ha_ in his name, then Sthep**ha**ne do not supposed to be included.

**Comment by RomaricMourgues** [comment]
It works now we updated the search algorithm to first display people with short name / more closest names to the query.
