### ISSUE TITLE
[Story] Star channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#310]
Epic #308

**As an internal user, I can star direct conversations or channels.**

As an internal user, if I want to access quickly, I can star channel or direct message by clicking on the three dot icon, and click on "Star the channel"
The channel goes in "stared" section between Applications and channels
![Capture d’écran 2020-10-06 à 15.33.32.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/fa543e72-387f-4aac-b9e9-95495e34df94)

**Comment by BenoitTallandier** [comment]
Related t #209

**Comment by hantt12** [comment]
Hi @RomaricMourgues I don't see "Star the channel" option but I mean "Add to favorites". This is the old feature.
Have you deployed "Star channel" feature to QA platform?

**Comment by RomaricMourgues** [comment]
The text is “Add to favorite”, this is the same feature as “Star channel”, just the text that is different.
