### ISSUE TITLE
[Story]  CMD + K

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#311]
Epic #310 

**As a user, I can search for a channel or a user in the CMD + K**

As a user, when I have want to search a channel or a user, I can click on the search (right&top) or use cmd/ctrl + K to open the popup search. 
In this popup, I can search channels where I am in the company or member in the company (for direct discussion).

Use the same design as before. Add user proposition design like this
![CMD + K for user proposition.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/9ac690ae-eedb-4d99-bef3-18cfe71b21a1)

**Comment by BenoitTallandier** [comment]
# Update
We need to be able to navigate through the channel list with up and down key.
The goal is to switch quickly from a channel to an other. CMD + K => "my channel" => Up or down to select the channel => Press enter key to go to this channel.

For now, we have to use our mouse : 
https://user-images.githubusercontent.com/22451567/107355097-4e568680-6acf-11eb-9c57-1dd620362289.mov

**Comment by RomaricMourgues** [comment]
See issues in #995
