### ISSUE TITLE
[Story] Notifications by channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#312]
Epic #308 

As a user, I can chose the level of notification I want for each channel :
- all message
- all, here, username
- username
- nothing
To change notification level, I can click on the 3 dot icon :
![Capture d’écran 2020-10-06 à 15.12.39.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/4d2bde45-d463-42bb-9124-12ea2fb699e7)

**Comment by hantt12** [comment]
There are some issues with this backlog:
I enable the notification for a certain channel but when the new message comes:
- No push notification (I didn't disable it from browser)
- The channel name is bold but there is no Number of unread messages as we used to have (Maybe this is a change? Please confirm)
@RomaricMourgues

**Comment by hantt12** [comment]
Hi @RomaricMourgues could you please help me check the notification for channel? 
I got notification for direct message but it's not working for channel

**Comment by RomaricMourgues** [comment]
Notifications workflow now:
- "All messages" notification option: you will get a red badge for any new thread
- "@all , @here or @myself ": you get a red badge only if you are mentioned or if this is a answer of a thread you are mentioned in
- "@myself ": you get a red badge only if you are mentioned or if this is a answer of a thread you are mentioned in
- "None": you never get a red badge
Event without badge, the channel will become bold if there is new content in it.
Direct channels are always in the "All messages" notification option.
