### ISSUE TITLE
[Story] Leave channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#313]
Epic #308 

**As an internal user, I can leave a public channel.** 

As an internal user, if I want to leave a channel, I can click on the 3 dots near to the channel name. I can click on the button "Leave the channel". 
If the channel is private, I have a confirmation popup to validate if I want to leave this channel. If it is a public channel, there is no popup. 
If my view was on this channel, I'm redirected in the first channel of the first channel of my list.
When I leave a channel, a message system is sent in the channel "USERNAME leave the channel"

**Comment by hantt12** [comment]
Sometimes I am not able to leave the channel

![Peek 2021-02-02 18-52.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/7d1ae5e9-8cca-49e2-bad1-933dfbd7ef44)

**Comment by hantt12** [comment]
This is not stable yet as I try today

![Peek 2021-02-03 19-44.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/34513f3c-9b4e-4e21-b30b-249b69125d18)

**Comment by hantt12** [comment]
Hi @RomaricMourgues Have you investigated the issue in my previous comment? because I still encounter it frequently

![Peek 2021-03-10 11-17.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/7333ea75-afcd-4205-b65e-2450b9149872)

**Comment by RomaricMourgues** [comment]
It should be fixed on QA now
