### ISSUE TITLE
[Story] Join channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#314]
Epic #308 

**As an internal user, I can join a public channel if I don't already participate.**

If I want to join a public channel, I can clic on the "+" icon and click "Join a channel". 
![Group 203.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/b1b0be9f-ef37-4767-bdbd-65becec9d8fa)

It opens a popup with the list of channels I'm not participating in yet. 
A search is available to filter these channels. The list is not displayed in one block (ie, there is a "load more" button).
Next to each channel, there is a "join" button.
When I join a channel, a message system is sent in this channel "XXXX join the channel"

![Join channel.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/bb6b9b76-adcb-4c01-9499-c9647a89e094)

**Comment by tlle14** [comment]
Hello @BenoitTallandier @RomaricMourgues 
Could you please confirm the channel list is only displays public channels or both public and private channels?

**Comment by RomaricMourgues** [comment]
Only public channels of course

**Comment by tlle14** [comment]
As in:
>A search is available to filter these channels. The list is not displayed in one block (ie, there is a "load more" button).
