### ISSUE TITLE
[Story] Add channel member

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#317]
Epic #308 

**As an internal user, I can add a member to a public/private**

As an internal user, if I want to add member in the channel where I am, I can click on the button "Add member of #316.
A popup appears with a user picker. The user picker search on all user (name, username,email) in the workspace. If a user is already in the channel, a label is shown near his name : "Already in this channel".
If what was enter in an email adresse and this email adresse is not used by other member in the company, a proposition appears with the email adresse and the button "Add as externe"

When I add someone, a message system is sent in the channel " XXX added YYY, ZZZ"

![Add members.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/1cbefaa5-bc7a-47bb-9227-b6b6cdfe3aeb)
![View members-1.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/3bd1d4bd-7270-47ed-87fa-a8e093b9b851)

**Comment by hantt12** [comment]
Hi @BenoitTallandier and @RomaricMourgues I am unable to add users to channel because the search function in this flow does not work

**Comment by RomaricMourgues** [comment]
Can you confirm it doesn’t work when you click the button “Add member » and then use the search bar in the second modal ?
We are working on a single modal version to simplify this.

**Comment by hantt12** [comment]
Hi @RomaricMourgues we cannot search for members to add
Steps:
1. Create a channel, when the "Add members in %channel_name%" modal is shown, CLOSE the model
2. Click (...) for the options and select Members 
3. Search for members

Currently the search result is not shown even though we type the correct username/email of the users

![Peek 2021-01-28 17-55.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a218a326-6ef0-4114-bb81-9c63a5769364)

**Comment by RomaricMourgues** [comment]
Yes this is because there is a BIG UX issue here, try this:

1. Open “…”
2. Click on “Add users”
3. Search users after the modal refresh

We are working on merging the two popups right now
