### ISSUE TITLE
[Story] Remove user from private channel 

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#318]
Epic #308 

**As an internal user, I can remove a member in a private channel**

As an internal user, if I want to remove user from a private channel, I open user popup #316. On each user, I can click on three dot and "remove". A confirmation popup explain that user "You are removing @XXX from #CHANNEL. He will no longer be able to see any of its messages. To rejoin the private channel, He will have to be re-invited"

![View members.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/76efa8b3-1026-4ba8-a36a-4126b96929eb)

**Comment by hantt12** [comment]
Discussion:
In my opinion, only channel creator/admin/owner can remove members from private channel. Currently any member can do it
What do you think?

**Comment by RomaricMourgues** [comment]
Any member can do it, the critical missing feature in the activity message showed in the channel when such action is taken.
When the activity message feature is available it will make sense :)
