### ISSUE TITLE
[Story] Create channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#321]
Epic #308 

**As an internal user, I can create a channel in the workspace**

As an internal user, when I want to create a channel, I click on the one next to "CHANNELS" and select "Create a channel". 

A popup opens and asks me the following informations:
- Channel icon
- Name of the channel
- Description of the channel (header),
- Private / Public
- If public, a switch to make the channel by default

If channel is private OR public and not by default: The next popup (when I validate) is the view to add user

![Create channel.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/732fd8b9-9120-49a0-aee1-0c11689ddedc)

**Comment by tlle14** [comment]
Hi @RomaricMourgues Could you please confirm if a guest is able to create a channel?

**Comment by RomaricMourgues** [comment]
Guest are not able to create channels, we are updating code thanks
