### ISSUE TITLE
[Story] Default Channels

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#322]
Epic #308 

As an internal user, when I am added to a workspace, I join the default channels.
As an internal user, when someone create a default channel, I am added to this channel.
As a internal user, I can create a default channel (with the popup of #321)

**Comment by chamerling** [comment]
## As an internal user, when I am added to a workspace, I join the default channels.

Get the default channel list, and add the current user to each channel.
By implementing this on the new backend, we need to get an event from the PHP backend and the user is added to a workspace, like

- event name: `workspace:user:added`
- payload: 
```
{
  "user": string,
  "company_id": string,
  "workspace_id": string
}
```

## As an internal user, when someone create a default channel, I am added to this channel.

1. Publish an event when a default channel is created (node backend)
2. Get the list of workspace users, and ass each user as member of the channel. This will push websocket events if users are connected and will update the channel list automatically on the client side

**Q**: How to get the list of workspace users

## As a internal user, I can create a default channel (with the popup of #321)

Nothing special here, add the option and explanation

**Comment by RomaricMourgues** [comment]
@chamerling we'll split the issue in two, the "import all current users in workspace" will be delayed for after we migrate users and workspaces to node backend.

**Comment by RomaricMourgues** [comment]
And I agree for the other points, I will add the event from php for node :)

**Comment by chamerling** [comment]
We should be able to hack the implementation while we do not have the users list on the node side by adding some events when the client get the list of workspace channels -> Check the default channels and add user to the default ones.

Anyway this will be resource consuming.
