### ISSUE TITLE
[Story] Log channel activities

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#324]
Epic #308 

**As an internal user, when I change a channel's information system send message in the channel.**

As an internal user, a message system is sent when I :
- change channel description => "XXX change the description"
- change channel name or channel emoji => "XXX renamed the channel to [emoji] [name]"
- add users => "XXX added YYY, ZZZ in the channel"
- remove users => "XXX removed YYY, ZZZ from the channel"
- add connector => "XXX added [Connector name] to the channel"
- remove connector => "XXX removed [Connector name] from the channel"

I receive message when someone  : 
- join the channel : "XXX joined the channel"
- leave the channel : "XXX left the channel" 

⚠️ message system doesn't trigger notification

**Comment by RomaricMourgues** [comment]
@chamerling @stephanevieira75 

Something like this: (please Christophe if you can give your wisdom about types names format

```
{
    type: "channel:activity:description", //Predefined list of activity types
    actor: {
        type: "user", //For now always user
        id: user-id, //Actor id
    },
    context: {
        type: "updated:channel",
        previous: {Channel Object},
        next: {Channel Object},
    }
}
```

```
{
    type: "channel:activity:members:added", //Predefined list of activity types
    actor: {
        type: "user", //For now always user
        id: user-id, //Actor id
    },
    context: {
        type: "added:users",
        added: [{User object}, {User object}],
    }
}
```

**Comment by chamerling** [comment]
What about:

```
{
    type: "channel:activity:description", //Predefined list of activity types
    actor: {
        type: "user", //For now always user
        id: user-id, //Actor id
    },
    context: {
        type: "diff",
        previous: {type: "channel", resource: Channel},
        next: {type: "channel", resource: Channel},
    }
}
```

and

```
{
    type: "channel:activity:members:added", //Predefined list of activity types
    actor: {
        type: "user", //For now always user
        id: user-id, //Actor id
    },
    context: {
        type: "add",
        array: [{type: "user", resource: User object}, {type: "user", resource: User object}],
    }
}
```

The context `type` gives the "type" of data to handle in the context: can be a diff, array add, array remove, etc.
Check if it fits all the use cases we currently have.

**Comment by RomaricMourgues** [comment]
We use the Christophe version 👍

**Comment by chamerling** [comment]
Just to know: Do we persist these messages?

**Comment by RomaricMourgues** [comment]
For the first implementation we do not persist the event.
But the generated message itself is persisted (as simple channel message)

**Comment by chamerling** [comment]
OK so why did you say that the message will be generated by the frontend then? Don't we have an issue here?

**Comment by chamerling** [comment]
Nice 👍🏼

**Comment by hantt12** [comment]
Skipped testing for adding connector because that feature is not ready  yet
Posted some bugs but they are minor so let's say we can pass this backlog
