### ISSUE TITLE
[Story] Hide direct channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#325]
Epic : #308 

**As a user, I can hide direct discussions.**
As a user, if I don't want to keep a direct discussion in my list, I can remove then by clicking on the cross.
![Group 204.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/c4b7acd4-2804-495c-b6e0-30e09b697d2a)

If the discussion that I removed was open in the main vue, I'm redirected to my first direct discussion.
When I remove the discussion, it is just for me. Other user that have the discussion in their list still have the discussion.
The content is not deleted. If I reopen this discussion, I can see the history.

**Comment by BenoitTallandier** [comment]
Related to #204

**Comment by hantt12** [comment]
A lot of console errors in the log. Besides,  sometimes the direct channel is still there after I try to delete it
![Peek 2021-02-02 16-22.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/018ed2ac-22a4-47df-ba7e-52c22b4abfdc)

**Comment by BenoitTallandier** [comment]
We need to remove the confirmation popup. It is not a critical action to hide discussion. With the current version, none of our user will hide their unused discussion. :)

**Comment by hantt12** [comment]
User can hide the conversation but there are many errors in the console log. Can you please have a quick look? @RomaricMourgues
