### ISSUE TITLE
[Story] See my direct channels

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#328]
Epic : #308 

** As a user, I can see direct message to someone that is in my company **

As a user, I can have direct discussion with member. I can see direct discussion under channels in the sidebar.
A direct discussion can take place either with a single interlocutor or with several interlocutors.
My direct discussions are sorted by lasted update.

**Comment by tlle14** [comment]
Hi @RomaricMourgues @BenoitTallandier could you please confirm? 

>As a user, I can have direct discussion with member
Do you mean the member by role or the member that belongs to the company? 


>My direct discussions are sorted alphabetically.
How the direct with multiple participants can be sorted alphabetically? 
I guess sorted by the latest update is better. The direct with the new messages will be on top.

**Comment by BenoitTallandier** [comment]
> Do you mean the member by role or the member that belongs to the company?
member that belongs to the company?

> My direct discussions are sorted alphabetically.
You're right we update the order

**Comment by tlle14** [comment]
Hi @BenoitTallandier 
Members that belong to the company include owner/admin/member and guest.

**Comment by BenoitTallandier** [comment]
> Members that belong to the company include owner/admin/member and guest.

Yes, :)
