### ISSUE TITLE
[Story] Add tab to channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#331]
Epic #308 

**As an internal user, I can add a tab (document, task, calendar) to a discussion channel.**

As a user, if I want to add a tab to a discussion channel, I click on the plus in the header of the channel. Then I choose wich type of tab I want to add (caledar, task, file). The tab appears in the header.

**Comment by hantt12** [comment]
Check this issue https://github.com/TwakeApp/Twake/issues/862

I will close this story
