### ISSUE TITLE
[Story] Add connector to a channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#332]
Epic #308 

**As an internal user I can add or remove a connector to or from a discussion channel.**

As an internal user, when I want to add or remove a connector, I can do that via the 3 dots and "connectors", and chose which connector I need.
![Capture d’écran 2020-10-06 à 17.08.23.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/1c4cb558-9d08-438d-8eba-1a525b8b1b79)

When I add a connector, a message system is sent "XXX added [Connector name] to the channel".
When I remove a connector, a message system is sent  "XXX removed [Connector name] from the channel"

**Comment by hantt12** [comment]
Hi @RomaricMourgues could you please confirm if this backlog is ready for test? If yes, please give me more details on how this function works

**Comment by RomaricMourgues** [comment]
It is not fully ready for testing yet because there is no connectors on QA.

You can test it on production in Linagora by adding a webhook and try to create messages by calling the generated web hook url.
