### ISSUE TITLE
[Story] Back / Next in browser

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#360]
EPIC #308

**As a user, I can user back & next of my browser**

As a user, if I am in the channel A, and go to the channel B, if I click on "back" of my browser, I'm redirected to the channel A.

As a user, if I open parameters, and then I click on "back", I'm redirected where I was before opening parameters

**Comment by tlle14** [comment]
Hello @RomaricMourgues @BenoitTallandier 
I don't see you describe the `Next button` behavior, is it ready to be tested? 
When I am on the previous screen, the `Next button` isn't enabled.

**Comment by tlle14** [comment]
Related issue: 
https://github.com/TwakeApp/Twake/issues/820
https://github.com/TwakeApp/Twake/issues/821

**Comment by hantt12** [comment]
Bug https://github.com/linagora/Twake/issues/1154
