### ISSUE TITLE
Desktop and mobile apps

### ISSUE THREAD

**Issue by cheerios911** [linagora/Twake#376]
**Is your feature request related to a problem? Please describe.**
are you guys planning on releasing the apps as well as opensource, mobile and desktop?

**Describe the solution you'd like**
I'd liek to brand the mobile apps as I have the other.

**Describe alternatives you've considered**
We have a customized version of rocket chat we are looking to replace with twake as I prefer the project management aspect of it but some clients have their own branded portal and would need that on the apps as well.

**Comment by BenoitTallandier** [comment]
Hi @cheerios911 

Sorry for the delay.
We are working an a new mobile app for Twake and we'll open source our development in few weeks.
For the desktop app, we'll publish it soon. Let us some time to prepare it.

**Comment by BenoitTallandier** [comment]
We just released our desktop app : https://github.com/TwakeApp/Desktop
I'll let you know when we'll start our new mobile repository
