### ISSUE TITLE
Clicking on push  notification does not open the right message

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#396]
**Describe the bug**
Clicking on push notification should open that message, not only Twake tab

**To Reproduce**
1. User A is opening another tab on his browser, not Twake
2. User B sends a message to user A
3. User A sees the push notification 
4. User A clicks on the push notification
5. User A sees the Twake tab, on the same channel that he opens before, not the message that he clicks on the push notification

**Expected behavior**
Open the message that User A clicks on the notification

**Desktop (please complete the following information):**
 - OS: Ubuntu
- Browser: Chrome, Firefox

**Comment by RomaricMourgues** [comment]
@stephanevieira75 this one should work now, but there is another issue: if notification point to a direct channel, it sometime changes the workspaces we are in (even if the direct channels are available from all the workspaces)
