### ISSUE TITLE
[Story] Responsive side bar

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#459]
Epic #308

As a user, when I am connected to a mobile device, I am able to have a responsive view of the application:
The sidebar (workspace + channels) is hidden. When I'm in a channel, a button appears on the left in the header. When I click on it, the side bar appears and I can change workspace. This sidebar is exactly the same as on the desktop application.

**Comment by hantt12** [comment]
There are some UI issues while user opens the sidebar on mobile devices. Please check
