### ISSUE TITLE
[Story] Edit channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#512]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a user 
When I look to edit a channel
And I am a workspace admin Or the channel creator
And I click on the 3 dots menu of the channel
And I choose to "Edit channel"
Then the edition popup appears
I can change the name, the description, and the confidentiality and the default visibility 
```

## Business case
When I made a mistake in the name or in the confidentiality of the channel, I want to edit it

## Criteria
- [ ] As a workspace admin or channel creator, when I click on the 3 dots of the channel, I can see "edit channel" in the menu
- [ ] As a workspace admin or channel creator, when I edit the name of the channel, every user member can see, in real time, the name of the channel changed. 

## UI UX Design
![Edit channel.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/57ec2ec7-5b5f-415f-88ed-f9e935a9276d)

## Related
Epic : #308

**Comment by tlle14** [comment]
Please confirm the allowed behavior for each role


  | Admin | Creator | Other member | Guest
-- | -- | -- | -- | --
Update name | o | o | o | x
Update description | o | o | o | x
Update privacy | o | o | o | x
Delete channel | o | o | x | x
Add member | o | o | x | x

**Comment by RomaricMourgues** [comment]
Public channels

  | Admin | Creator | Other members | Guest
-- | -- | -- | -- | --
Update name | o | o | o | x
Update description | o | o | o | x
Add member | o | o | o | x
Remove member | o | o | o | x
Update privacy | o | o | x | x
Delete channel | o | o | x | x

Private channels

  | Admin | Creator | Other members | Guest | Member not in the private channel
-- | -- | -- | -- | --
Update name | o | o | o | x | x
Update description | o | o | o | x | x
Add member | o | o | o | x | x
Remove member | o | o | o | x | x
Update privacy | o | o | x | x | x
Delete channel | o | o | x | x | x

**Comment by RomaricMourgues** [comment]
Every action should be reported in the channel like this:
"@userA removed @userB"
But it is not implemented yet (next week probably)

**Comment by tlle14** [comment]
Thank you

**Comment by tlle14** [comment]
Hi @RomaricMourgues 
A normal member is able to remove the creator from his channel => is this valid?

**Comment by RomaricMourgues** [comment]
Yes, the "channel creator" is an invisible information just here to prevent miss-clicks.

**Comment by RomaricMourgues** [comment]
Yes a member can remove the channel owner.
