### ISSUE TITLE
Wrong validation message on create new account

### ISSUE THREAD

**Issue by ashwin-07** [linagora/Twake#528]
**Describe the bug**
On creating a new account with username which is already taken, the email already exists message is shown instead of username already taken. 

**To Reproduce**
1. Go to  https://web.twake.app/#
2. Click on create an account
3. Provide already taken username
4. Provide a unique email (no account was created using that email)
5.Provide password
6.Click on continue

**Expected behavior**
Highlighting username field and displaying message "Username is already taken"

**Screenshots**
![image](https://user-images.githubusercontent.com/67856771/98148023-d0dd1200-1ef2-11eb-8d26-68ef60cc4d28.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86.0.4240.111

**Comment by BenoitTallandier** [comment]
Thank you for this feedback. We'll fix this!

**Comment by RomaricMourgues** [comment]
Now we use the Console software to manage accounts on Twake SaaS.

Create an account from Twake itself is depreciated.
