### ISSUE TITLE
Mail parameters aren't work

### ISSUE THREAD

**Issue by objeni** [linagora/Twake#531]
please check mail parameters with all mail systems and also add the encryption for log in because it is easy to use that and helpful for beginner.
I am in fact like  

> Uncaught Swift_TransportException: Expected response code 250 but got code "530", with the message "530 5.7.0 Must issue a STARTTLS command first. 192sm1892611pfz.200 - gsmtp

 only because the mail parameters are missing the encryption. I kindly request you please add this feature also because this helping with many beginners.

**Comment by RomaricMourgues** [comment]
Closing this issue as it will be done by Console in the near future.
