### ISSUE TITLE
iOS Twake app forgets selfhosted server domain

### ISSUE THREAD

**Issue by iFloris** [linagora/Twake#540]
**Describe the bug**
iOS Twake forgets a self hosted server domain when closed.

**To Reproduce**
1. Go to 'change server' below right 
2. Choose custom server domain
3. Login to custom server
4. Stop Twake iOS
5. Start Twake iOS again
6. See the initial Twake login screen with 'change server' below right

**Expected behavior**
Twake should remember a self hosted server setting and login

**Desktop (please complete the following information):**
 - OS: iOS iPad / iPhone
 - Browser iOS Twake app
 - Version 1.2.200

**Comment by BenoitTallandier** [comment]
Thank you for your feedback. 
We are working on a new version on mobile app. We'll fix this

**Comment by dichvuhuuich** [comment]
> Thank you for your feedback.
> We are working on a new version on mobile app. We'll fix this

Android OS 1.2.200 has the same problem, too, not remember a self hosted server setting and login. Please fix this!
