### ISSUE TITLE
User should be able to fill message field while sending previous message

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#580]
Currently, the message composer is disabled while the previous message is sent and until there is a response from the backend (I guess this is it, maybe something else). This leads to some UX issue: on a slow connection, I have to wait seconds to be able to write the next message.

Proposal:

1. Be able to write the next message
2. Block the submit (even if we can live without block...)

**Comment by hantt12** [comment]
This is a great improvement to UX thanks
