### ISSUE TITLE
“Reactivate” button does not turn off “Does not disturb” mode.

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#613]
**Describe the bug**

**To Reproduce**
1. Be sure that you are in Does not disturb at night
2. Click on “Notifications” icon
3. Press “Reactivate” button

**Expected behavior**
Pressing “Deactivate” button should work and enable notifications even in case and override “Out Of Working Hours” settings

**Screenshots**
![BugNotif](https://user-images.githubusercontent.com/22451567/100992783-e165c400-3554-11eb-986f-07abe0b0ae4a.gif)

**Comment by dichvuhuuich** [comment]
Where can I turn off “Does not disturb” mode?

**Comment by RomaricMourgues** [comment]
Hi,
You can do it from account preferences > notifications and set the hours from midnight to midnight.

**Comment by dichvuhuuich** [comment]
> Hi, You can do it from account preferences > notifications and set the hours from midnight to midnight.
> […](#)
Thank you, I see this preference, How can I change Local timezone on twake? I think now my site not follow my timezone.
