### ISSUE TITLE
Newsletter-like / readonly channels update

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#63]
### Update channels to handle thousand of users

- [ ] Queue of tasks for notifications (bulk of 100 notifications instead of the big loop)

- [ ] Store "workspace" instead of list of users for public channels

**Comment by BenoitTallandier** [comment]
@RomaricMourgues  Is it done with the channel migration ? :)

**Comment by RomaricMourgues** [comment]
The title of the issue we didn't do it.
The description yes it is done of course :)

**Comment by BenoitTallandier** [comment]
Cool, so I close this issue. The readonly channel will be in an other ticket :)
