### ISSUE TITLE
Add SaaS plan information and services

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#681]
In case we have the information a company did not pay

- [ ] Create a red header for non paying companies

- [ ] Create a service to get current plan and limitations in the future
- [ ] Add the plan name in the user menu and company menu with an "Upgrade" button with a link to the payment

**Comment by gplutus** [comment]
Why would you create a red-header for non-paying companies?  Would this be only for the paid platform admins?  Otherwise, you might dissuade people from using the platform.

**Comment by RomaricMourgues** [comment]
You’re right we need to ensure that doesn’t dissuade users. This will only affect users using paid plan but with expired card. This is also a temporary implementation before the next update.
It should not be displayed if you didn’t do anything wrong :)

**Comment by BenoitTallandier** [comment]
It's done
