### ISSUE TITLE
Problem while Deleting Workspaces

### ISSUE THREAD

**Issue by gregb100** [linagora/Twake#699]
**Describe the bug**
When deleting a workspace, the splash error is unreadable because it's too fast and in french.  

**To Reproduce**
1.  From within Twake, create a workspace
2.  Add a collaborator to workspace
3. Then click on "Workspace Settings-->"Delete workspace", enter the workspace name, then click delete.  The splash message pops up too quickly to read and is in french. 

**Expected behavior**
When deleting a workspace, with existing collaborators, the splash error indicating to first remove all collaborators should display to the user and require acknowledgment from the user.  It should also be in the localized language.

**Screenshots**
See attached.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: 87.0.664.66 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/36609341/103486844-19fbf600-4dbe-11eb-949b-93168ca6067a.png)

**Comment by RomaricMourgues** [comment]
Thanks, we’ll fix this soon.
For your information the message says :
« You must be alone in the workspace to remove it. Remove your collaborators and try again. »

Romaric

**Comment by gregplutus** [comment]
Thanks.  The splash was so fast, I couldn't even capture it for translation.  But I was able to do a screengrab, which helped me to translate it.  By the way, if you need an English speaker with business and technical acumen, let me know.  I'm willing to help with English translations.
