### ISSUE TITLE
[Story] Use Twake in mobile browser

### ISSUE THREAD

**Issue by gregb100** [linagora/Twake#703]
## User story summary
As a normal user, I'd like to use Twake in a mobile browser so that I can use Twake without depending on an app

## Notes
Some platforms allow a temp install of an app, that is removed when the app is closed.  However, allowing the user to access Twake in a mobile browser provides more flexibility.

**Comment by RomaricMourgues** [comment]
Hello @gplutus I don't understand your proposal as we already provide a browser version of Twake: https://web.twake.app/
Maybe are you refering to a web mobile version ?

**Comment by gplutus** [comment]
Yes, that's what I meant - I updated the issue
