### ISSUE TITLE
Twake Mobile App: On-prem Link Not Persistent

### ISSUE THREAD

**Issue by gregb100** [linagora/Twake#704]
**Describe the bug**
When using the Twake Android app, the on-prem custom link isn't persistent.

**To Reproduce**
1. Install Mobile App
2. Touch "Change Twake Server"
3. Close Twake App
4. Re-open Twake App

**Expected behavior**
After closing the App, the custom Twake server should be persistent until changed by the user.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 
 - Browser: N/A
 - Version: 11

**Comment by RomaricMourgues** [comment]
Thanks, we are doing big changes to the mobile app, I forward this to the mobile team.
