### ISSUE TITLE
FR Typo Canal vs Chaine

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#751]
On the center `C'est le premier message du canal`, on the sidebar we speak about `Chaines`: Should be the same.
Also a good translation to `This is the first message of the channel` should be `Ceci est le premier message de la chaîne`.

![Capture d’écran 2021-01-11 à 22 45 14](https://user-images.githubusercontent.com/264403/104242189-13751a80-545f-11eb-8c6e-49058aef6859.png)

Anyway, this is not a real message, should display something else like the channel description for example, or nothing...

**Comment by chamerling** [comment]
I continue to think that this message should be updated or deleted. It is useless.

<img width="1825" alt="Capture d’écran 2021-03-18 à 17 58 05" src="https://user-images.githubusercontent.com/264403/111666191-c5d8ad80-8813-11eb-9d0f-4983f6d2ba69.png">

**Comment by tlle14** [comment]
Retest pass! 
Thank @RomaricMourgues 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/bc0da012-c51b-4d72-b1b5-c0e86d276141)
