### ISSUE TITLE
Configuration as env. variables

### ISSUE THREAD

**Issue by aduprat** [linagora/Twake#755]
Currently the configuration is defined in files embedded in the code:
* for node, one file in this folder:
https://github.com/TwakeApp/Twake/tree/feature/2020.Q4.dev/twake/backend/node/config
* for PHP, one copy of this file:
https://github.com/TwakeApp/Twake/blob/feature/2020.Q4.dev/twake/backend/core/app/Configuration/Parameters.php.dist

In order to have Twake ready for K8S and Helm packages, we need to be able to override those configurations by giving env. variables to the `docker run` command.

- [ ] Merge node and php configuration files in one single json file
- [ ] Add ability to use environment variable if defined (priority: env variables > configuration file > default configuration file)
- [ ] PHP: Generate php parameters.php from configuration json (and env variables) file at startup
- [ ] Automate version number update in both backend conf and frontend conf

**Comment by chamerling** [comment]
The node backend already supports both environment variables and file. Environment variables are defined in https://github.com/TwakeApp/Twake/blob/feature/2020.Q4.dev/twake/backend/node/config/custom-environment-variables.json en overrides the ones defined in https://github.com/TwakeApp/Twake/blob/feature/2020.Q4.dev/twake/backend/node/config/default.json

**Comment by RomaricMourgues** [comment]
Yes, this is only for PHP :)
