### ISSUE TITLE
Cannot add user to channel

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#760]
**Describe the bug**
When company owner creates an user account,  the newly created account should be able to see the public channels and admin should be able to add that user accounts to private channels

**To Reproduce**
1. As Company owner/admin, create a new user account
2. Try to add the new user to a private channel
3. As the new user, log in and go to Twake 

**Expected behavior**
- Admin/company owner should be able to add user private channel
- New user should be able to see the public channels by default

Tested in https://web.qa.twake.app/

**Comment by RomaricMourgues** [comment]
Hello @hantt12 there is two things here:
- We do not support defaults public channels yet, so even public channels must be joined by each newcomers, the default channels task was affected today
- Inviting users to channels is broken because of missing ElasticSearch on QA (I'm on this one)
