### ISSUE TITLE
Special characters are cut off in the channel name

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#787]
# Actual Result
When opening a channel, special characters in the channel name are automatically cut off
![image](https://user-images.githubusercontent.com/69950655/104998619-1fb03780-5a5e-11eb-8380-db9b5d309058.png)

# Expected Result
The special characters should be able to display. If not, please restrict them in the creation steps.

**Comment by stephanevieira75** [comment]
Hi, i tried to reproduce this bug but it looks like i couldn't or it's already fixed. @RomaricMourgues Can you take a look at this please ? 

![Capture d’écran de 2021-07-02 11-35-21.png](https://images.zenhubusercontent.com/5f4e3d2d91dca0478164f0b5/903e3199-c95b-4c44-96db-896876f071b9)

**Comment by RomaricMourgues** [comment]
Outdated and fixed
