### ISSUE TITLE
User is automatically logged out when refresh the browser 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#819]
# Acutal Result
When refreshing the browser, User is automatically logout
![Peek 2021-01-27 16-18.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9c133900-0922-4cfc-8afe-02d58567f1f5)

# Expected Result
User shouldn't be logged out when refreshing the browser

# Environment
Chrome Ubuntu 87.0
QA environment

**Comment by BenoitTallandier** [comment]
It was fixed :)

**Comment by tlle14** [comment]
Retest pass!
![Peek 2021-06-16 14-26](https://user-images.githubusercontent.com/69950655/122176508-e1089700-ceae-11eb-9eae-ad5ede49c4d1.gif)
