### ISSUE TITLE
Create Channel > Missing the checkbox to show the channel in the channel list 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#822]
# Actual Result
Open a create channel form, it doesn't show the checkbox "Automatically show this channel in the channel list of all members"

# Expected Result
It should have the checkbox by default as in the story https://github.com/TwakeApp/Twake/issues/321

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/bbd67216-4c9f-4e93-adc2-b0ac03093135)

# Environment
Chrome Ubuntu
QA testing environment

**Comment by BenoitTallandier** [comment]
My bad, the design of this story is not good. 
By default, the checkbox is not checked
