### ISSUE TITLE
Member List > A member cannot see guest appear in the channel list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#852]
Related to #333

# Precondition
Story: https://github.com/TwakeApp/Twake/issues/316
A channel has a guest as a member

# Actual Result
A member in the channel cannot see guest appears in the member list
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/190b0485-585f-41ab-9236-8bc91abe76cf)

#Expected Result
A member should be able to see guest on the member list

# Environment
Chrome Ubuntu
QA testing environment

**Comment by BenoitTallandier** [comment]
Fixed
