### ISSUE TITLE
The channel should be selected when the corresponding context menu displays

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#854]
# Precondition
Selecting channel A

# Actual Result
Click on 3 dots button of  channel B, the context menu is opening but the channel B is still unselected
![Peek 2021-02-01 14-04.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6e34fc2b-c8b3-423b-8870-89d93676dd78)

# Expected result
When the context menu is opening, the corresponding channel should be selected.
It will avoid leaving/adding a member to the channel by mistake.

# Environment
Chrome/Firefox Ubuntu
QA testing environment

**Comment by RomaricMourgues** [comment]
@BenoitTallandier yes / no ? I had the inverse proposition from Fred few month ago

**Comment by BenoitTallandier** [comment]
In this situation, it is not possible to change the purple selection, because we didn't change the opened channel.
However, we should highlight the channel with the grey that we have on hover. 
I checked our competitors, they all solve this with this solution :)

**Comment by BenoitTallandier** [comment]
Done in production
https://images.zenhubusercontent.com/271994210/98402676-d4c0-42f8-9647-ddbde497c964/menu.mov
