### ISSUE TITLE
Members list is growing on the top when opening the members modal

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#873]
- [ ] Use a tooltip to display avatar user names under each image
- [ ] Fix growing values
- [ ] Reduce 'members' button size

1. Go to a channel, some members are displayed on the top
2. Open the members modal, scroll down
3. The members list is growing, the members list on the top is also growing, the counter is growing little by little
4. Close the modal
5. Open the modal
6. Scroll down
7. The members list on the top is growing again

The list was small at the beginning, after some time it is like this:

![Capture d’écran 2021-02-04 à 10 11 55](https://user-images.githubusercontent.com/264403/106874449-dd316080-66d5-11eb-8b74-d3c774d5deb8.png)

**Comment by RomaricMourgues** [comment]
- [x] Tooltip and quick view of members list
- [ ] popup with user search and add

The second point need some refactor on popup, will take more time than expected

**Comment by chamerling** [comment]
@RomaricMourgues I commented one of your commits. Anyway, how do you fix the thing that makes growing the list when we open the members modal: We paginate on the members list until we reach the end, so it grows...

**Comment by chamerling** [comment]
Also, Slack is doing some light UI on this: Display 3 members, then the counter:

![Capture d’écran 2021-02-09 à 18 48 04](https://user-images.githubusercontent.com/264403/107405287-72ce5500-6b07-11eb-9106-4ccf830a9ae1.png)

I really think that on the UI side, our `Members` button is too big. Anyway we do not have the members count value in the API response...

**Comment by RomaricMourgues** [comment]
The growing list is multiple bugs due to merging two popup in one, I will work on it tomorrow, just need to refactor code.

The issue currently is that we don't have the number of member in a channel (we had counters to implement you remember ? But we don't have them implemented yet :/ ).

So for now this will be a "..." unfortunately I think

For the member button size, yeah I agree, initially there was more buttons here (activity, members etc) like in Notion. But same: we didn't implement it. I will see to reduce the button.

**Comment by chamerling** [comment]
A button with a circle shape and just an icon should be enough for now.

https://ant.design/components/button/

Adding counters can be quick, I can work on it. Anyway it will not fix the growing list issue because we should not have to fetch all the members to display them on the top. What about doing a simple thing 'a la slack':

1. Fetch just N members, where N is < 10
2. Display the count
3. On click, open the members modal, where all the members are displayed if the user scrolls down

**Comment by RomaricMourgues** [comment]
This is what I started to do (the 3 last step you describe), but still I need to refactor the modal code before :)

**Comment by BenoitTallandier** [comment]
It's fixed
