### ISSUE TITLE
Implement channel counters

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#908]
DB model be like:

```cson
{
	//Primary key
	"company_id": "uuid-v4",
	"workspace_id": "string", // "uuid-v4" | "direct"
	"channel_id": "uuid-v4",
	"type": "string" // "members" | "guests" | "messages",

	"value": 0,
}
```

- [ ] Add to ORM
- [ ] Add business logic to channel service to be able to count members, guests, messages
- [ ] Add counters in REST responses
- [ ] For members and guests, randomly or when listing users, do a recount and reset the counter (we cannot reset a counter, we must apply the correct delta to it instead)

**Comment by RomaricMourgues** [comment]
@romanesko could you also add a message count company-wide in addition to the per-channel count?
