### ISSUE TITLE
Make translation easier to do using maybe Weblate

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#93]
**Is your feature request related to a problem? Please describe.**

Translation are done in a plain json (not easy)

**Describe the solution you'd like**
We could use Weblate or be compatible with Poedit.

See the thread here: https://community.twake.app/t/solved-add-translation-on-twake/26/3

**Comment by jhjacobs81** [comment]
would it be possible to use transifex instead??

i allready use it for other OSS projects as well, its web based, so no need for anyone to install programs and download files etc. etc.

**Comment by RomaricMourgues** [comment]
Thanks for giving us other alternatives, we did not choose a solution yet 👍

**Comment by jhjacobs81** [comment]
i rather like Twake 👍 

It can be a very strong competetor to MS Teams, Rocket.Chat (which i currently use at work) and MatterMost.

MS Teams: well its cloud so that fell off the wagon anyway
Rocket.Chat: that was what we went with due to our demands for such tool
MatterMost: Was my favorite (because of the workplaces) but the OSS versio has no LDAP support.

**Comment by Mejans** [comment]
Hello,
any news for us?

**Comment by RomaricMourgues** [comment]
Hello, sorry for the delay, we didn't have any time for this yet. We now have somebody (also having a lot of things to do) that can work on this point.

@aduprat if it doesn't take too much of your time it would be nice to have this live on one of our servers :) . I don't know how we can link it to our git to always have the latests files.

We'll try to do this as soon as possible, a big thanks for reminding us!

**Comment by Mejans** [comment]
Hello @RomaricMourgues où en est le sujet ?
Cordialement

**Comment by BenoitTallandier** [comment]
It's done https://hosted.weblate.org/projects/linagora/
