### ISSUE TITLE
Random issue when user tries to join a channel

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#985]
![2021-03-04_17-09.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a92c0297-fada-4705-b3a3-6c2c04ac07f7)

**Comment by BenoitTallandier** [comment]
It is working now. I close the issue.

https://user-images.githubusercontent.com/22451567/149941186-71eaed22-bdd0-4354-9db2-440b47aeda3a.mov
