### ISSUE TITLE
Channel member list is not updated after an user joins in

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#988]
**Describe the bug**
It's only until users refresh the page they can see the updated member list

**To Reproduce**
1. User A creates a public channel
2. User B is in the same workspace
3. User B search and join the above channel
4. User A and User B check the list of the channel members

**Expected behavior**
User B should be in the list of channel member

**Screenshots**
Users have to refresh the page to see the updated list

**Comment by BenoitTallandier** [comment]
I tested on my side, it seams to work now.
Could you try again @hantt12  ? :)

**Comment by hantt12** [comment]
I will test and update soon

**Comment by tlle14** [comment]
The issue is no longer exists
Retest pass!
![Peek 2021-06-03 16-12.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fa5da1ef-8da4-41d2-b767-7323bc91a15d)
